### ISSUE TITLE
[Requests] Add next & previous button in archive page

### ISSUE THREAD

**Issue by pacientes** [adityatelange/hugo-PaperMod#100]
Hello,
Thank you for making a awesome theme.

What is the maximum number of posts on the archive page?
If its not defined..

The page seems to be too long like this...
![image](https://user-images.githubusercontent.com/22834091/100771208-7ecfd380-3441-11eb-81ca-1b66abe6e7e6.png)

Can I add a button to the archive page?

**Comment by adityatelange** [comment]
@pacientes Archive is like a index of all the stuff you have written on the blog, we don't need a prev/next button for it !

On home page pagination is done ! so what would be the difference between an archive page and home page ?!

https://singhkays.com/archives/ is also long 

https://singhkays.com/tags/ is also long 

and IMO that's how it should be :))

**Comment by pacientes** [comment]
Thanks you! i got it!
