### ISSUE TITLE
[BUG] The posts won't show on the homepage if I have another folder in content/ that is before alphabeticaly

### ISSUE THREAD

**Issue by divad1196** [adityatelange/hugo-PaperMod#1006]
Hi,

I've been searching why the posts are not showing on my homepage for half a day now so I am asking my question here.
I've been following the features guide but nothing is mentioning it.
I took a look at the example branch where it does work but I couldn't find the option to use, so I removed every until it looked like this:
```
.
├── config.yml
├── content
│   └── posts
│       └── papermod-faq.md
├── LICENSE
├── README.md
└── themes
    └── hugo-PaperMod
        ├── ...
          ...
```

The config.yml file looks like this
```yml
baseURL: http://example.org/
title: PaperMod

theme: hugo-PaperMod
```

and the only file left `content/posts/papermod-faq.md`
```markdown
---
title: "FAQs"
summary: Frequently Asked Questions
date: 2021-01-20
# aliases: ["/papermod-how-to-guide"]
# tags: ["PaperMod"]
# author: "Aditya Telange"
# draft: true
# aliases: [/posts/papermod/papermod-how-to]
# weight: 3
---

```

I finally discovered that, when removing my other folder in content/, it worked perfectly.
I did some other tests:
If any other folder is alphabetically before "posts", (e.g. "abc"), nothing will be shown
Otherwise, if we only have other folder that are alphabetically after "posts" (e.g "xyz"), it works fine.

I think this is a bug?

**Comment by chaderenyore** [comment]
Same Problem here too, Only content in one sub directory are shown, I don't know why this happens.

**Comment by adityatelange** [comment]
Kindly read: https://gohugo.io/functions/where/#mainsections

**Comment by divad1196** [comment]
@adityatelange  Hi, I had not modified anything and the problems is still there when using this theme out of the box.
The reason seems to be an error in the them layout.

After having provided all the informations needed, I think your response is kind of disrespectful. Especially, It does not seem you have at least tried the steps to reproduce.
Can you please re-open this issue and checks this bug correctly?

**Comment by adityatelange** [comment]
> @adityatelange Hi, I had not modified anything and the problems is still there when using this theme out of the box. The reason seems to be an error in the them layout.


There's no error, this is how hugo functions

> After having provided all the informations needed, I think your response is kind of disrespectful. Especially, It does not seem you have at least tried the steps to reproduce. Can you please re-open this issue and checks this bug correctly?

Oh come on, this is not disrespectful at all

**Comment by divad1196** [comment]
@adityatelange I know how the filters work, I did a fix myself and someone else has complained about it.
For my special usage, I had replace `.RegularPages` with `.Site.RegularPages` and remove some other parts to fix the issue:
https://github.com/adityatelange/hugo-PaperMod/blob/master/layouts/_default/list.html#L39
I think you miss used the hugo's variables. 

And yes, it is. linking the documentation for a basic hugo filter, to someone who knows how hugo works on top of it, when there are no customization involved is kind of rude. You have clearly not tested the issue at all. The only reason I made this issue was to help you improving your theme. I gain nothing from it.

Put all the down thumbs you want. Have a nice day.

**Comment by adityatelange** [comment]
> @adityatelange I know how the filters work, I did a fix myself and someone else has complained about it. For my special usage, I had replaced `.RegularPages` with `.Site.RegularPages` and remove some other parts to fix the issue: https://github.com/adityatelange/hugo-PaperMod/blob/master/layouts/_default/list.html#L39 I think you misused the hugo's variables.
> 
> And yes, it is. linking the documentation for a basic hugo filter, to someone who knows how hugo works on top of it, when there are no customization involved is kind of rude. You have clearly not tested the issue at all. The only reason I made this issue was to help you improving your theme. I gain nothing from it.
> 
> Put all the down thumbs you want. Have a nice day.

You could have used the bug template if you care so much about improving theme, possibly linked a demo repo where this is reproducible. Don't put the blame on me, I won't test it without the context being clear.

**Comment by divad1196** [comment]
` If any other folder is alphabetically before "posts", (e.g. "abc"), nothing will be shown` I assumed it wasn't to hard to understand.

If asked, I would have provided you what you needed. You did not, and I don't want to spend more time on childish fight.
Have a nice day.

**Comment by adityatelange** [comment]
> ` If any other folder is alphabetically before "posts", (e.g. "abc"), nothing will be shown` I assumed it wasn't to hard to understand.
> 
> If asked, I would have provided you what you needed. You did not, and I don't want to spend more time on childish fight. Have a nice day.

@divad1196
Just tested it for _your_ sake, **works fine on my setup**. NOT A BUG. Stop frowning, go take a walk.

![image](https://user-images.githubusercontent.com/21258296/187036185-d0c2cf24-049f-4a06-9af7-24b28227a3db.png)
![image](https://user-images.githubusercontent.com/21258296/187036201-e4e35a27-3cc6-468f-bbfb-71f1c49e6a84.png)
