### ISSUE TITLE
Tags on taxonomy page look different from elsewhere

### ISSUE THREAD

**Issue by kdkasad** [adityatelange/hugo-PaperMod#101]
I noticed that the tags on the taxonomy page (e.g. [here](https://adityatelange.github.io/hugo-PaperMod/tags/)) look different from on posts.

Taxonomy page:
![tags in taxonomy page](https://user-images.githubusercontent.com/63574107/100832249-5681ae00-341c-11eb-859a-29500bac970f.png)

Bottom of post:
![tags in post](https://user-images.githubusercontent.com/63574107/100832372-90eb4b00-341c-11eb-9036-fbe8ba43256e.png)

I think that one of the two styles should be changed so they match a bit better. Personally, I like the look of the tags in the post (i.e. second image).

**Comment by adityatelange** [comment]
Why is it necessary to look same ? I think it is Fine !

Thanks for point that out ! We are missing other taxonomies on posts and only tags are shown !
Will look into this how to better match the design and support for custom taxonomies ! :))
