### ISSUE TITLE
Search functionality

### ISSUE THREAD

**Issue by piyushpaliwal** [adityatelange/hugo-PaperMod#103]
Are you by any chance planning to incorporate search functionality as well?

**Comment by adityatelange** [comment]
@piyushpaliwal will look into it :+1:

**Comment by piyushpaliwal** [comment]
Thanks @adityatelange, let me know if you consider this as a priority feature request or just another item in the backlog. I know this is a side project for you and hence I cannot ask for any ETAs but any insights to this would greatly help.

Thanks for the awesome work on the base theme.

**Comment by piyushpaliwal** [comment]
wow, that was super fast @adityatelange. Thanks for the effort. Any setup instructions that we should be aware of?

**Comment by adityatelange** [comment]
> wow, that was super fast @adityatelange. Thanks for the effort. Any setup instructions that we should be aware of?

already added to docs checkout features inside demo site !

**Comment by piyushpaliwal** [comment]
> wow, that was super fast @adityatelange. Thanks for the effort. Any setup instructions that we should be aware of?

oops, please ignore. I think you guys have already updated the docs, I'll look into it.
