### ISSUE TITLE
schemajson breadcrumb breaks minify when baseURL=/

### ISSUE THREAD

**Issue by mh-cbon** [adityatelange/hugo-PaperMod#1045]
Hi,

When building the site with minify=true and base-url=/ the schema json miss a comma. 

This did not happened when base-url has more than 1 slash.

Several tickets were opened around that.

It is at 
https://github.com/adityatelange/hugo-PaperMod/blob/master/layouts/partials/templates/schema_json.html#L48

A fix is to declare an consume a bool instead of trying to count the number of slash. 

like in

```
  "itemListElement": [
  {{- $zzz := false -}}
  {{- range $index, $element := $bc_list }}
    {{- $zzz = true -}}
...
    {{- end }}

  {{- end }}
  {{- /*  self-page addition  */ -}}
  {{- if $zzz }}, {{end }}
```

**Comment by FatChicken277** [comment]
+1 please reopen this pr https://github.com/adityatelange/hugo-PaperMod/pull/614

**Comment by adityatelange** [comment]
baseURL should be properly configured. Avoid setting it as `/`
https://gohugo.io/getting-started/configuration/#baseurl
