### ISSUE TITLE
how to enable code block highlights?

### ISSUE THREAD

**Issue by cha2hyun** [adityatelange/hugo-PaperMod#1046]
Hello, i jsut forked and deploy it through github pages.

I just copy & paste markdown syntax guide in sample page but code block highlights doesnt work. 
![image](https://user-images.githubusercontent.com/56015532/191421721-b52a8248-0720-4ada-a7ce-c603d7a7d839.png)

url : https://cha2hyun.github.io/posts/etc/markdown-syntac-guide/
repo : https://github.com/cha2hyun/blog/blob/master/content/posts/Etc/markdown%20syntac%20guide.md

any help for this issue ?🙏

**Comment by cha2hyun** [comment]
Self Answer 🥹

- change the config.yml 
- if anyone has same problem, you may copied config.yml from here(https://github.com/adityatelange/hugo-PaperMod/blob/exampleSite/config.yml) and  default value is disableHLJS:true

config.yml
```yml
  assets:
    # disableHLJS: true  <- disable here and highlights will work
```

**Comment by TheQueenIsDead** [comment]
Looks like you might need to generate the stylesheet:
https://github.com/adityatelange/hugo-PaperMod/issues/901

Make sure you link the style once generated (In your [config](https://github.com/cha2hyun/blog/blob/master/config.yml#L143))

The command will look like the one mentioned in the link above:
```
hugo gen chromastyles --style monokai --highlightStyle 'bg:#474733' > assets/css/extended/monokai.css
```

**Comment by cha2hyun** [comment]
> Looks like you might need to generate the stylesheet:
> 
> https://github.com/adityatelange/hugo-PaperMod/issues/901
> 
> 
> 
> Make sure you link the style once generated (In your [config](https://github.com/cha2hyun/blog/blob/master/config.yml#L143))
> 
> 
> 
> The command will look like the one mentioned in the link above:
> 
> ```
> 
> hugo gen chromastyles --style monokai --highlightStyle 'bg:#474733' > assets/css/extended/monokai.css
> 
> ```

Thanks. thats why my codeblock looks ugly. thanks for help i will try 👍

**Comment by cha2hyun** [comment]
## Method for enable code block when copied config.yml from exampleSite

1. If anyone has code block not highlighting issue like me, you might copied config.yml from here(https://github.com/adityatelange/hugo-PaperMod/blob/exampleSite/config.yml)

2. Make css file. (thanks for @TheQueenIsDead) Check > #901 
```shell
# check your assets folder path
# In this command, it generate monokai.css
hugo gen chromastyles --style monokai --highlightStyle 'bg:#474733' > themes/PaperMod/assets/css/extended/monokai.css
``` 

3. edit config.yml
```yml
markup:
  highlight:
    style: monakai
```

4. done
<img width="777" alt="image" src="https://user-images.githubusercontent.com/56015532/191643580-80e78032-be4f-4eb0-a8b2-23b647cbcbe1.png">
