### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by majesticio** [adityatelange/hugo-PaperMod#1056]
UseHugoToc: true appears to break ToC. UseHugoToc: false fixes it.
Great theme!

**Comment by Khoa-NT** [comment]
For more information.

UseHugoToc: true
![image](https://user-images.githubusercontent.com/12138158/193867460-4b201f31-f743-4d92-b4e6-45afc72a5f1a.png)


UseHugoToc: false
![image](https://user-images.githubusercontent.com/12138158/193867901-a201ec51-6b7e-4910-8e66-055456627ec1.png)

**Comment by adityatelange** [comment]
> UseHugoToc: true appears to break ToC. UseHugoToc: false fixes it. Great theme!

hugoToc is not enabled by default. Not a bug
