### ISSUE TITLE
[Feature Request] Add ability to customize which heading tags are included in the ToC

### ISSUE THREAD

**Issue by Nufflee** [adityatelange/hugo-PaperMod#1068]
It'd be great if it's possible to customize which heading tags (like `h1`, `h2`, `h3` etc.) are included in the Table of Content as it gets very long and nested when using many of them all the way down to `h6`. I'd be happy to help implementing this, but I am new to Hugo so I'm not sure what the best way to go about it would be.

I copied the `toc.html` partial template into my `layouts/partials` folder and edited it to only consider `h1` and `h2` tags as a workaround:

| ![image](https://user-images.githubusercontent.com/19150550/195958300-2a913464-3884-4109-9392-68f655742797.png) | ![image](https://user-images.githubusercontent.com/19150550/195958282-876d4fb6-4e6a-441c-bfab-45e651d6454f.png) |
|-----------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------|
| Default `toc.html` template                                                                                     | Customized `toc.html` template which only includes `h1` and `h2`                                                |

**Comment by adityatelange** [comment]
You can use Hugo's ToC generator by setting `useHugoToc` to true. Hugo then has option to customize which heading tags are included in the ToC https://gohugo.io/getting-started/configuration-markup/#table-of-contents
