### ISSUE TITLE
Anchored headers are created but the URL does not contain the hash

### ISSUE THREAD

**Issue by joaopgrassi** [adityatelange/hugo-PaperMod#108]
Hello! 

I noticed that the headers are created with the appropriate anchor (via `anchored_headings.html`), but when you click on a header, the URL does not contain the `#id`. This is not great since (in my view) the point of headings is that you can click and share that exact location with others. 

Investigating more, I saw that it's due the smooth scrolling handling in `footer.html`. Smooth scroll is awesome, but I would like to have both worlds :)

I would be more than happy to send a PR to fix it, but I'm not sure the best way. We could do like `history.pushState(null, null, `#${id}`);` at the end of the function so the URL is updated.. but then there's problems like the "scroll-to-top" button also adding `#top` to the URL which is not great.

Also I saw this: [Heading link example ](https://gohugo.io/getting-started/configuration-markup#heading-link-example), which uses markdown render hooks. I'm rather new to Hugo, but it seems that it's not the same way that is done in the theme? 

Thanks for this awesome theme btw!

**Comment by joaopgrassi** [comment]
One way would be to enable `scroll-behavior` to the whole `html` via css like here: https://gomakethings.com/smooth-scrolling-links-with-only-css. Also we can use a media query to make sure it follows the users system settings (less motion) https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion. 

With this then we don't need the js code anymore.

Another great article on this (the accessibility part around the `#` in the URL): https://css-tricks.com/smooth-scrolling-accessibility/

**Comment by adityatelange** [comment]
@joaopgrassi 
> I noticed that the headers are created with the appropriate anchor (via `anchored_headings.html`), but when you click on a header, the URL does not contain the `#id`. This is not great since (in my view) the point of headings is that you can click and share that exact location with others.

In my PoV, user is supposed to right click on `#` or long-press on (mobile devices) it in order to copy the link !
Much better than copying URL from browser !

> Investigating more, I saw that it's due the smooth scrolling handling in `footer.html`. Smooth scroll is awesome, but I would like to have both worlds :)

> I would be more than happy to send a PR to fix it, but I'm not sure the best way. We could do like `history.pushState(null, null, `#${id}`);` at the end of the function so the URL is updated.. but then there's problems like the "scroll-to-top" button also adding `#top` to the URL which is not great.
> 
> Also I saw this: [Heading link example ](https://gohugo.io/getting-started/configuration-markup#heading-link-example), which uses markdown render hooks. I'm rather new to Hugo, but it seems that it's not the same way that is done in the theme?

I'll look into it :)


> Thanks for this awesome theme btw!

Welcome :))

**Comment by joaopgrassi** [comment]
>In my PoV, user is supposed to right click on # or long-press on (mobile devices) it in order to copy the link !
Much better than copying URL from browser !

Hum.. not sure this is the general behaviour users expect. The default behaviour of the browser is to add the #id to the URL. 

For example look at this page from the Microsoft Docs: https://docs.microsoft.com/en-us/windows/terminal/customize-settings/global-settings

Once you hover on a heading, the anchor icon shows (same as its done by the theme). But once you click on it, it "moves" you to that part of the page and adds to the URL/history. As a developer I always copy from the URL. As soon as I published my blog, others were commenting that this feature was not working =/

It's also important for people using screen readers.. the way it is now defeats the accessibility part of the anchor tags. Just some food for thought.

In another note, you see a way I can maybe override this? Or maybe we could make it optional in the theme? (smooth scrolling). I know I can just copy the footer and change it.. but then it's hard to conciliate with changes from the theme.. so I would want to avoid it if possible.

**Comment by adityatelange** [comment]
@joaopgrassi based on your suggestions I have worked on a fix for this will push soon :wink:

**Comment by joaopgrassi** [comment]
Nice! If  you need help with anything.. let me know. Curious to see what solution you came up with ;)

**Comment by adityatelange** [comment]
@joaopgrassi Let me know if that works fine !

**Comment by joaopgrassi** [comment]
Hey. It seems to work, but I found two things:

1. The "scroll to top" button adds just the `#` to the URL. I don't really mind having the whole thing `#top` but not sure. 
2. If you add the `scroll-behavior` via css, then we don't need the script here: https://github.com/adityatelange/hugo-PaperMod/commit/80954de8bd085a3d5876e86c878088f911307c52#diff-1236858a4652b74ac20c849dced102285e73793914ce9093a079f5466bb7a938R35
as it will basically do nothing.

**Comment by adityatelange** [comment]
> 2. If you add the `scroll-behavior` via css, then we don't need the script here: [80954de#diff-1236858a4652b74ac20c849dced102285e73793914ce9093a079f5466bb7a938R35](https://github.com/adityatelange/hugo-PaperMod/commit/80954de8bd085a3d5876e86c878088f911307c52#diff-1236858a4652b74ac20c849dced102285e73793914ce9093a079f5466bb7a938R35)
>    as it will basically do nothing.

Yeah I missed it ! I remembered #64 coz of which didn't tested that :p
