### ISSUE TITLE
Document `site.Params.mainSections` usage

### ISSUE THREAD

**Issue by cgalo5758** [adityatelange/hugo-PaperMod#1082]
I was pulling my hairs out trying to figure out why my homepage would only show content from only one section. I found out that the theme filters sections for the homepage using the [mainSections](https://gohugo.io/functions/where/#mainsections) parameter; This means that the homepage will by default show only the section with the most content.

It should be added to the documentation that you must explicitly set the section you want displayed or what the default behavior is.

Feel free to copy paste stuff from this issue to the wiki.

To show multiple sections, list the sections you want in your config. An example in YAML:
```
params:
  mainSections:
  - blog
  - docs
```

It might also be worth considering making a "use all sections" option.

**Comment by adityatelange** [comment]
Done :heavy_check_mark:  [here](https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#posts-from-only-one-foldersection-visible-on-home-page)
