### ISSUE TITLE
post-single css overrides bottom margin on definition lists in Safari

### ISSUE THREAD

**Issue by f00b4r0** [adityatelange/hugo-PaperMod#1099]
This CSS block here:
https://github.com/adityatelange/hugo-PaperMod/blob/4bd96d62719b044ba28380ad2cb06c57a631afca/assets/css/common/post-single.css#L109-L113

defines `margin: 0` and comes after the block here:
https://github.com/adityatelange/hugo-PaperMod/blob/4bd96d62719b044ba28380ad2cb06c57a631afca/assets/css/common/post-single.css#L88-L94

In Safari, the latter `margin: 0` overrides the `margin-bottom` which results in no space between end of list and next paragraph, contrary to all other elements.

Either removing the extra `margin: 0` or reordering the blocks fixes the issue.

HTH

**Comment by adityatelange** [comment]
this is very late now, however please raise issue with bug report template if this can still be reproduced .
