### ISSUE TITLE
How can I get a dark theme like your demo site?

### ISSUE THREAD

**Issue by codertesla** [adityatelange/hugo-PaperMod#11]
Thanks for your paperMod theme which is clean and fast.

But how can I get a dark theme like what's like as your demo site?

By the way, could you put an Example Site in the theme folder like other themes ? 

Thanks again.

**Comment by adityatelange** [comment]
Glad you liked it 🎉

Here is source for demo site : https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite

Read this for enabling dark theme : https://github.com/adityatelange/hugo-PaperMod/wiki/Features#default-theme-lightdark

**Comment by codertesla** [comment]
> Glad you liked it 🎉
> 
> Here is source for demo site : https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite
> Demo site also includes lot of documentation, you may browse it here https://adityatelange.github.io/hugo-PaperMod/
> 
> Read this for enabling dark theme : https://github.com/adityatelange/hugo-PaperMod/wiki/Features#default-theme-lightdark

Wow. I got that dark theme finally.

Thanks.

Although I had to copy and past switch from yaml strings to toml one which is a little difficulty for me.
