### ISSUE TITLE
Next/Previous post or related posts under single layout

### ISSUE THREAD

**Issue by piyushpaliwal** [adityatelange/hugo-PaperMod#110]
It would be good to have couple of links below the posts which takes you to next post or the previous post. Currently the only option is to either go to the home page or from the menu.

**Comment by singhkays** [comment]
👍  this would be useful

**Comment by bee-san** [comment]
I agree, this would be very nice :)

**Comment by bee-san** [comment]
If you implement it, do it via tags/categories first but with the ones that have the most intersection first.

So for the tags, where each set is a post

```
{tech, programming, python}
{tech, cooking}
{tech, python}
```

And given the post has the tags `{tech, programming, python}`  it should display the most relevant posts being in the order of:
1. `{tech, programming, python}`
2. {tech, python}
3. {tech, cooking}

**Comment by adityatelange** [comment]
What could be the best position to add this on the single page  ?

---

<kbd>![image](https://user-images.githubusercontent.com/21258296/104763291-a5e12b00-578b-11eb-98d4-05d8a9bdf61d.png)
</kbd>

**Comment by kdkasad** [comment]
> What could be the best position to add this on the single page ?

I think in between the tags and the social links would be best.
