### ISSUE TITLE
Give some tips on how to set the favicon 

### ISSUE THREAD

**Issue by perhapzz** [adityatelange/hugo-PaperMod#1109]
### Discussed in https://github.com/adityatelange/hugo-PaperMod/discussions/953

<div type='discussions-op-text'>

<sup>Originally posted by **keitng** June 20, 2022</sup>
I've tried putting favicon.ico into /static/favicon/ and adding 
`params:
     assets:
          favicon: "/static/favicon/favicon.ico"`

into config.yml but it still doesn't work. Help appreciated, thanks</div>

### Can we give some tips on how to set the favicon?

I recently encountered the same issue as described in this discussion thread, was unsure how to properly set up the file layout and configure the favicon in the config file. It was not until I found Emil Arvidsson's solution that I was able to successfully resolve the issue.

I want to express my gratitude to Emil for his helpful suggestion. In addition, I believe it would be helpful to include a few small hints or tips, such as noting the location of a particular folder or including a default set of icons in the demo for easier reference. These types of additions could make it easier for new users to get started with Papermod.

**Comment by adityatelange** [comment]
Discussed in https://github.com/adityatelange/hugo-PaperMod/discussions/953

**Comment by yimmy23** [comment]
> 

where can I find solution? I meet the same question. I didn't find Emil Arvidsson's solution. #953 is not useful for me and @adityatelange 's answer in #953  does not work for me.

**Comment by ile** [comment]
> Discussed in #953

I'm still having problems with this: https://github.com/adityatelange/hugo-PaperMod/discussions/953#discussioncomment-8279490
