### ISSUE TITLE
[Featrue] Add setting to hide page

### ISSUE THREAD

**Issue by ghost** [adityatelange/hugo-PaperMod#1110]
Could we add a setting to hide pages from frontpage, archives, tags, rss, etc?
It's a useful feature, some popular themes do this.
My idea is to create a front matter type `hidden`.

**Comment by 2019YKL** [comment]
I really hope to add this feature.
I write a weekly newsletter on it, but I don't want all of them to be displayed on the homepage.

**Comment by dangkaka** [comment]
👍

**Comment by RoneoOrg** [comment]
Adding `hiddenInHomelist: true` to your front matter should solve this.
(This feature seems undocumented, please submit a merge request if you can)

@2019YKL @iMacyhs

**Comment by RoneoOrg** [comment]
@0f443ab1 Could you please mark this issue as closed/ solved to keep the tracker clean?
