### ISSUE TITLE
Css not loading

### ISSUE THREAD

**Issue by viralvaghela** [adityatelange/hugo-PaperMod#1118]
Hi, when I am deploying on the localhost, it works fine but on github pages or https://dulcet-custard-83bbf5.netlify.app/, It does not load the CSS and looks ugly, any solution? why it's happening?
Thanks!

**Comment by adityatelange** [comment]
Wrong repo, can't really help 
![image](https://user-images.githubusercontent.com/21258296/210166597-879a5800-9377-4454-b52e-b06d65662d8b.png)

**Comment by viralvaghela** [comment]
oops, sorry man, there were 40+tabs open and I missed correct one, my bad :/
