### ISSUE TITLE
[bug] custom taxonomy 'tags', 'category' url

### ISSUE THREAD

**Issue by sunuazizrahayu** [adityatelange/hugo-PaperMod#112]
i change my *tags* + *category* url to
```
taxonomies:
  category: category
  tag: tag
```

on bottom of post, it still produce '/tags/foo', not '/tag/foo'. and on /tag/ it produce blank (tags list not showing)
![bug-tag](https://user-images.githubusercontent.com/18210880/101355210-d8645200-38c8-11eb-9a53-a10669f9f0ce.png)

**Comment by sunuazizrahayu** [comment]
solved change taxonomy url -> https://discourse.gohugo.io/t/how-to-get-permalink-of-taxonomies-in-templates/12927/6
add permalink on config.toml
```
tags: /tag/:slug/
categories: /category/:slug/
```
it will change
```
/tags/foo    -->    /tag/foo
/categories/barr --> /category/bar
```

next, how to change "tags" dynamic on footer of post?

**Comment by adityatelange** [comment]
> next, how to change "tags" dynamic on footer of post?

Didn't get that ?!

**Comment by sunuazizrahayu** [comment]
> 
> 
> > next, how to change "tags" dynamic on footer of post?
> 
> Didn't get that ?!

i just found how fix this issue.. i will send PR
