### ISSUE TITLE
click on wiki home quick links return 404 pages

### ISSUE THREAD

**Issue by wswind** [adityatelange/hugo-PaperMod#1127]
https://github.com/adityatelange/hugo-PaperMod/wiki

<img width="278" alt="image" src="https://user-images.githubusercontent.com/18399096/211201159-6a26aaf9-87a9-4a9a-8163-a08fc8899cf6.png">

eg:
`https://github.com/adityatelange/hugo-PaperMod/Installation` should be changed to `https://github.com/adityatelange/hugo-PaperMod/wiki/Installation`

**Comment by adityatelange** [comment]
Thanks! Fixed https://github.com/adityatelange/hugo-PaperMod/wiki/Home/_compare/4258e4cc368f4a7c3ea82e7172a76301962ed6cf
