### ISSUE TITLE
[BUG] Black line on right side of the page

### ISSUE THREAD

**Issue by DiMalovanyy** [adityatelange/hugo-PaperMod#1141]
**Describe the bug**

Page not fit in 100% browser width, in other words, there is black line on right side of the page.
The problem is here [code](https://github.com/adityatelange/hugo-PaperMod/blob/d3d90be8a4ea04433d95d02a1dc07b0014c5b8b8/assets/css/includes/scroll-bar.css#L56), when I remove this block, everything is OK

 - Device/Os: MacBook Pro 14, M1, OSX Ventura 13.1
 - Type: Desktop
 - Browser and version : Safari 16.2 (18614.3.7.1.5)
 - Hugo Version: hugo v0.110.0+extended darwin/arm64 BuildDate=unknown
 - Theme Version: master

**Steps to reproduce the behavior:**

Sometimes required to resize window

**Expected behavior**:

No black/gray line or right side

**Repo/Source where this issue can be reproduced**:

master

**Screenshots**
![IMAGE 2023-01-22 21:08:33](https://user-images.githubusercontent.com/56088977/213937867-90ab4143-23e1-4c74-9334-c5baa5581776.jpg)
<img width="842" alt="Screenshot 2023-01-22 at 21 09 00" src="https://user-images.githubusercontent.com/56088977/213937883-8f3b0196-5e5d-4c42-afd7-22132a02d3e2.png">

First screenshot, with css block, second - without.

**Additional context**

**Comment by DiMalovanyy** [comment]
Who has saw same bug, you can create <your site>/assets/css/extended/scroll-patch.css and add there following code:
`
::-webkit-scrollbar {
    width: 0px;
    height: 11px;
}
`

**Comment by adityatelange** [comment]
Can set `Params.assets.disableScrollBarStyle` to true and get rid of custom scroll bar completely if you dont like it
