### ISSUE TITLE
failed to extract shortcode: template for shortcode "inTextImg" not found

### ISSUE THREAD

**Issue by couldbeuslgbt** [adityatelange/hugo-PaperMod#1154]
```
Error: Error building site: "/Users/dev/try-papermod/content/posts/papermod/papermod-installation.md:21:85": failed to extract shortcode: template for shortcode "inTextImg" not found
```

Can't build example site

**Comment by wingsterlai** [comment]
```
hugo v0.110.0+extended darwin/arm64 BuildDate=unknown
Error: Error building site: "/Users/wing/iCloud Drive (Archive)/Desktop/hugo-PaperMod-exampleSite/content/posts/papermod/papermod-installation.md:21:85": failed to extract shortcode: template for shortcode "inTextImg" not found
```
Can't build example site, either

**Comment by pseudokawaii** [comment]
Try using the shortcode like this:
```go
{{< inTextImg url="path/to/image.svg" >}}
```

**Comment by v01tt** [comment]
Getting the same error. 
 Tried this >               ({< inTextImg url="path/to/image.svg" >}}
Still doesn't work

**Comment by chrisrummel** [comment]
This issue is not related to hugo-PaperMod.
To be able to use a shortcode, you need to have the shortcode-file, in this case hugo/layouts/shortcodes/inTextImg.html
My guess is that this shortcode came with some other theme you used before, so you need to find it and copy it over.

**Comment by iafuad** [comment]
> This issue is not related to hugo-PaperMod. To be able to use a shortcode, you need to have the shortcode-file, in this case hugo/layouts/shortcodes/inTextImg.html My guess is that this shortcode came with some other theme you used before, so you need to find it and copy it over.

PaperMod does actually have the [InTextImg shortcode](https://github.com/adityatelange/hugo-PaperMod/blob/031e2ba57ea2b7b1de2e73c20bf2b5716f654fac/layouts/shortcodes/inTextImg.html), and it's working great for me. Maybe he should try updating the theme module?

**Comment by v01tt** [comment]
Yes, got it to work. 
Was using a variant of the PaperMod theme, that seemed to be missing the inTextImg.html from it's shortcode folder.
Pasted the file, and it worked.

**Comment by jamesbraza** [comment]
The current `exampleSite` branch (8/11/2023 at [7e5d17f](https://github.com/adityatelange/hugo-PaperMod/tree/7e5d17f08ac68ef7a365ba63d2f34a8c9f3a962a)) is missing `inTextImg.html` shortcode.

When you want to build the `exampleSite`:

```bash
git checkout exampleSite
git submodule update --init
wget -O themes/hugo-PaperMod/layouts/shortcodes/inTextImg.html https://raw.githubusercontent.com/adityatelange/hugo-PaperMod/v7.0/layouts/shortcodes/inTextImg.html
```
