### ISSUE TITLE
How to add custom highlighting

### ISSUE THREAD

**Issue by mzfr** [adityatelange/hugo-PaperMod#119]
Hey,

I read issue #35 but I am unable to use highlight.js to use monokai syntax highlighting.

Can you please give some detailed steps using which I can add custom highlight.

Thanks

**Comment by pacientes** [comment]
em..

first, add your `config.yml` file in `pygmentsUseClasses: true`
and then, modify(replace, but don't change filename) `theme/hugo-PaperMod/assets/css/an-old-hope.min.css` to [this link files](https://github.com/highlightjs/highlight.js/tree/master/src/styles)

highlight sample is [here](https://highlightjs.org/static/demo/)

**Comment by mzfr** [comment]
@pacientes So I have to change the theme's original file? Is there any way of adding highlights without changing the original file? I am asking cause for the build I am using submodule + github action so modifying it on my own repo would be difficult

**Comment by pacientes** [comment]
@mzfr I haven't found a way yet.
I'm sorry T-T

**Comment by adityatelange** [comment]
> and then, modify(replace, but don't change filename) 

Any .css file is bundled, filenames can be changed no issue !

Refer snippet below

https://github.com/adityatelange/hugo-PaperMod/blob/11c32302144c0f91734525bbe1f1d11ed1a16022/layouts/partials/head.html#L23-L31

**Comment by mzfr** [comment]
@adityatelange So I need to make a new css file in `/assets` directory of the theme? or my blogs root directory?

**Comment by adityatelange** [comment]
> @pacientes So I have to change the theme's original file? Is there any way of adding highlights without changing the original file? I am asking cause for the build I am using submodule + github action so modifying it on my own repo would be difficult

when you'll put `somestyle.css` as `an-old-hope.css` , theme's `an-old-hope.css` won't be bundled but the file placed in `assets/css/an-old-hope.css` will be @pacientes is correct
