### ISSUE TITLE
[Request] Search for tags

### ISSUE THREAD

**Issue by TheAnachronism** [adityatelange/hugo-PaperMod#1199]
Would it be possible to configure the fuse.js search functionality to allow to search for tags? Or rather, configure it, so one could search for posts with multiple tags like *#tag1 #tag2 #tag3*.

I'm not a JavaScript dev and couldn't figure out, how to build that myself.

**Comment by adityatelange** [comment]
@TheAnachronism you can do this for sure. No Js knowledge needed for this one.

https://github.com/adityatelange/hugo-PaperMod/blob/d6f911cc05c60e3cb7567b8f523ee8f9143cb43d/layouts/_default/index.json#L4

Modify the above file to include tags. something like https://github.com/adityatelange/hugo-index/blob/964ef03a7089613cf9220d24ace52688525433c5/layouts/index.json#L3

Use this https://github.com/adityatelange/hugo-PaperMod/wiki/Features#search-page and in keys add "tags"

`keys: ["title", "permalink", "summary", "content", "tags"]`
