### ISSUE TITLE
[BUG] New blog entry ignored by index.html and RSS feed

### ISSUE THREAD

**Issue by shiftingsand** [adityatelange/hugo-PaperMod#1203]
Hello.  I've been using PaperMod since 2021 and have made lots of blog entries but this is the first one I've made since Sept 2022.  I did all the steps I normally do. I'm having a problem with the visibility of my new post. It doesn't appear when you first visit my site and the RSS feed doesn't see it. The new post isn't a draft and only has a date in the past.

To test I tried the "LoveIt" theme and my new post appears. That makes me think it's a PaperMod issue.

WORKING
direct URL for the new post: https://chriswu.com/posts/appstore/yolo/
"posts" URL: https://chriswu.com/posts/
accessing the post via tags or categories.
accessing the site via localhost:1313

NOT working
Visiting the base URL: https://chriswu.com/
RSS feed doesn't show the newest post

macOS 13.3.1
hugo v0.111.3+extended darwin/amd64 
PaperMode (0.83 I think. I did a pull today.)

**Comment by shiftingsand** [comment]
I'm sorry, but I don't understand what you're requesting. Are you saying create a new bug report and fill in all the fields in the initial comments that are present?

**Comment by adityatelange** [comment]
> I'm sorry, but I don't understand what you're requesting. Are you saying create a new bug report and fill in all the fields in the initial comments that are present?

Yes
