### ISSUE TITLE
[Request] Pinterest Sharing and Social Icon support

### ISSUE THREAD

**Issue by hobbesjaap** [adityatelange/hugo-PaperMod#1204]
Hi there! I really, really love the work on PaperMod and have been using it on my own personal website for a while now.

I've started the process of converting my "big" Wordpress site into a Hugo site and I'm your theme again (of course!).

This site generates a lot of traffic through Pinterest links. So I'm looking how to easily keep the Pinterest sharing options alive. Would it be possible to add sharing options & a social icon for Pinterest?

**Comment by hobbesjaap** [comment]
I've done it myself by editing the svg.html file and adding these lines:

`{{- else if (eq $icon_name "pinterest") -}}
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="#000"><path d="M12 0a12 12 0 0 0-4.82 23c-.03-.85 0-1.85.21-2.76l1.55-6.54s-.39-.77-.39-1.9c0-1.78 1.03-3.1 2.32-3.1 1.09 0 1.62.81 1.62 1.8 0 1.09-.7 2.73-1.06 4.25-.3 1.27.63 2.31 1.89 2.31 2.27 0 3.8-2.92 3.8-6.38 0-2.63-1.77-4.6-4.99-4.6a5.68 5.68 0 0 0-5.9 5.75c0 1.05.3 1.78.78 2.35.23.27.26.37.18.67l-.25.97c-.08.3-.32.4-.6.3-1.67-.69-2.46-2.52-2.46-4.59 0-3.4 2.88-7.5 8.58-7.5 4.58 0 7.6 3.32 7.6 6.88 0 4.7-2.62 8.22-6.48 8.22-1.3 0-2.51-.7-2.93-1.5l-.84 3.3c-.26.93-.76 1.86-1.21 2.58A11.99 11.99 0 0 0 24 12 12 12 0 0 0 12 0z"/>
</svg>`

Not sure how to do a Pull Request, sorry, but if this could be folded into the next update, that would be awesome, thank you!

**Comment by adityatelange** [comment]
> Hi there! I really, really love the work on PaperMod and have been using it on my own personal website for a while now.
> 
> I've started the process of converting my "big" Wordpress site into a Hugo site and I'm your theme again (of course!).
> 
> This site generates a lot of traffic through Pinterest links. So I'm looking how to easily keep the Pinterest sharing options alive. Would it be possible to add sharing options & a social icon for Pinterest?

Hi thanks for your kind words. will try to add this
