### ISSUE TITLE
Build failure - no such template "_internal/google_news.html"

### ISSUE THREAD

**Issue by shveeram** [adityatelange/hugo-PaperMod#1206]
Wondering if any others recently encountered this?

While building via Render upon latest commit to my Github, I am getting the below error:

Error: Error building site: failed to render pages: render of "page" failed: "/opt/render/project/src/themes/PaperMod/layouts/_default/baseof.html:5:8": execute of template failed: template: _default/about.html:5:8: executing "_default/about.html" at <partial "head.html" .>: error calling partial: execute of template failed: html/template:partials/head.html:99:13: no such template "_internal/google_news.html"

**Comment by adityatelange** [comment]
https://discourse.gohugo.io/t/page-render-error/43594/2
