### ISSUE TITLE
[Feature] Configure highlightjs theme based on current theme

### ISSUE THREAD

**Issue by michael0liver** [adityatelange/hugo-PaperMod#121]
Hi, I think it would be nice if we could configure which highlight.js theme was used based on if we were using light or dark theme. I see I can overwrite *an-old-hope.min.css* but this will apply for both light and dark, would it be possible to implement this?

**Comment by adityatelange** [comment]
Thing is we have a dark background for both `light` and `dark` !

**Comment by michael0liver** [comment]
How would I customise this?

**Comment by adityatelange** [comment]
> How would I customise this?

Fork the theme ..
Checkout assets dir for related code and change it accordingly
