### ISSUE TITLE
cover.images - not sure if I am getting the desire effect

### ISSUE THREAD

**Issue by joelouthan** [adityatelange/hugo-PaperMod#1210]
Hello!

Source: https://raw.githubusercontent.com/joelouthan/theologic.us/main/content/posts/study-romans/study-romans01-1-7.md

```
cover:
  images: "images/banners/romans.png"
```

Image URL: https://theologic.us/images/banners/romans.png

<img width="678" alt="image" src="https://user-images.githubusercontent.com/8844984/236676874-d5bd1f31-967c-4bf6-9faa-fbd2b095d6c6.png">

Am I using cover.images correctly? Or how do I bring an image to opengraph/twitter posts?

**Comment by joelouthan** [comment]
Also on twitter: 
<img width="640" alt="image" src="https://user-images.githubusercontent.com/8844984/236677071-8b9751e2-e01c-480b-93ec-42761acc5a4a.png">

**Comment by adityatelange** [comment]
Hi @joelouthan 
It is `cover.image` please check here https://github.com/adityatelange/hugo-PaperMod/wiki/Variables#page-variables
