### ISSUE TITLE
Not found resources in 404 page

### ISSUE THREAD

**Issue by binick** [adityatelange/hugo-PaperMod#1223]
**Describe the bug**
When navigating to a non-existent resource hugo will try to render the [layout 404](https://gohugo.io/getting-started/configuration/#_404-server-error-page)

[Stylesheets](https://github.com/adityatelange/hugo-PaperMod/blob/bacb763071d9852bb719675e6c4452fc5650a193/layouts/partials/head.html#LL72C1-L74C105) are referenced with `$stylesheet.RelPermalink`.
This means that if the resource is at the path `/foo/bar/my-resource.html` then the stylesheet `stylesheet{fingerprint}.css` will also be looked up in `/foo/bar/assets/css/stylesheet{fingerprint}.css` while it is in `/assets/css/stylesheet{fingerprint}.css`.

 - Device/Os: [e.g. Android 10]
 - Type: [e.g. Desktop/Mobile]
 - Browser and version [e.g. Chrome 86.0]:
 - Hugo Version [ >=0.97.1 expected]:
 - Theme Version [e.g. v4.0, master, or commit-id ]:

**Steps to reproduce the behavior:**
1. Add permelinks config:
``` 
permalinks:
  posts: /:year/:month/:day/:slug/
```
2. Navigating to a non-existent resource

**Expected behavior**:
Resource files should always be loaded against the root

**Repo/Source where this issue can be reproduced**:
[binick.github.io](https://github.com/binick/binick.github.io)

**Comment by binick** [comment]
I think just replace `RelPermalink` with `Permalink` in the assets definition

**Comment by adityatelange** [comment]
Hi @binick have you set baseURL?

**Comment by binick** [comment]
Hi, yes. If you want, that is the [src/config/production/config.yml](https://github.com/binick/binick.github.io/blob/177a70c95d666a9d36199108ba7b552811fbad80/src/config/production/config.yml)

**Comment by adityatelange** [comment]
I don't know if it is related to https://github.com/gohugoio/hugo/issues/8109, but there was no response from hugo team on this one #126

**Comment by adityatelange** [comment]
![image](https://github.com/adityatelange/hugo-PaperMod/assets/21258296/176836df-bcf2-4b65-b39f-dcbb62130796)
css resource loads fine?

**Comment by adityatelange** [comment]
Not sure but seems like `/` in end is the issue. https://gohugo.io/getting-started/configuration/#baseurl

> (string) The absolute URL (protocol, host, path, and trailing slash) of your published site (e.g., https://www.example.org/docs/).


or try setting canonifyURLs to true https://gohugo.io/getting-started/configuration/#canonifyurls
