### ISSUE TITLE
[BUG] Fix deprecated code - build failed on latest Hugo (v0.112.0) 0 Language.Params deprecaiton warning

### ISSUE THREAD

**Issue by darrenkearney** [adityatelange/hugo-PaperMod#1224]
**Describe the bug**

When attempting to build on latest hugo, there is adeprecation warning for Language.Params for PaperMod layout files. This causes build to fail.
This is due to recent enhancements with Hugo handling language configs.
Related issue on hugo's issue tracker: https://github.com/gohugoio/hugo/issues/10947

 - Device/Os: WSL Ubuntu 22.04 running on WSL on Windows 10. - Likely all devices and operating systems.
 - Type: Desktop
 - Hugo Version >=0.112.0 expected.
 - Theme Version 

**Steps to reproduce the behavior:**
1. Get the latest version of hugo >=v0.112.0 at https://github.com/gohugoio/hugo/releases/tag/v0.112.0
2. run `hugo --panicOnWarning` command in your project root directory to attempt to build the project.
3. Note the build fail message.

**Expected behavior**:
1. Get the latest version of hugo >=v0.112.0 at https://github.com/gohugoio/hugo/releases/tag/v0.112.0
2. Run `hugo --panicOnWarning` to attempt to build the project.
3. Project builds successfully.

**Repo/Source where this issue can be reproduced**:

https://github.com/adityatelange/hugo-PaperMod/releases/tag/v7.0
https://github.com/adityatelange/hugo-PaperMod/tree/master (as of 2023/05/23

**Error message**
> ~/path/to/project$ hugo --panicOnWarning
> Start building sites …
> hugo v0.112.0-0a95d6704a8ac8d41cc5ca8fffaad8c5c7a3754a+extended linux/amd64 BuildDate=2023-05-23T08:14:20Z VendorInfo=gohugoio
> WARN 2023/05/23 11:55:27 .Language.Params is deprecated and will be removed in a future release. .Language.Params is deprecated and will be removed in a future release. Use site.Params instead.
> 
> - For all but custom parameters, you need to use the built in Hugo variables, e.g. site.Title, site.LanguageCode; site.Language.Params.Title will not work.
> - All custom parameters needs to be placed below params, e.g. [languages.en.params] in TOML.
> 
> See https://gohugo.io/content-management/multilingual/#changes-in-hugo-01120
> 
> Total in 3873 ms
> Error: error building site: render: failed to render pages: render of "page" failed: "/path/to/project/themes/PaperMod/layouts/_default/single.html:39:26": execute of template failed: template: _default/single.html:39:26: executing "main" at <.Language.Params.Taxonomies.tag>: error calling Params: Warning trapped. Remove the --panicOnWarning flag to continue.

**Comment by darrenkearney** [comment]
Pull Request here: https://github.com/adityatelange/hugo-PaperMod/pull/1225

**Comment by adityatelange** [comment]
> Looks like bep had second thoughts on this: https://github.com/gohugoio/hugo/issues/11025
> 
> No longer a warning after 0.112.4

_Originally posted by @SirUli in https://github.com/adityatelange/hugo-PaperMod/issues/1225#issuecomment-1566141008_
