### ISSUE TITLE
[BUG] Indentation of YAML multiline strings is inconsistent

### ISSUE THREAD

**Issue by concretevitamin** [adityatelange/hugo-PaperMod#1227]
**Describe the bug**

In https://blog.skypilot.co/analyzing-the-whole-mouse-brain-atlas-on-the-cloud-with-skypilot/#create-a-vm-with-a-very-basic-yaml-file I have a `yaml` codeblock:
```yaml
...
setup: |
  pip install --upgrade pip
  conda env update -f /home/analysis/env.yaml  

run: |
  nohup jupyter-lab --no-browser --port 8888 &
```
As you can see, 
- The `setup` multiline string has 2 lines, and are indented 2 spaces;
- The `run` multiline string has 1 line, and is indented 4 spaces.

In the markdown source, both multiline strings are indented 2 spaces.

Anyway to fix this?

 - Device/Os: [e.g. Android 10]
 - Type: [e.g. Desktop/Mobile]
 - Browser and version [e.g. Chrome 86.0]:
 - Hugo Version [ >=0.97.1 expected]: `hugo v0.84.4+extended darwin/amd64 BuildDate=unknown`
 - Theme Version [e.g. v4.0, master, or commit-id ]: `e6b697f - (grafted) Add support for Greek, Modern el.yaml (#1160) (3 months ago) <Michail Angelos Tsiantakis>`

**Steps to reproduce the behavior:**

**Expected behavior**:

**Repo/Source where this issue can be reproduced**:

**Screenshots**

**Additional context**

**Comment by adityatelange** [comment]
Hi @concretevitamin, code blocks are not generated by PaperMod but hugo does it for you, please raise this over github or discourse

**Comment by jmooring** [comment]
Please take a moment to test these issues before pushing users upstream.
