### ISSUE TITLE
FYI: SocialIcons will not be displayed unless `homeInfoParams` is defined

### ISSUE THREAD

**Issue by Skarlso** [adityatelange/hugo-PaperMod#1239]
So this caught me off-guard and should be documented unless I missed it. But `socalIcons` will not be displayed if you don't define `homeInfoParams`. If that is documented somewhere, my apologies. If not, maybe it would be nice to mention it somewhere, please? :)

**Comment by adityatelange** [comment]
https://github.com/adityatelange/hugo-PaperMod/wiki

**Comment by Skarlso** [comment]
Where? Which section does describe this dependency?

**Comment by Skarlso** [comment]
@adityatelange At least have the curtesy of pointing to the right section.

**Comment by adityatelange** [comment]
> @adityatelange At least have the courtesy of pointing to the correct section.

@Skarlso where you want it to be displayed? In which mode you're trying to display socialIcons?
