### ISSUE TITLE
Image captions are added to the table of contents

### ISSUE THREAD

**Issue by kdkasad** [adityatelange/hugo-PaperMod#124]
If an image is added using the figure shortcode like so, the caption gets added to the page's Table of Contents:
```html
{{< figure src="/img/photo1.jpg" title="This is the caption" >}}
```

The resulting entry in the page's table of contents looks like this:
```html
<a href="#" aria-label="This is the caption">This is the caption</a>
```

I'm pretty sure this happens because the caption is put in an `h4` element:
```html
<figure>
    <img src="/very-secret-english-website/homemade-skis-broken.webp"/>
    <figcaption>
        <h4>and after</h4>
    </figcaption>
</figure>
```

**Comment by adityatelange** [comment]
@kdkasad is this even a case with Hugo's inbuilt toc generator ?

**Comment by kdkasad** [comment]
> @kdkasad is this even a case with Hugo's inbuilt toc generator ?

It does not happen with Hugo's default ToC generator. In fact, using `{{- .TableOfContents }}` in place of the `{{- partial "toc.html" . }}` line produces a ToC with identical structure but with correct information. It could probably be used instead, and the `toc.html` partial could be removed entirely.

**Comment by adityatelange** [comment]
@kdkasad I see. But there are conditions where this code just produces better results than default one ! You can tryout different combos with headings 

> It could probably be used instead, and the toc.html partial could be removed entirely.

So I am not in favor of removing that entirely

**Comment by adityatelange** [comment]
@AllanChain Can you help us

**Comment by kdkasad** [comment]
> But there are conditions where this code just produces better results than default one ! You can tryout different combos with headings

Can you give an example? I want to do some testing to compare the two.

**Comment by adityatelange** [comment]
> > But there are conditions where this code just produces better results than default one!
> 
> Can you give an example? I want to do some testing to compare the two.

@kdkasad https://github.com/adityatelange/hugo-PaperMod/blob/exampleSite/content/posts/markdown-syntax.md

**Comment by kdkasad** [comment]
> > > But there are conditions where this code just produces better results than default one!
> > 
> > 
> > Can you give an example? I want to do some testing to compare the two.
> 
> @kdkasad https://github.com/adityatelange/hugo-PaperMod/blob/exampleSite/content/posts/markdown-syntax.md

The only difference I notice is that headings where certain levels are skipped (e.g. `h4` inside `h2`) will have 2 bullets in front. Otherwise, the results are exactly the same:

`toc.html` partial:
![screenshot of toc with current partial template](https://user-images.githubusercontent.com/63574107/101866136-e61a1180-3b2c-11eb-8235-16f2973f3cc9.png)

`.TableOfContents`:
![screenshot of toc with default generator](https://user-images.githubusercontent.com/63574107/101866239-28dbe980-3b2d-11eb-9aa0-02bed099360c.png)

**Comment by adityatelange** [comment]
> > > > But there are conditions where this code just produces better results than default one!
> > > 
> > > 
> > > Can you give an example? I want to do some testing to compare the two.
> > 
> > 
> > @kdkasad https://github.com/adityatelange/hugo-PaperMod/blob/exampleSite/content/posts/markdown-syntax.md
> 
> The only difference I notice is that headings where certain levels are skipped (e.g. `h4` inside `h2`) will have 2 bullets in front. Otherwise, the results are exactly the same:

Exactly !

**Comment by AllanChain** [comment]
> @AllanChain Can you help us

But I am not using hugo any more 🤷 Seems that hugo has its own way getting headers directly from markdown, instead of finding all h tags. So figure caption is not included using `{{- .TableOfContents }}`

**Comment by adityatelange** [comment]
> > @AllanChain Can you help us
> 
> But I am not using hugo any more  Seems that hugo has its own way getting headers directly from markdown, instead of finding all h tags. So figure caption is not included using `{{- .TableOfContents }}`

Gotcha ! Never mind, thanks for replying !

**Comment by adityatelange** [comment]
Simplest solution to this would be having own copy of hugo's shortcode with `h4` tag removed 
https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/shortcodes/figure.html

**Comment by kdkasad** [comment]
I can think of another solution, which is to hide the bullet point on `li` elements which have a `ul` as their *only* child. This would be tricky with current CSS selectors, and would probably require JavaScript. However, with the `:has()` pseudo-class proposed in CSS4, it would be easy to do using the following selector:
```css
li:has(> ul:only-child) {
    /* hide bulletpoint somehow */
}
```
