### ISSUE TITLE
Failed to create config from result: failed to decode config for language "fr": unknown config key "profilemode"

### ISSUE THREAD

**Issue by yimmy23** [adityatelange/hugo-PaperMod#1249]
I tried to build a website using the config.yml from the PaperMod Demo site. After running the "Hugo serve" command, it showed an error message "failed to create config from result: failed to decode config for language "fr": unknown config key "profilemode"." 
Please give me some instruction to solve it.

**Comment by Achilles-10** [comment]
I met the same Error

**Comment by ShaohanTian** [comment]
Have you solved it?

**Comment by ShaohanTian** [comment]
I solve it by some below changes on config.yml:

1. One change:
```yml
defaultContentLanguageInSubdir: false
```

2. Moving **profileMode** code to **params**:
![image](https://github.com/adityatelange/hugo-PaperMod/assets/58108746/d48fc5fb-3c12-43af-9561-d1040e81917d)

![image](https://github.com/adityatelange/hugo-PaperMod/assets/58108746/17430737-d0ea-4898-bddd-d6a5c824aefa)

**Comment by adityatelange** [comment]
> I tried to build a website using the config.yml from the PaperMod Demo site. After running the "Hugo serve" command, it showed an error message "failed to create config from result: failed to decode config for language "fr": unknown config key "profilemode"." Please give me some instruction to solve it.

https://github.com/adityatelange/hugo-PaperMod/blob/84110306fee8e35b737d9a46e2c845ec23a5f187/config.yml#L69
