### ISSUE TITLE
[DOC] Document the feature `hiddenInHomelist`

### ISSUE THREAD

**Issue by RoneoOrg** [adityatelange/hugo-PaperMod#1255]
The feature `hiddenInHomelist` is [requested](https://github.com/adityatelange/hugo-PaperMod/issues/1110) and [already fixed](https://github.com/adityatelange/hugo-PaperMod/commit/b906338dc82a48e0fa8c8d4160a09c8b07302472).

It's missing a line in the documentation

**Comment by adityatelange** [comment]
Sure, I'll add

**Comment by RoneoOrg** [comment]
Thanks!
