### ISSUE TITLE
Remove sub folders from URL for posts

### ISSUE THREAD

**Issue by bee-san** [adityatelange/hugo-PaperMod#128]
Hey,

I want this:

```
URL/blog
```

But we have this:

```
URL/posts/blog
```

Where `blog` is the post.

The easiest way is to move all posts from `posts` into `content`, but this prevents it from appearing in the list of blog posts on the homepage.

Is there something I can do to make them appear?

**Comment by sunuazizrahayu** [comment]
> 
> 
> Hey,
> 
> I want this:
> 
> ```
> URL/blog
> ```
> 
> But we have this:
> 
> ```
> URL/posts/blog
> ```
> 
> Where `blog` is the post.
> 
> The easiest way is to move all posts from `posts` into `content`, but this prevents it from appearing in the list of blog posts on the homepage.
> 
> Is there something I can do to make them appear?

@bee-san use custom permalink on your `config.yml`
```
permalinks:
  posts: /blog/:slug
```

**Comment by kdkasad** [comment]
Check the Hugo wiki for more information: https://gohugo.io/content-management/urls/

**Comment by bee-san** [comment]
Thanks a lot!
