### ISSUE TITLE
Links rely on color to be distinguishable - Pagespeed Insights

### ISSUE THREAD

**Issue by wagneradrian** [adityatelange/hugo-PaperMod#1291]
I tested my website with Pagespeed Insights and I get the following warning in accessibility:
> Links rely on color to be distinguishable.
> Low-contrast text is difficult or impossible for many users to read. Link text that is discernible improves the experience for users with low vision.

Same problem with the Demo of PaperMod:
[https://pagespeed.web.dev/analysis/https-adityatelange-github-io-hugo-PaperMod-posts-papermod-papermod-installation/6bez215sp9](https://pagespeed.web.dev/analysis/https-adityatelange-github-io-hugo-PaperMod-posts-papermod-papermod-installation/6bez215sp9)

**Comment by adityatelange** [comment]
It is a drawback of a monochrome theme and a disadvantage which comes because of a choice. Can't fix it with colors
