### ISSUE TITLE
Fatal error when I execute workflow to deploy github page

### ISSUE THREAD

**Issue by loulou64490** [adityatelange/hugo-PaperMod#1297]
I don't understand the error
![Capture d’écran du 2023-08-31 16-10-47](https://github.com/adityatelange/hugo-PaperMod/assets/102870297/b5ebd3ec-8961-4880-829c-eccf79fe1f49)

**Comment by anantnrg** [comment]
Create a file in the root directory called `.gitmodules` and add this:
```
[submodule "themes/PaperMod"]
path = "themes/PaperMod"
url = https://github.com/adityatelange/hugo-PaperMod
```

**Comment by loulou64490** [comment]
Thanks, it's work perfectly!
