### ISSUE TITLE
[BUG] Hugo converting archive into article when refreshing.

### ISSUE THREAD

**Issue by shravanSD** [adityatelange/hugo-PaperMod#1298]
**Describe the bug**
Sometimes the 'archive' appears like 'archive' but sometimes it appears as 'article' as seen on the browsers' inspector.

 - Device/Os: [e.g. Android 10]
 - Type: [e.g. Desktop/Mobile]
 - Browser and version [e.g. Chrome 86.0]:
 - Hugo Version [ >=0.97.1 expected]:
 - Theme Version [e.g. v4.0, master, or commit-id ]:

- Device/OS: Macbook
- Laptop
- Firefox 116.0.3
- Hugo 0.117
- Theme version https://github.com/adityatelange/hugo-PaperMod/commit/efe4cb45161be836d602d5cd0f857e62661dae8b

**Steps to reproduce the behavior:**

I do not really know the steps to reproduce the error. When I do any changes and the browser reloads, the archive layout changes to article on the browser.

> Incorrect display
<img width="1356" alt="image" src="https://github.com/adityatelange/hugo-PaperMod/assets/25692098/138d3f0c-d44a-4089-ba04-8ddbf5cd7d2e">

> Correct display
<img width="1308" alt="image" src="https://github.com/adityatelange/hugo-PaperMod/assets/25692098/3b4869af-8925-4374-92a7-894d687c7b13">

I do not know what is causing that, no major changes are being done.

The site can be accessed at sxravan.com

regards,

Shravan

**Comment by adityatelange** [comment]
cant' reproduce
