### ISSUE TITLE
Specifying canonical URL results in multiple canonical URLs

### ISSUE THREAD

**Issue by cbrownstein** [adityatelange/hugo-PaperMod#130]
_Originally posted by @adityatelange in https://github.com/adityatelange/hugo-PaperMod/issues/104#issuecomment-738547278_:
> @Horsty80 It's fine to have multiple canonical urls. Canonical urls just let search engines know that their contents are same. You may read about those on the web, for more info :)

I believe this is incorrect and can cause problems.

See, e.g.:

https://yoast.com/rel-canonical/#common-issues
> Multiple rel=canonical links on a page cause havoc. When we encounter this in WordPress plugins, we try to reach out to the developer doing it and teach them not to, but it still happens. And when it does, the results are wholly unpredictable.

https://help.dragonmetrics.com/en/articles/214017-multiple-rel-canonical-tags
> If there is more than one rel=canonical tag on the page, search engines will get confused and not know which tag contains the actual canonical page. If there is more than one on the page, Google will simply ignore all of the rel=canonical tags, while other search engines may behave erratically or unpredictably when trying to identify the canonical page.

**Comment by Horsty80** [comment]
@cbrownstein i'm totaly agree with you, and i custom the theme to have just 1 canonical URL
Thanks for the ressources ;)

**Comment by kdkasad** [comment]
I don't think this is an actual issue. The theme doesn't create multiple canonical URLs. The problem was only caused by adding more custom content to the `head` element.

**Comment by Horsty80** [comment]
My workaround is to overload the `head` element

**Comment by cbrownstein** [comment]
> I don't think this is an actual issue. The theme doesn't create multiple canonical URLs. The problem was only caused by adding more custom content to the `head` element.

The theme _can_ create multiple canonical URLs.

The relevant lines are:

https://github.com/adityatelange/hugo-PaperMod/blob/09aba49bf0922110bd61b23a802b2099ce7b5a36/layouts/partials/head.html#L19-L23

Line 19 will output the canonical URL of the post _always_.

Lines 20-23 will output one (or more) user-defined canonical URLs if `.Site.Params.canonical` has values or `.Params.canonical` has values.

**Comment by kdkasad** [comment]
> > I don't think this is an actual issue. The theme doesn't create multiple canonical URLs. The problem was only caused by adding more custom content to the `head` element.
> 
> The theme _can_ create multiple canonical URLs.
> 
> The relevant lines are:
> 
> https://github.com/adityatelange/hugo-PaperMod/blob/09aba49bf0922110bd61b23a802b2099ce7b5a36/layouts/partials/head.html#L19-L23
> 
> Line 19 will output the canonical URL of the post _always_.
> 
> Lines 20-23 will output one (or more) user-defined canonical URLs if `.Site.Params.canonical` has values or `.Params.canonical` has values.

I missed that, sorry. In that case, yes, this is an issue.

**Comment by adityatelange** [comment]
@cbrownstein @Horsty80 

I am li'l busy so I might now review PRs.

I am not really sure about multiple canonical URls being a problem, 
https://developers.google.com/search/docs/advanced/crawling/consolidate-duplicate-urls#define-canonical
![image](https://user-images.githubusercontent.com/21258296/102177297-43b1b380-3ec9-11eb-84ec-e09e8132c3e8.png)

Also its upto the owner of the website to add a single canonical url or multiple, it not necessary to do so !

**Comment by kdkasad** [comment]
According to [Yandex's website](https://yandex.com/support/webmaster/robot-workings/canonical.html#canonical__not-use), specifying multiple canonical URLs is an error:
![image](https://user-images.githubusercontent.com/63574107/102181904-344a5000-3e60-11eb-8913-82fed0561f46.png)

Plus, the point of the canonical URL is to point to the one canonical location of the page, so there shouldn't be multiple.

**Comment by cbrownstein** [comment]
> I am not really sure about multiple canonical URls being a problem,
> https://developers.google.com/search/docs/advanced/crawling/consolidate-duplicate-urls#define-canonical
> 
> […]
> 
> Also its upto the owner of the website to add a single canonical url or multiple, it not necessary to do so !

I'm not understanding how this suggests that having multiple canonical URLs is fine. I read this as meaning it's acceptable to have multiple pages pointing to a single a canonical page, which makes sense logically: the one page is the true version while the other pages are duplicates.

**Comment by adityatelange** [comment]
> > I am not really sure about multiple canonical URls being a problem,
> > https://developers.google.com/search/docs/advanced/crawling/consolidate-duplicate-urls#define-canonical
> > […]
> > Also its upto the owner of the website to add a single canonical url or multiple, it not necessary to do so !
> 
> I'm not understanding how this suggests that having multiple canonical URLs is fine. I read this as meaning it's acceptable to have multiple pages pointing to a single a canonical page, which makes sense logically: the one page is the true version while the other pages are duplicates.

@cbrownstein After reading about this and asking peers, I am in favor of this change :+1:
