### ISSUE TITLE
[BUG] Wrong background color of code blocks

### ISSUE THREAD

**Issue by qbao96xb** [adityatelange/hugo-PaperMod#1302]
**Wrong background color of code blocks**

 - Device/Os: MacOS Ventura
 - Type: All Platform affected
 - Browser and version: Firefox 117.0 * Chrome 116.0.5845.96
 - Hugo Version [ >=0.97.1 expected]: v0.118.2
 - Theme Version [e.g. v4.0, master, or commit-id ]: v7.0

**Steps to reproduce the behavior:**
1. Installing the theme using as instructed in README.md
2. Writing blog in `.Rmd` format, translated into `.md` using `blogdown::serve_site()`
3. Implementing the Build Website function in RStudio, which definitely runs `rmarkdown::render_site(encoding = 'UTF-8')`
4. The output site shows a rgb(29, 30, 32) color for the background of the code block. My further inspection shows that the `.html` file of the posts show a default color of black as follows:
```
@media (prefers-color-scheme: dark) {
            :root {
                --theme: rgb(29, 30, 32);
                --entry: rgb(46, 46, 51);
                --primary: rgb(218, 218, 219);
                --secondary: rgb(155, 156, 157);
                --tertiary: rgb(65, 66, 68);
                --content: rgb(196, 196, 197);
                --hljs-bg: rgb(46, 46, 51);
                --code-bg: rgb(55, 56, 62);
                --border: rgb(51, 51, 51);
            }
```

**Expected behavior**:
The code blocks' backgrounds should be aligned with the chosen theme via the light/dark button. It should be light or dark depending on the current selected mode.

**Repo/Source where this issue can be reproduced**:
https://github.com/qbao96xb/blog_waldeinsamkeit1340

**Screenshots**
<img width="754" alt="Screenshot 2023-09-08 at 10 43 49 PM" src="https://github.com/adityatelange/hugo-PaperMod/assets/43134324/5bb12385-2a9b-408e-8dca-893c5d4578e2">
Or
You can find the issue in my blog here: https://theinsightseekers.netlify.app/2023/07/14/user-segmentation-using-k-means-in-r/

**Additional context**
- blogdown version: 1.18
- RStudio version: RStudio 2023.06.2+561 
- R version: 4.3.1 (2023-06-16) -- "Beagle Scouts"

**Comment by qbao96xb** [comment]
P/S: First I tried to customize the highlighter as per the instructions in the FAQ post, however, it did not work. So I fell back to the default version of blogdown:

```
params:
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - python
    - sql
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
```

**Comment by buraksekili** [comment]
@qbao96xb have you resolved the issue? I also faced this

**Comment by adityatelange** [comment]
Hi @qbao96xb I see you're using highlight.js as well as chromastyles. You need to drop one of them.
Set `Params.assets.disableHLJS` to true and

**Comment by adityatelange** [comment]
this should be fixed with latest patches where we have removed hljs and moved to chromastyles. kindly update and let me know.
