### ISSUE TITLE
superscript and subscript support

### ISSUE THREAD

**Issue by shellheim** [adityatelange/hugo-PaperMod#1304]
Is there support for subscript and superscript in PaperMod? 
I couldn't find anything official regarding this in the hugo docs. The only way seems to be to use the `<sub>` and `<sup>` html tags and somehow allow them to remain in the document.

**Comment by shellheim** [comment]
Currently, this issue can be solved using the rawhtml shortcode. From it's [first commit](https://github.com/adityatelange/hugo-PaperMod/commit/bfcf89ccca27e26a0858e725b858d6c5f71960d5) :

```html
 {{< rawhtml >}} 
  
  <p class="someclass">
    This is <strong>raw HTML</strong>, inside Markdown.
  </p>
  
 {{< /rawhtml >}}
 
```
Will result in the <p> tag with class name "someclass" to be rendered in the final webpage. So one could use it with the `<sub>` and `<sup>` tags for subscript and superscript respectively.

**Comment by adityatelange** [comment]
> Currently, this issue can be solved using the rawhtml shortcode. From it's [first commit](https://github.com/adityatelange/hugo-PaperMod/commit/bfcf89ccca27e26a0858e725b858d6c5f71960d5) :
> 
> ```
>  {{< rawhtml >}} 
>   
>   <p class="someclass">
>     This is <strong>raw HTML</strong>, inside Markdown.
>   </p>
>   
>  {{< /rawhtml >}}
>  
> ```
> 
> Will result in the `<p>` tag with class name "someclass" to be rendered in the final webpage. So one could use it with the `<sub>` and `<sup>` tags for subscript and superscript respectively.

Or you can use `unsafe: true `
https://github.com/adityatelange/hugo-PaperMod/blob/0dfff4e1ce3a7bd72c6a7197ad64de939d68937a/config.yml#L194-L197
