### ISSUE TITLE
[BUG] extend_{head,footer}.html doesnt work

### ISSUE THREAD

**Issue by fguisso** [adityatelange/hugo-PaperMod#1319]
**Describe the bug**
 - Device/Os: MacOS M1/Github Actions runner
 - Hugo Version : hugo v0.119.0-b84644c008e0dc2c4b67bd69cccf87a41a03937e+extended darwin/arm64 BuildDate=2023-09-24T15:20:17Z VendorInfo=brew
 - Theme Version [e.g. v4.0, master, or commit-id ]: v7.0

**Steps to reproduce the behavior:**

**Expected behavior**:

Same in `hugo server`, the partials need to be rendered in build static `hugo --minify`

**Additional context**

I'm looking to understand this problem and found some peculiar things, but I don't understand how it works.

1. Going to `themes/PaperMod/layouts/_default/baseof.html`
2. change `partialsCached` to `partials` in line 20
3. Now the `extend_footer.html` works on `server` or `build static`.

**Comment by adityatelange** [comment]
It works fine

**Comment by adityatelange** [comment]
> Do you have testing something? Can you please explain anything before closing this?

Can you share a sample repository where this can be reproduced?
