### ISSUE TITLE
Compatibility issue with `delimit` function in Hugo 0.120.0

### ISSUE THREAD

**Issue by loganmarchione** [adityatelange/hugo-PaperMod#1325]
I’m not a front-end developer, but I use Hugo and PaperMod for my personal site.

I noticed when going from Hugo 0.119.0 to 0.120.0, I’m seeing raw [HTML character entities](https://www.w3schools.com/html/html_entities.asp) in my final site that are being incorrectly rendered by the browser.

The top is Hugo 0.120.0 and the bottom is 0.119.0 (nothing else changed).
![combined](https://github.com/adityatelange/hugo-PaperMod/assets/4955337/1201c48f-0b11-4a5f-8e2c-63de19b1264f)

I asked on [Hugo's Discourse](https://discourse.gohugo.io/t/hugo-0-120-0-incorrectly-rendering-html-character-entities/46893) and they said it was a recent change in the `delimit` function in Hugo [0.120.0](https://github.com/gohugoio/hugo/releases/tag/v0.120.0) and that it would require a theme update.

FWIW, I've tried the latest PaperMod hash as-of this writing and it still shows the same thing.

**Comment by adityatelange** [comment]
Hi @loganmarchione, thanks for heads up, this has been fixed. Please pull master branch.
There are more deprecations with 120, but those are not breaking changes. I will look into them over weekend.

**Comment by loganmarchione** [comment]
@adityatelange, it's working, thanks!
