### ISSUE TITLE
[BUG] Long search queries hang or lag website

### ISSUE THREAD

**Issue by ragibson** [adityatelange/hugo-PaperMod#1329]
**Describe the bug**

 - Device/Os: [e.g. Android 10] Windows 10, Linux Mint, Android
 - Type: [e.g. Desktop/Mobile] Desktop, Mobile
 - Browser and version [e.g. Chrome 86.0]: Firefox 119.0, Chrome 119.0.6045.105
 - Hugo Version [ >=0.97.1 expected]: Latest
 - Theme Version [e.g. v4.0, master, or commit-id ]: Latest

**Steps to reproduce the behavior:**

Go to any website using the theme, e.g., https://adityatelange.github.io/hugo-PaperMod/ and type increasingly long queries into the search field.

As the search query gets longer, the website starts to lag and/or hang (much earlier than any reasonable index search should). Many other Hugo themes with similar search functionality do not seem to have this issue.

**Expected behavior**:

The search functionality should be efficient and not cause lag, as in many other Hugo themes, or be asynchronous when this is not feasible.

**Repo/Source where this issue can be reproduced**:

Any PaperMod website should work, including https://adityatelange.github.io/hugo-PaperMod/.

**Screenshots**

N/A

**Additional context**

N/A

**Comment by adityatelange** [comment]
Yes, this does lag with longer search text as it goes through full text in cases when it is enabled.
We can fix it with setting a max limit to input length. Async search and setting up a lock in Js while search or running the search in background without letting the page freeze is a time taking solution to solve. We'll see how this goes.

**Comment by adityatelange** [comment]
64 chars would be good enough imo as we are doing a fast search and not highlighting the text after we found the results.

**Comment by soul-ride** [comment]
Maybe my experience will be useful for someone:

I had the same issue with embedded Fuse.js search on quite large dataset (>50k records), even with relatively short queries (less than 15 characters). I was not able to fix this with any options available in fuse.js library.

Ended up switching from Fuse.js to [MiniSearch](https://github.com/lucaong/minisearch) which is superfast even with larger datasets (tested on more than 100k records), and even with fuzzy search option enabled.

Switch to MiniSearch is very easy, you just need to override few files in theme and download index.min.js from their repo.
I've composed all the files that needed to be updated at this repo - [https://github.com/soul-ride/PaperMod-MiniSearch](PaperMod-MiniSearch) .

@adityatelange maybe you can consider the switch from Fuse.js to MiniSearch (or other alternative) as default engine in PaperMod theme? Looking on the different tests, it seems like in most cases Fuse.js uses more memory and is slower than other libraries out there.

**Comment by adityatelange** [comment]
> Maybe my experience will be useful for someone:
> 
> I had the same issue with embedded Fuse.js search on quite large dataset (>50k records), even with relatively short queries (less than 15 characters). I was not able to fix this with any options available in fuse.js library.
> 
> Ended up switching from Fuse.js to [MiniSearch](https://github.com/lucaong/minisearch) which is superfast even with larger datasets (tested on more than 100k records), and even with fuzzy search option enabled.
> 
> Switch to MiniSearch is very easy, you just need to override few files in theme and download index.min.js from their repo. I've composed all the files that needed to be updated at this repo - [PaperMod-MiniSearch](https://github.com/soul-ride/PaperMod-MiniSearch) .
> 
> @adityatelange maybe you can consider the switch from Fuse.js to MiniSearch (or other alternative) as default engine in PaperMod theme? Looking on the different tests, it seems like in most cases Fuse.js uses more memory and is slower than other libraries out there.

@soul-ride I tried their demo website on my Mobile phone and I face freezing issue (1 sec pauses with each character) here too. Query I entered was "and".
https://lucaong.github.io/minisearch/demo/

**Comment by adityatelange** [comment]
What I see here is fuzzy search in Js is CPU intensive task. If you use chromium based browser you can measure performance and Ram usage while u perform the search operation.

**Comment by adityatelange** [comment]
> I had the same issue with embedded Fuse.js search on quite large dataset (>50k records), even with relatively short queries (less than 15 characters). I was not able to fix this with any options available in fuse.js library.

If you want to improve performance consider setting options excluding full text search from contents of a page.
