### ISSUE TITLE
[BUG] Issues Displaying / Hiding Covers

### ISSUE THREAD

**Issue by woadey** [adityatelange/hugo-PaperMod#1331]
**Describe the bug**

Throwing an error when the config.yml cover has hidden: true, but a markdown page has the cover hidden: false. 

 - Device/Os: WSL
 - Type: Desktop
 - Browser and version: Chrome 119.0
 - Hugo Version: v0.92.2+extended
 - Theme Version: v7.0 (aec66c2d1dc5fd27cf6e70127327d006d2411106)

**Steps to reproduce the behavior:**

1. Go to config.yml
2. Add params: cover: hidden: true
3. Create a new "index.md" (or any other new markdown page)
4. Go to "index.md"
5. In the header, add an image (cover: image: "path/to/image")
6. In the header, specify cover: hidden: false

**Expected behavior**:

By specifying cover: hidden: false on index.md, I would expect the cover image to be visible (rather than throwing an error). 

**Repo/Source where this issue can be reproduced**:

https://github.com/adityatelange/hugo-PaperMod/tree/master

**Screenshots**

![image](https://github.com/adityatelange/hugo-PaperMod/assets/46456168/5caa5069-903a-4fda-b5c0-34b45f8691b8)

**Comment by adityatelange** [comment]
Upgrade to the minimum supported version of hugo for Papermod
