### ISSUE TITLE
Publish Time, Read Time, Author, and Word Count not rendering correctly. [BUG]

### ISSUE THREAD

**Issue by Normanras** [adityatelange/hugo-PaperMod#1334]
NOTE: I looked through the other issues and didn't see this elsewhere. I can also confirm that in my previous post to my hugo site a few weeks ago, this was not occurring.

**Describe the bug**
After updating PaperMod today, I noticed that in both running a local server and my production server the `span` that contains the publish time, time to read, author, and word count is not formatted correctly and now shows:

```
<span title='2023-11-15 08:08:49 -0500 EST'>November 15, 2023</span>&nbsp;·&nbsp;6 min&nbsp;·&nbsp;1221 words&nbsp;·&nbsp;Me
```

When I inspect the element, it looks like the `<span` is being put inside double quotes, causing the HTML to not be rendered. I've included a screenshot below.

I originally noticed this when testing a new post that I published today, but looking back through my previous posts, it is occurring there as well. That's why I thought it might be a bug, since I hadn't changed anything in my `hugo.toml` nor have I edited those past posts.

**Steps to reproduce the behavior:**
I wish I had a clear understanding of how this happened. The only thing I changed in my workflow is I went to my themes directory and ran `hugo mod get -u` and there were no errors in running that command.

**Expected behavior**:
The HTML to be rendered and the elements within that span to show correctly.

**Repo/Source where this issue can be reproduced**:
My repo is private, but you can see the bug [here](https://selfhosted.rsmsn.co). 

**Screenshots**
![Screenshot 2023-11-16 at 9 38 22 AM](https://github.com/adityatelange/hugo-PaperMod/assets/44226464/bcc6740c-384f-4c71-9e11-6036bf0dc875)

**Additional context**
None.

**Comment by adityatelange** [comment]
#1325

**Comment by Normanras** [comment]
Missed it! Thank you.
