### ISSUE TITLE
Update the Create site command with Hugo in the Wiki

### ISSUE THREAD

**Issue by s0l1dx10** [adityatelange/hugo-PaperMod#1336]
The old command not working now:

`hugo new site <name of site> -f yml`

and that is the replacement one for it:

`hugo new site <name of site> --format "yaml"`

Note: the Extention "yaml" and "yml" are the same but according to the offiacl Q&A for Yaml they recommended using "yaml" 
[https://yaml.org/faq.html](url)

**Comment by adityatelange** [comment]
done https://github.com/adityatelange/hugo-PaperMod/wiki/Installation/_history
