### ISSUE TITLE
[BUG] - correction to the installation steps 

### ISSUE THREAD

**Issue by gooseyman** [adityatelange/hugo-PaperMod#1339]
I had an issue following the install instructions as listed. I believe it was the `-f yml` part of the new site build command `hugo new site <name> -f yml`

When I updated the format part to align with the hugo docs https://gohugo.io/commands/hugo_new_site/ it worked fine. 

Suggesting the edit be made to the installation wiki to change to `--format "yaml"`

**Comment by jasonbraganza** [comment]
`hugo new site test -f yml` works on my machine as expected. What was the issue you faced?

I’m running Hugo v0.120.4

**Comment by soul-ride** [comment]
I have similar issue with hugo extended v0.120.x on Windows.

All of these create site with hugo.toml config file inside (not expected):
- _hugo new site example.com -f yaml_
- _hugo new site example.com -f json_
- _hugo new site example.com -f "yaml"_

Creates site with hugo.yaml config file as expected:
_hugo new site example.com --format "yaml"_

**Comment by jasonbraganza** [comment]
aah now i get it, yes! it creates a `hugo.toml` file with `hugo new site test -f yml`, instead of the expected `yaml` file

**Comment by s0l1dx10** [comment]
Actually, I reported the same issue here #1336 😃 and like @soul-ride said the new command is:
 `hugo new site <name-of-site> --format "yaml"`
 Should work with you.

**Comment by adityatelange** [comment]
done https://github.com/adityatelange/hugo-PaperMod/wiki/Installation/_history Thanks @soul-ride @s0l1dx10
