### ISSUE TITLE
Update Wiki on architypes to match Hugo Quickstart docs 

### ISSUE THREAD

**Issue by bryndin** [adityatelange/hugo-PaperMod#1341]
`You can use it by creating archetypes/post.md`
at the bottom of [installation docs wiki page](https://github.com/adityatelange/hugo-PaperMod/wiki/Installation) 

Must be
`You can use it by creating archetypes/posts.md`

i.e. plural `posts` to match [Hugo Quickstart / Add Content](https://gohugo.io/getting-started/quick-start/#add-content) docs
```
hugo new content posts/my-first-post.md
```

Otherwise Hugo can't auto match the architype.

**Comment by adityatelange** [comment]
ok
