### ISSUE TITLE
[BUG] The cover image declared in the frontmatter doesn't appear anymore after the last theme update

### ISSUE THREAD

**Issue by nicfab** [adityatelange/hugo-PaperMod#1355]
**Describe the bug**

 - Os: MacOS Sonoma 14.1.2
 - Type: Desktop
 - Browser and version: Firefox, Safari, Brave
 - Hugo Version [ >=0.97.1 expected]:  v0.121.1
 - Theme Version [e.g. v4.0, master, or commit-id ]: 7 master

**Steps to reproduce the behavior:**

Under `/folder/themes/PaperMod` I run `git stash` and `git pull` to update the PaperMod theme
Thus I ran `hugo server` to see the website and the cover image doesn't appear anymore.
The same it happens if I deploy the local content to the server via `rsync`.
You see what I mean here: https://notes.nicfab.eu/en/

**Expected behavior**:

To see the cover images of every post.

**Comment by adityatelange** [comment]
Hi @nicfab, didn't find issue with demo site please check
https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-installation/
https://adityatelange.github.io/hugo-PaperMod/posts/markdown-syntax/

**Comment by adityatelange** [comment]
@nicfab I see the below lines

```
    cover:
        hidden: false
        hiddenInList: true
        hiddenInSingle: true
```

this hides them from List and Single pages

**Comment by nicfab** [comment]
> @nicfab I see the below lines
> 
> ```
>     cover:
>         hidden: false
>         hiddenInList: true
>         hiddenInSingle: true
> ```
> 
> this hides them from List and Single pages

Thank you very much!
Yes, indeed.
I appreciate your support.

Last thing: I wonder why the social icons on the home page are not centered [https://notes.nicfab.eu](https://notes.nicfab.eu).
Any suggestion?

**Comment by adityatelange** [comment]
> Any suggestion?

can add a custom css with text-align center for .social-icons class

**Comment by adityatelange** [comment]
@nicfab try

homeInfoParams:
        AlignSocialIconsTo: "center" # or left or right

**Comment by nicfab** [comment]
> @nicfab try
> 
> ```
> homeInfoParams:
>         AlignSocialIconsTo: "center" # or left or right
> ```

Thank you very much. 
You are very kind.

**Comment by nicfab** [comment]
> @nicfab try
> 
> ```
> homeInfoParams:
>         AlignSocialIconsTo: "center" # or left or right
> ```

Thank you, but it doesn't work.
I found the solution by copying the `social_icons.html` file from the PaperMod folder to `/layout/partials`, editing it, and adding `<center>` and `</center>` as follows:

```
<div class="social-icons">
    <center>
    {{- range . }}
    <a href="{{ trim .url " " | safeURL }}" target="_blank" rel="noopener noreferrer me" title="{{ (.title | default .name) | title }}">
        {{ partial "svg.html" . }}
    </a>
    {{- end }}
</center>
</div>

```

**Comment by kurotych** [comment]
Thank you @nicfab I had the same problem and your solution helped me.
