### ISSUE TITLE
[BUG] Social Icons miss aligned

### ISSUE THREAD

**Issue by cebor** [adityatelange/hugo-PaperMod#1359]
**Describe the bug**

Since 6864770ad4dd67fe381e143ca48bdd81c38835ce social icons are miss aligned in profile mode

 - Device/Os: macOS
 - Type: Desktop
 - Browser and version: Firefox
 - Hugo Version [ >=0.97.1 expected]: 0.121
 - Theme Version: master

**Screenshots**

Before:

<img width="294" alt="Screenshot 2023-12-15 at 18 20 16" src="https://github.com/adityatelange/hugo-PaperMod/assets/1576120/5f46e68f-30b0-4f88-bb26-a1e75d7b12b3">

<br>

After:

<img width="325" alt="Screenshot 2023-12-15 at 18 19 54" src="https://github.com/adityatelange/hugo-PaperMod/assets/1576120/b2a5e56c-c679-4f33-925a-ff205a5c456a">

**Comment by adityatelange** [comment]
reverted, my bad
