### ISSUE TITLE
[BUG] Issue in rendering cover when the resource is global

### ISSUE THREAD

**Issue by PooriaT** [adityatelange/hugo-PaperMod#1363]
**Describe the bug**

 - Device/Os: [e.g. Android 10]: Ubuntu 22.04
 - Type: [e.g. Desktop/Mobile]: Desktop
 - Browser and version [e.g. Chrome 86.0]: Firefox 121.0
 - Hugo Version [ >=0.112.4 expected]: hugo v0.121.1

 - Theme Version [e.g. v4.0, master, or commit-id ]: V7.0

**Expected behavior**:
When I tired to add a cover image, it returned an error due to an issue in `cover.html`. Line 9, `resources` has to be changed to `.Resources`. Then, it is fixed.

**Repo/Source where this issue can be reproduced**:
`https://github.com/adityatelange/hugo-PaperMod/blob/master/layouts/partials/cover.html`

**Comment by adityatelange** [comment]
> it returned an error due to an issue in cover.html
Hi @PooriaT can you share which issue? or console log? or steps to reproduce?
cover images works fine in demo.

**Comment by PooriaT** [comment]
Hi @adityatelange 
When I tried to provide the cover letter for a post whose image was located in a static folder, it returned an error and referred to line 9 of `cover.html` which can not find the image. When I changed the `resource` to `.Resource`, it was fixed.

**Comment by adityatelange** [comment]
Yes I get it but I need to find the how and why before trying to know a fix for this issue.
https://github.com/adityatelange/hugo-PaperMod/blob/a1cb044262d33d11860feb847c4c30aa281aee82/layouts/partials/cover.html#L9

As per hugo docs resources.ByType is used for global reource.
https://gohugo.io/functions/resources/bytype/

**Comment by PooriaT** [comment]
Yes, you are right. TBH, in the first implementation, it returned the reported error and it was fixed after the mentioned change. Now, I tried to revert back the code to what it was and send out the screenshot of the error to you but it worked fine and it is odd.

**Comment by PooriaT** [comment]
If I face the issue once more, I try to get a screenshot and send it back to you. Anyway, thanks for checking.

**Comment by adityatelange** [comment]
sure, closing for now
