### ISSUE TITLE
PDF Icon

### ISSUE THREAD

**Issue by fuccichris** [adityatelange/hugo-PaperMod#137]
would it be possible to create the adobe PDF image as an icon for papermod as well? Thank you.

**Comment by adityatelange** [comment]
@fuccichris where do you want this icon to be ?

**Comment by fuccichris** [comment]
Hi adityatelange, I'm hoping to use it as one of my icons when in profile mode, so that I can have a link to my github, linkedin, and resume. Ideally, i hope it could become a social icon like the ones featured in your link: https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-icons/. Thanks!

**Comment by adityatelange** [comment]
@fuccichris Adobe PDF is not a social platform imo, but PRs are welcome ..

**Comment by fuccichris** [comment]
ty ty, happy holidays mate
