### ISSUE TITLE
[BUG] BreadcrumbList itemListElement is not correct json format

### ISSUE THREAD

**Issue by helywin** [adityatelange/hugo-PaperMod#1373]
**Describe the bug**

BreadcrumbList itemListElement is not correct json format

 - Device/Os: Windows
 - Type: Desktop
 - Browser and version [e.g. Chrome 86.0]: Firefox 121.0
 - Hugo Version [ >=0.112.4 expected]: v0.121.1
 - Theme Version [e.g. v4.0, master, or commit-id ]: master

**Steps to reproduce the behavior:**

1. Go to <https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-installation/>
2. Soucecode of webpage

html xpath:`/html/head/script[1]`

```html
<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  "itemListElement": [, 
    {
      "@type": "ListItem",
      "position":  2 ,
      "name": "Posts",
      "item": "https://adityatelange.github.io/hugo-PaperMod/posts/"
    }, 
    {
      "@type": "ListItem",
      "position":  3 ,
      "name": "PaperMod",
      "item": "https://adityatelange.github.io/hugo-PaperMod/posts/papermod/"
    }, 
    {
      "@type": "ListItem",
      "position":  4 ,
      "name": "Install / Update PaperMod",
      "item": "https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-installation/"
    }
  ]
}
</script>
```

3. There is a comma after `"itemListElement": [`

**Expected behavior**:

correct json format

**Repo/Source where this issue can be reproduced**:

<https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-installation/>

<https://www.helywin.com/posts/20220412181224/>

**Screenshots**

![图片](https://github.com/adityatelange/hugo-PaperMod/assets/38039316/584ea340-2eb1-493f-871f-c6ffb727e854)

**Additional context**

**Comment by adityatelange** [comment]
Fixed by #1368
