### ISSUE TITLE
on macOS Sonoma and Safari `defaultTheme = auto` does not appear to work properly

### ISSUE THREAD

**Issue by nicolaiarocci** [adityatelange/hugo-PaperMod#1382]
- macOS Sonoma with Dark Mode set on 'auto' (or 'dark'). 
- config.yml `defaultTheme` set to 'auto';.
- On Chrome, website correctly appears as dark, matching the SO setting.
- On Safari, website stays 'light', while it should be dark.

<img width="2559" alt="image" src="https://github.com/adityatelange/hugo-PaperMod/assets/512968/f94d3bf1-87a8-4bb0-a41f-5672a4d74f9e">

 - Os: macOS Sonome 14.1.1
 - Type: Desktop
 - Browser and version Safari 17.1
 - Hugo Version 0.121.1
 - Theme Version: master

**Comment by chrisrummel** [comment]
Can't confirm that.
I have both Sonoma's theme on auto and my website on auto and when using Safari my website is displayed with the light theme at daytime and with the dark theme at nighttime.

**Comment by nicolaiarocci** [comment]
As per @chrisrummel hint I deleted my website cookies, refreshed the page, and now it appears dark as it should given that we're in the evening in my timezone. So it appears that if a actively opts for dark/light via the UI button, that preference will be saved for his/her next visits, which is probably a nice feature to have.
