### ISSUE TITLE
[BUG] ShowFullTextInRSS creates invalid RSS feed

### ISSUE THREAD

**Issue by schroedingersZombie** [adityatelange/hugo-PaperMod#1385]
**Describe the bug**
Commit [#00488d0](https://github.com/adityatelange/hugo-PaperMod/commit/00488d01463fc8c8db9fbda3f6060a0b5b373464) introduces an error, when site.params.showFullTextInRSS is st to true.

It removes the xmlns:content="http://purl.org/rss/1.0/modules/content/" attribute in the rss tag. This is required for the <content:encoded> tag containing the full text.

 - Hugo Version [ >=0.112.4 expected]: 121.2
 - Theme Version [e.g. v4.0, master, or commit-id ]: master

**Steps to reproduce the behavior:**
insert
```
params:
  showFullTextInRss: true
```
into hugo.yaml.
Paste https://yoursite.net/index.xml into https://validator.w3.org/feed/check.cgi
![image](https://github.com/adityatelange/hugo-PaperMod/assets/3123453/95255812-8745-478d-9d24-7b6a4df31da7)

**Expected behavior**:
RSS feed validates successfully.

*Edit: just noticed, I forgot to type a title*

**Comment by Yuk-0v0** [comment]
same problem

**Comment by vindex10** [comment]
Hi! This PR fixes the problem, although it also brings a feature :upside_down_face: 

https://github.com/adityatelange/hugo-PaperMod/pull/1370

**Comment by schroedingersZombie** [comment]
Thank you very much! :)
