### ISSUE TITLE
Missing docs for https://github.com/adityatelange/hugo-PaperMod/pull/1364

### ISSUE THREAD

**Issue by jimangel** [adityatelange/hugo-PaperMod#1386]
**Describe the bug**
https://github.com/adityatelange/hugo-PaperMod/pull/1364 landed, it would be good to cover in the docs what needs to be done to use / impact / migrate.

I don't think it's a huge deal, but I was doing some different things with chroma and took a bit to resolve because css files were overriding the new approach.

Ref: https://github.com/jimangel/jimangel.io/commit/a78a7563ee45b1a2c57a3c395033be6c4da015da

**Comment by jimangel** [comment]
> Is it possible this behaviour itself is a bug? Or am I missing something?

I ran into this when trying to have two .css files for light and dark mode. I had one background for light and one background for dark.

When I was trying to fix this, after upgrading, I eventually stripped all the custom chroma away and used a theme (and noticed the same thing you are pointing out).

Instead of fighting the statically set `!important` code-block-bg, I just left it.

The original author might have assumed that forcing the background color (for both via `background: var(--code-block-bg) !important;`) is the best option vs. change/toggle based on mode. You can test this out by adding a `monokailight` theme via `hugo gen chromastyles --style=monokailight > assets/css/includes/chroma-styles.css`.

I wouldn't mind having light/dark mode support for the code block background, but I can get by with `monokai` in both settings.

**Comment by adityatelange** [comment]
Hi,
> **Describe the bug** #1364 landed, it would be good to cover in the docs what needs to be done to use / impact / migrate.
> 
> I don't think it's a huge deal, but I was doing some different things with chroma and took a bit to resolve because css files were overriding the new approach.
> 
> Ref: [jimangel/jimangel.io@a78a756](https://github.com/jimangel/jimangel.io/commit/a78a7563ee45b1a2c57a3c395033be6c4da015da)

There is no impact as such if you are using no customization PaperMod. Of course there can be if you have customized it.

If you have disabled HLJS and using own chromastyles, all you need to do is move your chromastyles css to `assets/css/includes/chroma-styles.css`.


> I encountered a similar issue. post-single.css has the following block that's overriding chroma:

This we are doing it from very long time and is not introduced with this PR.

Chromastyles have their own background color set for each theme and this may or may not look good with PaperMod.
Making users use only a few themes isn't an option either which will add more css to support each theme.
The PR sticks to what we had by default from a long time.

**Comment by yunyit** [comment]
> which directly conflicts with the background set by the chroma-style.css so I don't think there's a good way to adopt this other then just override the whole file with my own  chroma-mod.css...

I have the following setup in `assets/css/extended/blank.css` : 
```css
.post-content pre code , 
.post-content .highlight:not(table) ,
.post-content .highlight table
 {
    background: unset !important;
    background-color: var(--code-bg) !important; /* 兼容日夜显示模式 */
    color: var(--secondary) !important; /* 兼容日夜显示模式 */
}
```
and `assets/css/includes/chroma-mod.css` unchanged for 
```
.chroma {
    background-color: unset !important;
}
```
I choose  [trac](https://xyproto.github.io/splash/docs/trac.html) for 
```shell
hugo gen chromastyles --style=trac > assets/css/includes/chroma-styles.css
```
and it works well :)
