### ISSUE TITLE
How to enable search?

### ISSUE THREAD

**Issue by danijeljw-RPC** [adityatelange/hugo-PaperMod#1388]
I have followed your guidance and also created a link in the navbar to `/search` but I am only getting a 404 page? How do I enable search?

**Comment by hellloveyy** [comment]
You can check if your public directory did not generate a corresponding file. You can enter `hugo` on the command line

**Comment by RoneoOrg** [comment]
Please show your code a public repo

**Comment by 64bitpandas** [comment]
In case anyone's still running into the same issue- I resolved it by renaming `content/index.md` to `content/_index.md` ([here's why it works](https://discourse.gohugo.io/t/hugo-refuses-to-build-pages-in-content-folder/30648)).
