### ISSUE TITLE
Katex Cases does not go onto a new line

### ISSUE THREAD

**Issue by bee-san** [adityatelange/hugo-PaperMod#139]
Per Katex documentation:
![image](https://user-images.githubusercontent.com/10378052/102416556-f715c780-3ff1-11eb-932c-86df9354301b.png)
https://katex.org/docs/supported.html

This code:

```
x = \begin{cases}a &\text{if } b \\c &\text{if } d\end{cases}
```

Produces this output in the theme:
![image](https://user-images.githubusercontent.com/10378052/102416692-36441880-3ff2-11eb-9125-8b3b75f09c56.png)

However, in my own formula which has cases I get this output:
![image](https://user-images.githubusercontent.com/10378052/102416718-43610780-3ff2-11eb-8505-58e39a322063.png)

When it should look like:
![image](https://user-images.githubusercontent.com/10378052/102416746-51af2380-3ff2-11eb-931e-98c0114d7a73.png)

Code:

```
$$OPT(i) = \begin{cases}B[k - 1, w], \quad \text{If w < }w_k \\ max{B[k-1, w], b_k + B[k - 1, w - w_k]}, \; \quad \text{otherwise} \end{cases}$$
```

Is this a CSS issue?

**Comment by bee-san** [comment]
Oh, could it be this:

**Comment by kdkasad** [comment]
I don't think this would be a CSS issue. You can try using an inline shortcode to write HTML directly, avoiding the Markdown preprocessor altogether:
```html
{{< math.inline >}}
<p>
$$
OPT(i) = \begin{cases}B[k - 1, w], \quad \text{If w < }w_k \\ max{B[k-1, w], b_k + B[k - 1, w - w_k]}, \; \quad \text{otherwise} \end{cases}
$$
</p>
```

**Comment by bee-san** [comment]
Wow that works!!! You really know your stuff 😅

**Comment by xsro** [comment]
I want to use katex code like this

```
$$
\begin{equation}
\begin{split}   a &=b+c\\
      &=e+f
\end{split}
\end{equation}
$$
```

but I find the katex can't render it. The result is like this. Is there a way to solve this problem?

<img width="364" alt="截屏2021-08-28 下午12 47 23" src="https://user-images.githubusercontent.com/64292434/131206513-f0fd0ac3-f5bd-47c9-a8ba-2ceac540c988.png">

and this is my content in `extend_head.html`

```html
{{ if or .Page.Params.math .Site.Params.math }}
<!-- KaTeX -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.13.13/dist/katex.min.css" integrity="sha384-RZU/ijkSsFbcmivfdRBQDtwuwVqK7GMOw6IMvKyeWL2K5UAlyp6WonmB8m7Jd0Hn" crossorigin="anonymous">
<script defer src="https://cdn.jsdelivr.net/npm/katex@0.13.13/dist/katex.min.js" integrity="sha384-pK1WpvzWVBQiP0/GjnvRxV4mOb0oxFuyRxJlk6vVw146n3egcN5C925NCP7a7BY8" crossorigin="anonymous"></script>
<script defer src="https://cdn.jsdelivr.net/npm/katex@0.13.13/dist/contrib/auto-render.min.js" integrity="sha384-vZTG03m+2yp6N6BNi5iM4rW4oIwk5DfcNdFfxkk9ZWpDriOkXX8voJBFrAO7MpVl" crossorigin="anonymous"
 onload="renderMathInElement(document.body,{
          // customised options
          // • auto-render specific keys, e.g.:
          delimiters: [
              {left: '$$', right: '$$', display: true},
              {left: '$', right: '$', display: false}
          ],
          // • rendering keys, e.g.:
          throwOnError : true
        });"></script>
{{ end }}
```
