### ISSUE TITLE
[BUG] Background Color Mismatch in Light Mode

### ISSUE THREAD

**Issue by ibrahimcetin** [adityatelange/hugo-PaperMod#1418]
**Describe the bug**

 - Hugo Version [ >=0.112.4 expected]: v0.122.0
 - Theme Version [e.g. v4.0, master, or commit-id ]: master

Background color mismatch on single page **in light mode** with profile mode.

**Steps to reproduce the behavior:**

In light mode, you can easily see the background color mismatch when switching between the home and about tabs on [my website](https://ibrahimcetin.dev).

**Expected behavior**:

All pages background color should be the same.

**Repo/Source where this issue can be reproduced**:

My website: https://ibrahimcetin.dev
Source code: https://github.com/ibrahimcetin/ibrahimcetin.dev

**Screenshots**

<img src=https://github.com/adityatelange/hugo-PaperMod/assets/33904390/749135ea-0b55-4b15-b352-03c5000a6948) height=400 width=400 alt=Home Page Screenshot/>
<img src=https://github.com/adityatelange/hugo-PaperMod/assets/33904390/c9ce72b4-07b5-4acb-b102-9f08f4a1ac72 height=400 width=400 alt=About Page Screenshot/>

I think the difference is clear, about page has a lighter background color.

**Additional context**

I'm using profile mode on [my website](https://ibrahimcetin.dev/), but the about page has a background color mismatch in light mode. I noticed that the about page, being a single page, doesn't have the class="list" attribute on its body tag. When I manually add the class, everything seems okay.

**Proper Solution**
I a bit dived into the theme's source code and fixed the issue by modifying [this line](https://github.com/adityatelange/hugo-PaperMod/blob/66904cc4c2b292e6a3686d483e4054904a9f3954/layouts/_default/baseof.html#L13).

To resolve the issue, I introduced a new layout named `single` in `about.md` to distinguish it from other layouts. Additionally, I added ```(eq .Layout `single`))``` to the mentioned line. This simple addition seems to have fixed the problem. However, since I'm not familiar with the theme's internals, I am not sure this is *the solution*. If it is, I can create a pull request.

**Comment by LucyLikesYourFace** [comment]
>  When I manually add the class, everything seems okay.
Out of curiosity I tested this against the demo site, doing this makes the background the same colour as buttons etc.
Perhaps its intentional?
![papermod scrs](https://github.com/adityatelange/hugo-PaperMod/assets/56839145/f24f1c30-f22c-46cf-bfd1-91fab6d2820b)

**Comment by h-subaru** [comment]
@ibrahimcetin @LucyLikesYourFace 

Hi, I noticed the problem in the page of @ibrahimcetin , and reproduced the same background-collision, as @LucyLikesYourFace mentions. 

The solution of @ibrahimcetin shows some fallback background-color settings （ either of `body` or of `html`  ） for the **single** kind pages be inconsistent with **list** pages ...?

**Comment by h-subaru** [comment]
I tried some modification like this:
1. `body` background same as `.list`（ to set consistent background-color）

    `assets/css/extended/blank.css` 
    - copies it from PaperMod repo

    ```css
    /*
    This is just a placeholder blank stylesheet so as to support adding custom styles budled with theme's default styles

    ......
    */
    body {
        background: var(--code-bg);
    }

    body.dark {
        background: var(--theme);
    }
    ```
2. add `.post-entry` class to the container of contents （to keep the color contrast in the single page **content** and **footer** ）

    `layouts/_default/single.html`
    - copies it from PaperMod repo
        -  L. 38: appends `.post-entry` class attribute

        ```html
          <!-- <div class="post-content"> -->
         <div class="post-content post-entry">
        ```
        - L. 45: appends `.post-entry` class attribute

        ```html
          <!-- <footer class="post-footer"> -->
          <footer class="post-footer post-entry">
        ```

**Comment by h-subaru** [comment]
# Result （ /posts/hello/ single page）

## in Light mode

![image](https://github.com/adityatelange/hugo-PaperMod/assets/12190539/952239b2-d614-407e-81e9-c94c3886b4c2)

## in Dark mode

![image](https://github.com/adityatelange/hugo-PaperMod/assets/12190539/998876fb-92fd-4d1c-9ca4-b2b2e316fa72)

**Comment by adityatelange** [comment]
> All pages background color should be the same.

This is intended, not a bug.
