### ISSUE TITLE
Add BlueSky to the list of Social Icons in the Wiki

### ISSUE THREAD

**Issue by MVPuccinoV2** [adityatelange/hugo-PaperMod#1421]
BlueSky is missing from the Social Icons list in the Wiki despite PaperMod supporting it.

**Comment by adityatelange** [comment]
sure

**Comment by samanthavbarron** [comment]
I came here to open the same issue since it's not listed on this page? https://github.com/adityatelange/hugo-PaperMod/wiki/Icons
