### ISSUE TITLE
optionally allow cover image to lead to the post itself

### ISSUE THREAD

**Issue by vindex10** [adityatelange/hugo-PaperMod#1422]
I suggest to have an option in settings, which would allow the cover image to lead to the post it is covering.

Current behavior is that the link is to the source image, not to the post.

I find it intuitive for the cases, when cover image serves as a "larger and more descriptive title" of the post.

Related PR, which we can update if we land on some alternative solution:

https://github.com/adityatelange/hugo-PaperMod/pull/1371

**Comment by adityatelange** [comment]
> > linkFullImages can be true, false or post. When it is post, the image in the cover leads to the post.
>
> I don't see where we have mentioned it can be `post`?

_Originally posted by @adityatelange in https://github.com/adityatelange/hugo-PaperMod/issues/1371#issuecomment-1985059231_
