### ISSUE TITLE
allow exposing theme css variables in settings

### ISSUE THREAD

**Issue by vindex10** [adityatelange/hugo-PaperMod#1424]
To allow more theme customizations through hugo.yaml, I suggest to make theme-vars.css renderable.

this small change opens a wide variety of opportunities in future.

For example, a use case which I'm interested in: allow to configure how many lines are visible in the preview in the list of the posts. This is specified in CSS, and impossible to tune via hugo.yaml yet, because css is not rendered by default.

`theme-vars.css` is supposed to be very simple, so I wouldn't expect its being rendered - a big issue.

Relevant PR which we can adapt with the flow of the discussion:
https://github.com/adityatelange/hugo-PaperMod/pull/1399

**Comment by adityatelange** [comment]
> I don't see any use case here. Users can already override theme-vars.css file ([using this](https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#override-theme-template))

_Originally posted by @adityatelange in https://github.com/adityatelange/hugo-PaperMod/issues/1399#issuecomment-1985058636_
