### ISSUE TITLE
underline post list entry title on hover

### ISSUE THREAD

**Issue by vindex10** [adityatelange/hugo-PaperMod#1426]
I would very much like to be able to make the "hover" more explicit than just changing the cursor to "pointer", on the list page, when hovering on some entry.

I suggest to underline the title:
https://github.com/adityatelange/hugo-PaperMod/pull/1402/

But maybe there are alternative suggestions and we could land on something together :) 

Thank you!

**Comment by adityatelange** [comment]
> Closing as this is an amend for https://github.com/adityatelange/hugo-PaperMod/pull/1401

_Originally posted by @adityatelange in https://github.com/adityatelange/hugo-PaperMod/issues/1402#issuecomment-1985057180_
