### ISSUE TITLE
[BUG] Misaligned long footer for low width devices.

### ISSUE THREAD

**Issue by dng-nguyn** [adityatelange/hugo-PaperMod#1427]
**Describe the bug**

 - Device/Os: Mobile devices
 - Type: Mobile
 - Browser and version: Any
 - Hugo Version: v0.122.0
 - Theme Version: 7.0

**Steps to reproduce the behavior:**

1.Have a 1-line long footer on a low-width screen

**Expected behavior**:

The footer is aligned in the middle.

**Repo/Source where this issue can be reproduced**:

https://dinhcap.dev

**Screenshots**

low width (iphone SE): misaligned to the right. this could trigger side scrolling, which can be annoying.
![image](https://github.com/adityatelange/hugo-PaperMod/assets/133786254/70ec4116-a84f-4fc0-912b-db6c3af5bc38)

**Additional context**

Edited: This is unlikely to happen under most circumstances (e.g website with short footer, multiple \<span> tags, bigger screen devices) and can be avoided by using multiple \<span> tags instead of a long one.

**Comment by adityatelange** [comment]
Should never happen after https://github.com/adityatelange/hugo-PaperMod/commit/28b86cb5a602f4a64e90dce035e30ebe9fad1d6a
