### ISSUE TITLE
[BUG] Render of "page" failed:

### ISSUE THREAD

**Issue by trashcatt** [adityatelange/hugo-PaperMod#1430]
**Describe the bug**

 - Device/Os: GitLab
 - Type: [e.g. Desktop/Mobile]
 - Browser and version [e.g. Chrome 86.0]:
 - Hugo Version [ >=0.112.4 expected]: hugo v0.122.0 linux/amd64 BuildDate=unknown
 - Theme Version [e.g. v4.0, master, or commit-id ]: master

**Steps to reproduce the behavior:**

**The ERROR**
`Start building sites … 
hugo v0.122.0 linux/amd64 BuildDate=unknown
ERROR render of "page" failed: "/builds/sm0ggles/sm0ggles.gitlab.io/layouts/_default/single.html:25:6": execute of template failed: template: _default/single.html:25:6: executing "main" at <partial "cover.html" (dict "cxt" . "IsHome" false "isHidden" $isHidden)>: error calling partial: "/builds/sm0ggles/sm0ggles.gitlab.io/themes/PaperMod/layouts/partials/cover.html:4:22": execute of template failed: template: partials/cover.html:4:22: executing "partials/cover.html" at <$.IsSingle>: invalid value; expected bool
Total in 363 ms
Error: error building site: render: failed to render pages: render of "page" failed: "/builds/sm0ggles/sm0ggles.gitlab.io/layouts/_default/single.html:25:6": execute of template failed: template: _default/single.html:25:6: executing "main" at <partial "cover.html" (dict "cxt" . "IsHome" false "isHidden" $isHidden)>: error calling partial: "/builds/sm0ggles/sm0ggles.gitlab.io/themes/PaperMod/layouts/partials/cover.html:4:22": execute of template failed: template: partials/cover.html:4:22: executing "partials/cover.html" at <$.IsSingle>: invalid value; expected bool
Cleaning up project directory and file based variables 00:00
ERROR: Job failed: exit code 1`

**Expected behavior**:

For it to build correctly 
**Repo/Source where this issue can be reproduced**:
This repo isn't setup to build hugo but I needed to move the code to a public repo

https://gitlab.com/trashcatt/blog
**Screenshots**

**Additional context**

**Comment by adityatelange** [comment]
Can't reproduce. You might have made any custom changes to theme pull from upstream. https://github.com/adityatelange/hugo-PaperMod/commit/b288ede80cbd70151e2f07f2e09ad6258e64f7fa

**Comment by zznewclear13** [comment]
> Can't reproduce. You might have made any custom changes to theme pull from upstream. [b288ede](https://github.com/adityatelange/hugo-PaperMod/commit/b288ede80cbd70151e2f07f2e09ad6258e64f7fa)

There is a typo in `layouts/partials/cover.html`, line 9. It should be `.Resources.ByType` rather than `resources.ByType`.

**Comment by thomjiji** [comment]
I change the [line 4](https://github.com/adityatelange/hugo-PaperMod/blob/9ea3bb0e1f3aa06ed7715e73b5fabb36323f7267/layouts/partials/cover.html#L4C1-L4C50) in `themes/PaperMod/layouts/partials/cover.html` from:

`{{- $loading := cond $.IsSingle "eager" "lazy" }}`

to

`{{- $loading := cond (eq $.IsSingle true) "eager" "lazy" }}`

Then it can render as normal.
