### ISSUE TITLE
Output order CSS reversed since Hugo v0.123.0

### ISSUE THREAD

**Issue by dynabler** [adityatelange/hugo-PaperMod#1432]
**Describe the bug**
The CSS output is reversed with Hugo v0.123.0 and above. PaperMod partials/head.html has the correct order, but somehow Hugo 0.123.0 reverses the order and makes core.css come AFTER extended.css, which makes extended.css redundant.

 - Device/Os: [Windows 11]
 - Type: [Desktop]
 - Browser and version [Chrome 121]:
 - Hugo Version [v0.123.0](https://github.com/gohugoio/hugo/releases/tag/v0.123.0) and [v0.123.1](https://github.com/gohugoio/hugo/releases/tag/v0.123.1) 
 - Theme Version [PaperMod 7.0 ](https://github.com/adityatelange/hugo-PaperMod/releases/tag/v7.0)

**Steps to reproduce the behavior:**
1. Download & Install Hugo v0.123.0 or v0.123.1
2. Run `hugo server` to run or `hugo` in terminal to build hugo site
3. Open in browser `localhost:1313/assets/css/stylesheet.css` or public/style.css in text-editor
4. Notice extended.css comes BEFORE core.css
5. Download & install Hugo v1.222.0
6. Repeat steps 2-4
7. compare the style.css and notice the correct output as coded in partial/head.html with Hugo v0.122.0, but NOT with Hugo v0.123 and v0.123.1

**Expected behavior**:
I expected extended.css to come after core.css. Papermod partials/head.html is correct, nothing wrong there. But the output is reversed, e.g. extended.css comes before core.css

NOTE: if this could be solved for now, great. If it's a Hugo bug, could you file a bug report? I have no experience with software, so I have no idea how to describe the bug to Hugo dev team.

**Comment by adityatelange** [comment]
Hi @dynabler, 

what is the path for extended.css?

Can you check latest demo site it was built with  0.123.0

![image](https://github.com/adityatelange/hugo-PaperMod/assets/21258296/085e46a1-bf43-45d1-81bc-ffaca80f969b)

https://github.com/adityatelange/hugo-PaperMod/blob/3ba89eec3f1b3af568ddacccabddfe2d1c78517a/assets/css/extended/custom.css#L7-L9

custom css is in the end?

![image](https://github.com/adityatelange/hugo-PaperMod/assets/21258296/2ed35d67-13b1-4d51-8908-ae36c042a71e)
