### ISSUE TITLE
dead links in wiki

### ISSUE THREAD

**Issue by wswind** [adityatelange/hugo-PaperMod#1450]
on the page of the install wiki: https://github.com/adityatelange/hugo-PaperMod/wiki/Installation

some links are 404 not found:
<img width="457" alt="image" src="https://github.com/adityatelange/hugo-PaperMod/assets/18399096/88f3227d-f04e-4bdc-9f76-a7f1634421aa">

for example:
`https://github.com/adityatelange/hugo-PaperMod/papermod-features` should be changed to：
`https://github.com/adityatelange/hugo-PaperMod/wiki/Features`

**Comment by adityatelange** [comment]
Yeah man, I am unable to sync docs at 2 places, wiki and demo, when I do it, somethings breaks. Will fix thanks for letting me know
