### ISSUE TITLE
[BUG] Wiki: Installation - Expand Method 4

### ISSUE THREAD

**Issue by mintommm** [adityatelange/hugo-PaperMod#1472]
In https://github.com/adityatelange/hugo-PaperMod/wiki/Installation

When using "Expand Method 4 - Hugo module", setting of theme in the config file should be
```
theme: github.com/adityatelange/hugo-PaperMod
```
instead of
 ```
theme: ["PaperMod"]
```
.

**Comment by adityatelange** [comment]
![image](https://github.com/user-attachments/assets/bb461a89-8e96-4881-9a91-45d22ce03386)

**Comment by adityatelange** [comment]
https://discourse.gohugo.io/t/how-to-add-a-theme-using-modules-for-beginners/20665
