### ISSUE TITLE
Using profileMode UI on pages other than main

### ISSUE THREAD

**Issue by Allen-Hu** [adityatelange/hugo-PaperMod#149]
As the title, is it possible to show the profileMode UI on something like an "About Me" page rather than the homepage?
Thanks in advance!

**Comment by adityatelange** [comment]
Sorry no plans to this.. You may add it as a **shortcode** and put it on **about.md** page.

code for profile-mode page is here:
https://github.com/adityatelange/hugo-PaperMod/blob/0f994eee95811f5cf6099fb5897dd62be1e6cff2/layouts/partials/index_profile.html#L1-L21
