### ISSUE TITLE
Hugo Aliases Not Working as Expected

### ISSUE THREAD

**Issue by NickHerrig** [adityatelange/hugo-PaperMod#1492]
**Describe the bug**
I have a few posts that I want to redirect internally from old links while still keeping the original links in place. 
It's my understanding that I can use [Hugo Aliases](https://gohugo.io/content-management/urls/) for this task. 

When I configure the alias though, the redirect doesn't happen. 
Is there some sort of setting or configuration I'm missing?

Are Aliases supported with hugo-PaperMod?

 - Device/Os: Macbook Pro (Intel Chip)
 - Type: Desktop and Mobile
 - Browser and version [e.g. Chrome 86.0]: Arc Browser (Chromium Based)
 - Hugo Version [ >=0.112.4 expected]: hugo v0.121.2-6d5b44305eaa9d0a157946492a6f319da38de154+extended darwin/amd64 BuildDate=2024-01-05T12:21:15Z VendorInfo=brew
 - Theme Version [e.g. v4.0, master, or commit-id ]:  v7.0

**Steps to reproduce the behavior:**

Aliases can be configured via the Hugo documentation here - https://gohugo.io/content-management/urls/

To recreate the behavior add a alias on a new post at `/posts/my-post` and configure the alias to another post

```/content/posts/my-post.md
title = "My Post"
aliases = 
  - "/posts/my-other-post"
```

Then visit http://mywebsite/posts/my-post.

**Expected behavior**:
I would expect the page to be redirected to `/posts/my-other-post`.

Is there something I'm missing in the configuration? Are you able to configure an internal redirect with Aliases?

**Comment by adityatelange** [comment]
Aliases is not a PaperMod specific feature, it is common for all @gohugoio related themes.

Aliases work by creating an page which has refresh links to the the pege where you have aliases mentioned.

In the snippet you shared. `/posts/my-other-post` will have an html page with refresh link to page `/posts/my-post` .
So it'll be like `/posts/my-other-post` -> `/posts/my-post` and not vice versa.
Kindly discuss further working of aliases over here https://discourse.gohugo.io as this is not theme specific.
