### ISSUE TITLE
Wiki docs: dead link for DateFormat

### ISSUE THREAD

**Issue by gvlanaro** [adityatelange/hugo-PaperMod#1497]
In https://github.com/adityatelange/hugo-PaperMod/wiki/Variables:

```diff
-[Details](https://gohugo.io/functions/format/)
+[Details](https://gohugo.io/functions/time/format/)
```

I tried to create a pull request but apparently it's not supported for the wiki repository

**Comment by adityatelange** [comment]
Done mate.
