### ISSUE TITLE
[Discussion][Feature] Allow user configurable light/dark theme

### ISSUE THREAD

**Issue by singhkays** [adityatelange/hugo-PaperMod#15]
It's great that the theme supports auto light/dark theme but some readers might not want to be forced upon dark mode at night. The theme should allow the reader to specify or set such an option like the Novela theme (https://themes.gohugo.io/theme/hugo-theme-novela)

![image](https://user-images.githubusercontent.com/6164178/95008002-ae419b80-05ca-11eb-872c-4d12c0be425c.png)

**Comment by adityatelange** [comment]
I had thought of it before, it's a neat feature. But as you can see there's actually no place left on the navigation bar (which is not a hamburger style menu) !

**Comment by singhkays** [comment]
I'm not sure I understand which navigation bar. Here's an example from my blog

![image](https://user-images.githubusercontent.com/6164178/95008685-d7652a80-05d0-11eb-9c70-aa3746d4935b.png)

The button could be user configurable and could be in the places indicated or the last item in the navigation menu

**Comment by adityatelange** [comment]
@singhkays

**Comment by singhkays** [comment]
looks good 👍 closing
