### ISSUE TITLE
Image render hook vs the new embedded image render hook in 0.123

### ISSUE THREAD

**Issue by baekgaard** [adityatelange/hugo-PaperMod#1504]
PaperMod provides a layouts/_default/_markup/render-image.html render hook. 

However, in newer versions of Hugo (0.123 and beyond) a new embedded image render hook [is also provided](https://gohugo.io/render-hooks/images/#default). I think this may be meant as a better way to manage resources in a multilingual setup, but I also found it useful to avoid canonifyURL in cases where the entire site/baseURL is not at the root (i.e. like in www.xxx.yyy/zzz). 

The embedded image render hook needs to be manually enabled for some sites, but is automatically enabled for multilingual single-host sites in the default configuration.

It may not be obvious (when debugging) why the embedded _image_ render hook is not accessible when the embedded _link_ render hook works with PaperMod -- at least it took me some minutes to figure out why not all url's were rewritten correctly. 

I'm wondering to which degree the render-image.html hook in PaperMod is needed, or if it could be made to work with the embedded image render hook when enabled somehow -- although I don't currently see a good solution for that? I guess it's mainly there to provide the alt text?

In my own site, I simply made the embedded image render hook explicit by replacing (and updating) the render-image.html file with the [code of the embedded one](https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/_default/_markup/render-image.html).

**Comment by jmooring** [comment]
With the existing image render hook...
<https://github.com/adityatelange/hugo-PaperMod/blob/3f50861a0ced88f9b614a43662edeb4c0bc45da8/layouts/_default/_markup/render-image.html>


...page resources for non-default languages on a multilingual single-host site will not be found.

The only thing that the existing image render hook does is to add a lazy loading attribute. Either model the hook after Hugo's [embedded hook](https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/_default/_markup/render-image.html), or remove it.

**Comment by adityatelange** [comment]
can do

**Comment by adityatelange** [comment]
> ...page resources for non-default languages on a multilingual single-host site will not be found.

@jmooring I see we'll face compatibility issues with users using hugo < 0.125.0 as [PageInner](https://gohugo.io/render-hooks/images/#pageinner-details) was introduced in 0.125.0

**Comment by jmooring** [comment]
Your choices:

1. Require v0.125.0.
2. Use `Page` instead of `PageInner` in the render hook.
3. Do not include a render hook in your theme. The embedded hooks are automatically enabled for multilingual single-host sites.
