### ISSUE TITLE
[Bug?] Is this bug?

### ISSUE THREAD

**Issue by pacientes** [adityatelange/hugo-PaperMod#151]
I use the Microsoft Edge browser.
And I am using only syntax highlighting in the default blog theme file.

so... Press the'F5' key on the post page.
Then, web pages scroll automatically.

Is this some feature?

Video file download here.
[2020-12-23 22-29-33.zip](https://github.com/adityatelange/hugo-PaperMod/files/5735462/2020-12-23.22-29-33.zip)

Thank you.

**Comment by kdkasad** [comment]
It's caused by [layouts/_default/footer.html#30](https://github.com/adityatelange/hugo-PaperMod/blob/7c53c14c85bd1f6ea64547d08397ba441e31f9aa/layouts/partials/footer.html#L30). I think it should be removed, since most browsers will handle this anyways.

**Comment by pacientes** [comment]
@kdkasad I tested it removed that, but still scrolling. T-T

**Comment by kdkasad** [comment]
> @kdkasad I tested it removed that, but still scrolling. T-T

Right. Once you remove that piece of code, it's up to your browser to disable auto-scrolling. It happens on any site with Chromium-based browsers.

**Comment by pacientes** [comment]
> > @kdkasad I tested it removed that, but still scrolling. T-T
> 
> Right. Once you remove that piece of code, it's up to your browser to disable auto-scrolling. It happens on any site with Chromium-based browsers.

So. How can I fix previous scroll position?

**Comment by adityatelange** [comment]
@pacientes sorry for not replying, 0f994ee should have fixed the bug ! it was because we were using smooth scroll with css and it forces any scroll to be smooth, and not only with anchor links within header !

---


> I think t's caused by [layouts/_default/footer.html#30](https://github.com/adityatelange/hugo-PaperMod/blob/7c53c14c85bd1f6ea64547d08397ba441e31f9aa/layouts/partials/footer.html#L30). I think it should be removed, since most browsers will handle auto-scrolling anyways.

The snippet you have mentioned is for getting menu's scroll position and is unrelated to #151
