### ISSUE TITLE
CSP Enhancement by removing unsafe-inline

### ISSUE THREAD

**Issue by Schwitzd** [adityatelange/hugo-PaperMod#1517]
Dear all,

I've added the CSP header to my Hugo site, but to render PaperMod correctly I'm forced to add the `script-src 'unsafe-inline'` directive.
Can you please consider removing inline JavaScript and style?

Many thanks

**Comment by adityatelange** [comment]
Can you give me an example how an adversary would use inline scripts to compromise static sites?

**Comment by Schwitzd** [comment]
Here you can find some examples: [Do you use Content Security Policy with your Hugo site?](https://discourse.gohugo.io/t/do-you-use-content-security-policy-with-your-hugo-site/20512)

**Comment by adityatelange** [comment]
> Here you can find some examples: [Do you use Content Security Policy with your Hugo site?](https://discourse.gohugo.io/t/do-you-use-content-security-policy-with-your-hugo-site/20512)

I know CSP is a good way to prevent some attacks. If you are certain about the impact please let me know the entry points and attack paths available using `inline-scripts`.

**Comment by Schwitzd** [comment]
I'm using profile mode and when I remove `unsafe-inline' from my homepage I get the following errors:
![Screenshot from 2024-05-19 13-23-08](https://github.com/adityatelange/hugo-PaperMod/assets/15292575/deb96711-58af-4147-a7ff-6a66db7dc9c9)

**Comment by adityatelange** [comment]
alright, figure it out
