### ISSUE TITLE
[BUG?] Code block wraps on Safari

### ISSUE THREAD

**Issue by michael0liver** [adityatelange/hugo-PaperMod#152]
This is a long code block using Chrome/Firefox. It gives a nice horizontal scrolling:
<img width="534" alt="image" src="https://user-images.githubusercontent.com/55017335/103086119-a1d24b00-45db-11eb-98ab-9140d11a973c.png">

This is the same block on Safari (macOS & iOS):
<img width="570" alt="image" src="https://user-images.githubusercontent.com/55017335/103086076-7e0f0500-45db-11eb-9112-fc0b1b5b2258.png">

Instead of horizontal scrolling it wraps the text which I do not like, since all browsers on iOS use webkit then it affects Chrome and Firefox on iOS as well.

Using `display: inline-block;` gives us no wrapping but makes whole page horizontal scrollable instead of just code block.

Thanks for the theme again its really great 🚀 !

**Comment by adityatelange** [comment]
@michael0liver I do not own a apple device and cannot fix this myself.

Though this isn't an issue on linux / windows desktops as I have tested this on FF and chromium based browsers, it is safari specific imo
