### ISSUE TITLE
[BUG]run well in local,but fault when publish in github.

### ISSUE THREAD

**Issue by baiwan-chenhao** [adityatelange/hugo-PaperMod#1520]
in the terminal:

blog/:14  Failed to find a valid digest in the 'integrity' attribute for resource 'https://baiwan-chenhao.github.io/blog/assets/css/stylesheet.4599eadb9eb2ad3d0a8d6827b41a8fda8f2f4af226b63466c09c5fddbc8706b7.css' with computed SHA-256 integrity 'tgnFjVwRu5CxpU4EAF10rR3fIhZet59VM5Z+V9+cO1A='. The resource has been blocked.

**Comment by baiwan-chenhao** [comment]
publish well when using other theme.

**Comment by heyzqq** [comment]
Has this problem been solved? @baiwan-chenhao

**Comment by weeix** [comment]
From https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#failed-to-find-a-valid-digest-in-the-integrity-attribute-for-resource--

**Solution:**

Set the following in config.yml

```yaml
params:
  assets:
    disableFingerprinting: true
```
