### ISSUE TITLE
Error post-meta

### ISSUE THREAD

**Issue by nicfab** [adityatelange/hugo-PaperMod#1524]
After updating the theme to the latest version, v7.0, via `git pull` - `git checkout v7.0` on my website, an error related to the file `post_meta.html` appears.

You can see directly on the Internet, [here for example](https://notes.nicfab.eu/en/posts/restic/), that at the beginning of a post, it appears `<span title='etc.`.

Is there something I did wrong?

**Comment by adityatelange** [comment]
Maybe go through pinned issues?

**Comment by nicfab** [comment]
> Maybe go through pinned issues?

Sorry, what do you mean?

**Comment by adityatelange** [comment]
> > Maybe go through pinned issues?
> 
> Sorry, what do you mean?

duplicate of #1325 #1344

**Comment by nicfab** [comment]
> > > Maybe go through pinned issues?
> > 
> > 
> > Sorry, what do you mean?
> 
> duplicate of #1325 #1344

I am so sorry.
I missed them; I look forward for your update.

**Comment by adityatelange** [comment]
this is already fixed you can update your submodule with latest commit from master branch and that will do

**Comment by dirsigler** [comment]
@nicfab in your site folder run

```sh
git submodule update --init --recursive
git submodule update --remote --merge
```
