### ISSUE TITLE
Generated Schema.org invalid because of missing comma

### ISSUE THREAD

**Issue by robhenley** [adityatelange/hugo-PaperMod#1525]
The schema.org schema generated is not valid for me because it's missing a comma in the array.  An example of which is here:

```json
{
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  "itemListElement": [
    {
      "@type": "ListItem",
      "position":  1 ,
      "name": "Posts",
      "item": "/posts/"
    }
    {
      "@type": "ListItem",
      "position":  1 ,
      "name": "An Example Post",
      "item": "/post/an-example-post/"
    }
  ]
}
```

I didn't have time to fully diagnose but the issue appears to be the following line:

https://github.com/adityatelange/hugo-PaperMod/blob/3f50861a0ced88f9b614a43662edeb4c0bc45da8/layouts/partials/templates/schema_json.html#L48

If I change no code it seems like the following added the comma fine:
```bash
hugo --gc serve
```

This, again with unmodified code, however resulted in the comma being missing:
```bash
rm -rf public/ && hugo --gc && nvim public/post/an-example-post/index.html
```

If I change schema_json.html L48  to the following it works in both scenarios:
```go
  {{- if (ge (len $bc_list) 1) }}, {{end }}j
```

**Comment by adityatelange** [comment]
trying to diagnose issue but dersi

**Comment by adityatelange** [comment]
trying to diagnose issue but this isn't helping as bug report template isn't used. 
can't reproduce it. what i can speculate is you are setting the base URL to '/'

**Comment by robhenley** [comment]
@adityatelange 
That's correct.  Setting it to the full URL appears to have fixed it.   Thank you!

I didn't realize there was a template because I started the issue from the "reference in new issue" on a specific line in the schema_json.html which apparently ignores templates but I appreciate the feedback.
