### ISSUE TITLE
Request for Math Writing Support Feature

### ISSUE THREAD

**Issue by ichsanulamal** [adityatelange/hugo-PaperMod#1541]
Hi,

First, thank you for the fantastic work on the Hugo PaperMod theme. It's a great theme with a clean and elegant design, making it a pleasure to use.

I would like to request the addition of math writing support in the Hugo PaperMod theme. As someone who frequently writes technical content that involves mathematical equations and expressions, having built-in support for rendering math would be incredibly helpful.

### Additional Information:

https://gohugo.io/content-management/mathematics/

**Comment by XieWeikai** [comment]
I have the same demand

**Comment by ichsanulamal** [comment]
> I have the same demand

https://adityatelange.github.io/hugo-PaperMod/posts/math-typesetting/

**Comment by CalK16** [comment]
Hi, is there a specific reason for manually modifying the code for each user instead of incorporating changes into this repository?
