### ISSUE TITLE
[BUG] Cover image broken in non-production mode

### ISSUE THREAD

**Issue by weeix** [adityatelange/hugo-PaperMod#1559]
**Describe the bug**
The cover image link is broken (resulting in a HTTP 404 error) when using the theme in non-production mode.

 - Device/Os: Windows 11
 - Type: Desktop
 - Browser and version: Brave 1.68.128
 - Hugo Version: 0.128.1
 - Theme Version: 9ea3bb0e1f3aa06ed7715e73b5fabb36323f7267

**Steps to reproduce the behavior:**

1. Clone the example site: `git clone -b exampleSite https://github.com/adityatelange/hugo-PaperMod.git`
2. Inside the directory, run: `git submodule update --init --recursive`
3. In `config.yml`, remove the `env: production` line
4. Run: `hugo server`

**Expected behavior**:

The cover image should display as expected.

**Repo/Source where this issue can be reproduced**:

https://github.com/adityatelange/hugo-PaperMod.git (`exampleSite` branch)

**Screenshots**

![image](https://github.com/user-attachments/assets/760cf4b2-30d1-434a-9bfd-b7aa33d071e9)

**Additional context**

Changing this line in cover.html resolved the issue locally, but I'm unsure of potential side effects in other scenarios:

https://github.com/adityatelange/hugo-PaperMod/blob/9ea3bb0e1f3aa06ed7715e73b5fabb36323f7267/layouts/partials/cover.html#L29

Changed to:

```html
        <img loading="{{$loading}}" src="{{ $cover.Permalink }}" alt="{{ $alt }}">
```

**Comment by adityatelange** [comment]
Intended feature and not a bug

https://github.com/adityatelange/hugo-PaperMod/blob/9ea3bb0e1f3aa06ed7715e73b5fabb36323f7267/layouts/partials/cover.html#L19-L20

**Comment by weeix** [comment]
@adityatelange I thought your intention was to resize the image if the conditions are met or display it unchanged otherwise.

Additionally, the cover image URL would also break if the responsive cover images option is turned off:

```yaml
params:
  cover:
    responsiveImages: false
```
