### ISSUE TITLE
Add Config Option to Exclude Content from Search Index in PaperMod

### ISSUE THREAD

**Issue by zxcgz** [adityatelange/hugo-PaperMod#1562]
I'm using PaperMod for a blog with a large number of posts. The search functionality generates a very large `index.json` (about 200MB), causing a long download time and delaying search usability post-deployment.  I suggest adding a configurable option to exclude specific elements like `content` from `index.json`. This would help reduce the file size and improve search performance for large sites. It's a niche but very useful feature for content-heavy blogs.

**Comment by adityatelange** [comment]
we already have this

**Comment by adityatelange** [comment]
https://github.com/adityatelange/hugo-PaperMod/wiki/Variables#fuseopts

set keys to include only title and link

**Comment by zxcgz** [comment]
> https://github.com/adityatelange/hugo-PaperMod/wiki/Variables#fuseopts
> 
> set keys to include only title and link

I referred to the example and added the following configuration under
```
[params.fuseOpts]:
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1000
threshold = 0.4
minMatchCharLength = 0
keys = ["title"]
```
However, the index.json file used for search still contains the content field.

**Comment by zxcgz** [comment]
But when I modify the file in /layout/_default/index.json to the following:
```
{{- $.Scratch.Add "index" slice -}}
{{- range site.RegularPages -}}
{{- if and (not .Params.searchHidden) (ne .Layout archives) (ne .Layout search) }}
{{- $.Scratch.Add "index" (dict "title" .Title "permalink" .Permalink "summary" .Summary) -}}
{{- end }}
{{- end -}}
{{- $.Scratch.Get "index" | jsonify -}}
```
The index.json file used for search then no longer includes the content.

**Comment by zxcgz** [comment]
But when I modify the file in /layout/_default/index.json to the following:
```
{{- $.Scratch.Add "index" slice -}}
{{- range site.RegularPages -}}
{{- if and (not .Params.searchHidden) (ne .Layout archives) (ne .Layout search) }}
{{- $.Scratch.Add "index" (dict "title" .Title "permalink" .Permalink "summary" .Summary) -}}
{{- end }}
{{- end -}}
{{- $.Scratch.Get "index" | jsonify -}}
```
The index.json file used for search then no longer includes the content.

**Comment by adityatelange** [comment]
whichever way works for you the best
