### ISSUE TITLE
[Proposal] i18n supports in more places

### ISSUE THREAD

**Issue by MortalHappiness** [adityatelange/hugo-PaperMod#1567]
This is a proposal to add i18n supports in the following places:

1. `{{ $bc_pg.Name }}` -> `{{ i18n $bc_pg.Name | default $bc_pg.Name }}`
https://github.com/adityatelange/hugo-PaperMod/blob/9ea3bb0e1f3aa06ed7715e73b5fabb36323f7267/layouts/partials/breadcrumbs.html#L14

- URL: Any posts
- Before: 
![image](https://github.com/user-attachments/assets/84589b0e-3434-4626-bc6a-0ff3192ebe10)
- After:
![image](https://github.com/user-attachments/assets/517ae781-6d79-49ed-98b3-eb7aa1dfb013)

2. `{{ .Title }}` -> `{{ i18n .Title | default .Title }}`
https://github.com/adityatelange/hugo-PaperMod/blob/9ea3bb0e1f3aa06ed7715e73b5fabb36323f7267/layouts/partials/head.html#L11

- URL: `/zh-tw/posts/`
- Before:
![image](https://github.com/user-attachments/assets/33518a55-23fc-423f-b238-bcfa18c5b1ab)
- After:
![image](https://github.com/user-attachments/assets/2ecc0f99-f7c6-4861-add7-1e014b39724c)

3. `{{ .Title }}` -> `{{ i18n .Title | default .Title }}`
https://github.com/adityatelange/hugo-PaperMod/blob/9ea3bb0e1f3aa06ed7715e73b5fabb36323f7267/layouts/_default/list.html#L11

- URL: `/zh-tw/posts/`
- Before:
![image](https://github.com/user-attachments/assets/af651e75-78ed-46ce-b66a-1bb56b679b76)
- After:
![image](https://github.com/user-attachments/assets/3facc382-f2ee-45fd-abf0-8a9a5dd96e82)

4. `{{ .Title }}` -> `{{ i18n .Title | default .Title }}`
https://github.com/adityatelange/hugo-PaperMod/blob/9ea3bb0e1f3aa06ed7715e73b5fabb36323f7267/layouts/_default/terms.html#L5

- URL: `/zh-tw/tags/`
- Before:
![image](https://github.com/user-attachments/assets/3d45b936-b4dd-4a76-814a-33a4858b64aa)
- After:
![image](https://github.com/user-attachments/assets/2d5f53c7-92d6-4b3e-b3c8-ae4d462c45ed)

By using templates like `{{ i18n $variable | default $variable }}`, we don't need to add translations for all languages all at once.

Note: I can open a PR if this proposal is feasible.

**Comment by adityatelange** [comment]
The places you're referring to are user content/folder names and we cannot support i18n for that.
There are ways to set title of Tags Series and the section titles. You'll need to search it on internet.
