### ISSUE TITLE
[BUG] Google Search Console  can't crawl the sitemap.xml

### ISSUE THREAD

**Issue by heyzqq** [adityatelange/hugo-PaperMod#1568]
Hi, after using this theme, when I entered the `sitemap.xml` in Google Search Console, it shows **"Unable to fetch"**. Currently, in Google search results (keyword: `site:my.site.com`), only the homepage of the website is indexed. However, `bing.com` can index other pages.

- My website: my.site.com -> my.github.io
- Theme Version [e.g. v4.0, master, or commit-id ]: master

Is this a bug?
Thank you for your contribution and looking forward to your reply!

**Comment by adityatelange** [comment]
Thanks for your report, but we cannot address this issue with the information provided. Please note that without additional details, we won't be able to investigate further.

Thank you for your understanding.
