### ISSUE TITLE
[Enhancement]: Resize pictures in markdown

### ISSUE THREAD

**Issue by suiyuanla** [adityatelange/hugo-PaperMod#1577]
### What you'd like to propose?

When I add an image in Markdown, it centers, maintains its aspect ratio, and takes up the entire width of the article. This looks great most of the time. However, in cases where the image itself is small, it gets scaled up significantly, which looks awkward. I wish there was a way to adjust the image size, perhaps with something like `![alt text](/path/to/picture?width=400px&height=300px)`, while keeping the resized image centered on its own line. 

I have searched in the wiki and the repo, can't find the solution. Please excuse me if this feature is already implemented.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adityatelange** [comment]
centring is possible with
path/someimage.jpg#center

height, width is not possible as we're building statically.
