### ISSUE TITLE
[Enhancement]: Signal Social Icon

### ISSUE THREAD

**Issue by joshaustintech** [adityatelange/hugo-PaperMod#1583]
### What you'd like to propose?

Would love to see a social icon for [Signal](https://signal.org/), since we have usernames and groups and can share them via links.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jasonbraganza** [comment]
@joshaustintech, already there via PR #1446

**Comment by KhaaL** [comment]
@jasonbraganza @adityatelange the list of social icons should include signal: https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-icons/
