### ISSUE TITLE
[Enhancement]: Give the definition of "clean". Otherwise, remove it

### ISSUE THREAD

**Issue by ally9335** [adityatelange/hugo-PaperMod#1598]
### What you'd like to propose?

You claim that the theme is "clean". What makes it clean? Clean compared to what? Give me an example of a dirty theme then?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adityatelange** [comment]
Educate yourselves kid, I don't owe you the answer.
