### ISSUE TITLE
Does this theme support setting a google analytics tag? 

### ISSUE THREAD

**Issue by singhkays** [adityatelange/hugo-PaperMod#16]
Can you set a google analytics tag? Example here https://github.com/MunifTanjim/minimo/blob/master/exampleSite/config.toml#L9

**Comment by adityatelange** [comment]
It does support 
https://github.com/adityatelange/hugo-PaperMod/blob/d8199140e5940f02960196d1220c9a0ce8a23de1/layouts/partials/head.html#L51
read: https://gohugo.io/templates/internal/#configure-google-analytics

set env to `production` 
https://github.com/adityatelange/hugo-PaperMod/blob/d8199140e5940f02960196d1220c9a0ce8a23de1/layouts/partials/head.html#L50

**Comment by dipeshmnm** [comment]
Hi, as a layperson, I still can not figure out how and where to put the exact analytics codes.
