### ISSUE TITLE
[Enhancement]: Social Icon - Bluesky

### ISSUE THREAD

**Issue by ya4** [adityatelange/hugo-PaperMod#1614]
### What you'd like to propose?

[Bluesky](https://bsky.app) is growing rapidly and adding the icon in Social Icons would provide value to PaperMod users who are on Bluesky. The icon was added in simple-icons [recently](https://github.com/simple-icons/simple-icons/pull/8856).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Strubbl** [comment]
The icons is already part of the code and you can use it: https://github.com/adityatelange/hugo-PaperMod/blob/master/layouts/partials/svg.html#L71

**Comment by ya4** [comment]
Ooof, not sure how I missed that. Thanks!
