### ISSUE TITLE
[Bug]: HTML 输出未被正确解析的问题(Issue with HTML output not being parsed correctly)

### ISSUE THREAD

**Issue by Mini-Jelly** [adityatelange/hugo-PaperMod#1615]
### What happened?

Issue with HTML output not being parsed correctly
![2024-10-12_15-44-36](https://github.com/user-attachments/assets/064113cb-8928-4637-b6ff-61b0509b2a0c)

### Steps to reproduce

1.run cmd
```
hugo new site 123
cd 123
move D:\hugo.exe D:\123\
echo theme = 'hugo-PaperMod-7.0' >> hugo.toml
```

2.Put the downloaded theme into the folder `theme` in the `123` folder

3.Create some new articles

4.I asked ChatGPT how to solve it

on "themes\PaperMod\layouts\partials" Line 20
```
{{- delimit . "&nbsp;·&nbsp;" -}}      ------>     {{- safeHTML (delimit . " · ") -}}
``` 

> **ChatGPT**：In the last line of post_meta.html, wrap the result of delimit in the safeHTML function. This will ensure that the output HTML is parsed correctly.

**The result of this modification is that ChatGPT answered**

### Hugo Version

Hugo >= 0.112.4 (Recommended - Minimum version required for PaperMod)

### PaperMod Version

PaperMod v7.0

### What kind of devices are you seeing the problem on?

Desktop

### What browsers are you seeing the problem on?

Chrome

### Browser Version

Chorme 121.0.6167.185

### Relevant log output

```shell
D:\hugo>hugo --gc
Start building sites …
hugo v0.135.0-f30603c47f5205e30ef83c70419f57d7eb7175ab windows/amd64 BuildDate=2024-09-27T13:17:08Z VendorInfo=gohugoio

WARN  deprecated: .Site.Social was deprecated in Hugo v0.124.0 and will be removed in a future release. Use .Site.Params instead.

                   | EN
-------------------+------
  Pages            | 147
  Paginator pages  |  11
  Non-page files   |   0
  Static files     |   0
  Processed images |   0
  Aliases          |  42
  Cleaned          |   0

Total in 169 ms
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by Mini-Jelly** [comment]
hugo v0.135.0-f30603c47f5205e30ef83c70419f57d7eb7175ab windows/amd64 BuildDate=2024-09-27T13:17:08Z VendorInfo=gohugoio

**Comment by newptcai** [comment]
I had the same problem. Solved by update PaperMod via:

> git submodule update --remote
