### ISSUE TITLE
[Bug]: site config key paginate was deprecated

### ISSUE THREAD

**Issue by Strubbl** [adityatelange/hugo-PaperMod#1617]
### What happened?

got a warning during site creation:

`WARN  deprecated: site config key paginate was deprecated in Hugo v0.128.0 and will be removed in a future release. Use pagination.pagerSize instead.`

### Steps to reproduce

generate the site with hugo v0.135.0

### Hugo Version

Hugo >= 0.112.4 (Recommended - Minimum version required for PaperMod)

### PaperMod Version

a2eb47bb4b805116dcd34c1605d39835121f8dbe

### Relevant log output

```shell
$ hugo -s .
WARN  deprecated: site config key paginate was deprecated in Hugo v0.128.0 and will be removed in a future release. Use pagination.pagerSize instead.
Start building sites … 
hugo v0.135.0+extended linux/amd64 BuildDate=unknown
...
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DanielHermosilla** [comment]
I'm new to Hugo and the bug happened to me while following the [quickstart guide](https://gohugo.io/getting-started/quick-start/). Apparently the error is not associated with PaperMod but with Hugo itself (since the quickstart is within the Anekene theme)

**Comment by Strubbl** [comment]
Thank you, just replacing `paginate` in the config yaml with
```
pagination:
  pagerSize: 5
```
resolves this warning.
