### ISSUE TITLE
New Social SVG: Reddit & NuGet

### ISSUE THREAD

**Issue by bruno-garcia** [adityatelange/hugo-PaperMod#163]
Firstly thank you for much for putting the work on setting this up.

I'like to suggest 2 new social svgs:

[NuGet](https://upload.wikimedia.org/wikipedia/commons/2/25/NuGet_project_logo.svg)
And [Reddit](https://iconmonstr.com/reddit-4-svg/)

**Comment by joaopgrassi** [comment]
Maybe we could follow the same as in the footer and have a extended for `svg.html`? That way we could add extra icons without having to bloat the theme.

**Comment by adityatelange** [comment]
> Maybe we could follow the same as in the footer and have a extended for `svg.html`? That way we could add extra icons without having to bloat the theme or duplicate the entire file.

Good idea, I'll look into it if we can do that :D

**Comment by bruno-garcia** [comment]
Looks great:
![image](https://user-images.githubusercontent.com/1633368/103423374-39074780-4b74-11eb-93d1-1ffa18ee5c84.png)


Thanks @adityatelange for adding it so quickly!

**Comment by michael0liver** [comment]
> > Maybe we could follow the same as in the footer and have a extended for `svg.html`? That way we could add extra icons without having to bloat the theme or duplicate the entire file.
> 
> Good idea, I'll look into it if we can do that :D

I have seen something similar in another theme, user could add SVGs to a toml file then reference the name. https://github.com/reuixiy/hugo-theme-meme/blob/master/data/SVG.toml

**Comment by joaopgrassi** [comment]
Yes, I think having the icons using `data` files is better. In `social_icons.html` we have the icons the user wants to use, then it's just a matter of finding them in the `data` file and rendering. This would also remove the need for all the `if/elses` inside `svg.html`.

**Comment by adityatelange** [comment]
> Yes, I think having the icons using `data` files is better. In `social_icons.html` we have the icons the user wants to use, then it's just a matter of finding them in the `data` file and rendering. This would also remove the need for all the `if/elses` inside `svg.html`.

Yes you are correct, but the svgs in papermod are quite longer in size, it may not be a good idea to have a very long string !
So, as of now I would like to keep this as it is :)
