### ISSUE TITLE
[Bug]: CSS files not loading in deployment over github pages

### ISSUE THREAD

**Issue by Illucious** [adityatelange/hugo-PaperMod#1645]
### What happened?

I built the site and deployed it on GitHub pages at [https://illucious.github.io/](https://illucious.github.io/) and the page is loading without any CSS.
I went to the browser console and here's what it said
`illucious.github.io/:1 Failed to find a valid digest in the 'integrity' attribute for resource 'https://illucious.github.io/assets/css/stylesheet.d72444526d7ecbdb0015438a7fa89054a658bf759d0542e2e5df81ce94b493ee.css' with computed SHA-256 integrity '1vzSCk+4bvpN+sjsldpgJEzIhxBCGD2h7yjjp2Ktecg='. The resource has been blocked.`

### Steps to reproduce

1. Go to the browser console of the website

### Hugo Version

Hugo >= 0.125.7 (Recommended - Minimum version required for PaperMod)

### PaperMod Version

PaperMod V0.8

### Browser Version

 Version 1.73.97 Chromium: 131.0.6778.108 (Official Build) (64-bit)

### Relevant log output

```shell
illucious.github.io/:1 Failed to find a valid digest in the 'integrity' attribute for resource 'https://illucious.github.io/assets/css/stylesheet.d72444526d7ecbdb0015438a7fa89054a658bf759d0542e2e5df81ce94b493ee.css' with computed SHA-256 integrity '1vzSCk+4bvpN+sjsldpgJEzIhxBCGD2h7yjjp2Ktecg='. The resource has been blocked.
```

### Repository/Source Code link where this issue can be reproduced

https://github.com/Illucious/illucious.github.io

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adityatelange** [comment]
https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#failed-to-find-a-valid-digest-in-the-integrity-attribute-for-resource--

**Comment by Illucious** [comment]
thanks, it's fixed

> https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#failed-to-find-a-valid-digest-in-the-integrity-attribute-for-resource--
