### ISSUE TITLE
CSS Grid Layout for Posts Instead of Stacking 

### ISSUE THREAD

**Issue by thedivtagguy** [adityatelange/hugo-PaperMod#167]
I'm trying to get a grid layout on the my Hugo homepage instead of the current stacked version. The posts should appear in a 3 column grid instead of the one on top of the other. To start with, I've wrapped the <article> tag in list.html in a `<div class = "container">`:
```
<div class="container">

<article class="{{ $class }}">
  {{- $isHidden := (.Site.Params.cover.hidden | default .Site.Params.cover.hiddenInList)}}
  {{- partial "cover.html" (dict "cxt" . "IsHome" true "isHidden" $isHidden) }}
  <header class="entry-header">
    <h2>
      {{ .Title }}
      {{- if .Draft }}<div class="entry-isdraft"><sup>&nbsp;&nbsp;[draft]</sup></div>{{- end }}
    </h2>
  </header>
  {{- if (ne .Site.Params.hideSummary true)}}
  <section class="entry-content">
    <p>{{ .Summary | plainify | htmlUnescape }}...</p>
  </section>
  {{- end }}
  <footer class="entry-footer">
    {{- partial "post_meta.html" . -}}
  </footer>
  <a class="entry-link" aria-label="post link to {{ .Title | plainify }}" href="{{ .Permalink }}"></a>
</article>
{{- end }}
</div>
```
I looked through the theme's CSS files and I can see that the cards for the posts are styled by post-entry. Combined, I've added this CSS to the post-entry.css:

```
.container {
  display: grid;
   grid-template-columns: 1fr 1fr 1fr;  
   grid-gap: 10px;
}


.post-entry {
    margin-bottom: var(--gap);
    padding: var(--gap);
    background: var(--entry);
    border-radius: var(--radius);
    transition: transform .1s;
    position: relative;
}

```
I think this is what it is supposed to be. But this clearly does not work. For some reason, the grid is not adding the fourth post to a new row but just adding a new column. They are not side by side as expected but still stacked: See the image here:

![image](https://user-images.githubusercontent.com/6006888/103459951-8d5b2480-4d38-11eb-81b9-ffc6eb8d143f.png)

**I think what is happening is that  the `.container` is being added for each post (like in a for loop), not over the actually containing element. Where is the `div` where I can apply container to?** I can't find an index.html so I'm adding it to `list.html` right now.

My repo is hosted here: https://github.com/thedivtagguy/archives if this is more helpful.

A live deploy is here: https://jolly-panini-82258b.netlify.app/

**Comment by adityatelange** [comment]
Sorry but this is out of scope.You may modify according to your liking, but customization and guidance isn't provided here. 
Hope you understand.
