### ISSUE TITLE
Accessibilty: Contrast between post-entry and background to low

### ISSUE THREAD

**Issue by lu4p** [adityatelange/hugo-PaperMod#169]
A friend of mine, whom I showed my blog to, didn't find it immediately obvious, that the excerpts on the home page can be clicked, he attributed this to low contrast between the background and the "boxes". 

![Screenshot](https://user-images.githubusercontent.com/46541492/104108330-f35d2400-52c3-11eb-9c07-2c4ebf70f31a.png)

This only applies to the "light" theme as far as I can tell. The obvious  solution would be to make the background a touch darker.

I can of course fix this myself by overriding the theme, but possibly this is more common and other people might also benefit from this.

**Comment by adityatelange** [comment]
The low contrast maybe can be improved by setting just a darker shade, but in my opinion this is very much about the perspective.

Also [Light House Report for Homepae](https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fadityatelange.github.io%2Fhugo-PaperMod%2F) does not mention any accessibility issue though, usually in these cases they show up with [Background and foreground colors do not have a sufficient contrast ratio](https://web.dev/color-contrast/)

This can also be a thing when using laptops (as I have also experienced) when the screen angle isn't good so we see stuff like this not to look good. 

Github also uses a lower gray shade #f6f8fa but with a border around elements to be distinguishable, but maybe that's contradicts papermod's design pov.

**Comment by lu4p** [comment]
What about using a shadow effect to add more depth?

**Comment by adityatelange** [comment]
> What about using a shadow effect to add more depth?

I'm thinking of providing an optional border to cards

**Comment by lu4p** [comment]
Looks good :+1:
