### ISSUE TITLE
Release plan with versioning instead of regular commits to master

### ISSUE THREAD

**Issue by piyushpaliwal** [adityatelange/hugo-PaperMod#174]
Hi @adityatelange, I notice that you are actively working on fixing issues and enabling new features for the theme, which is amazing! 
The only challenge is with the people who are using this theme. We have to regularly keep our remote theme in sync irrespective of any content changes.
For ex, I updated the theme folder a few days ago only to realize that there are already new commits available for me to pull.

Can you maybe put in a strategy with proper versioning and a release plan for maybe fortnightly or something? Thinking out loud :)

**Comment by adityatelange** [comment]
@piyushpaliwal I think everyone using this theme is free to update their copy of theme whenever they want it to according to their comfort.

I do the stuff in my free time and do not plan to dedicate specific time or schedule for it, it is what it is. 
It is not easy for me to plan schedule and deliver a Free software (which is just a add-on theme), all alone.

Hope you understand :)

**Comment by piyushpaliwal** [comment]
@adityatelange I completely understand and am with you on it. I am not saying to get on a schedule (like I said, was just thinking out loud) but to get this theme much more organized coz its really good!

If you have proper changelog and versioning, its really beneficial for everyone. With this, you can still continue to work on the theme in your free time and when you know that there have been enough commits for a release, you go ahead and tag/bump it as a major or minor version. Just like any other development project.

**Comment by adityatelange** [comment]
We already have proper changelog and versioning imo. The only difference is there are no point releases. And yes I know when we have to release, you may follow the release tags instead of 'master' branch !
https://github.com/adityatelange/hugo-PaperMod/releases

**Comment by piyushpaliwal** [comment]
Ok
