### ISSUE TITLE
Google Analytics Integration

### ISSUE THREAD

**Issue by koti** [adityatelange/hugo-PaperMod#178]
Hey, I was wondering how easy it is to integrate Google Analytics on your website. I followed this guide here: http://cloudywithachanceofdevops.com/posts/2018/05/17/setting-up-google-analytics-on-hugo/. 

I added my Google Analytics Tracking ID into the config.toml file and additionally moved my header page into the hugo/layouts/partials/header.html. It doesn't really seem to be working.

Could you please provide some documentation on Integrating Google Analytics to the website?

**Comment by adityatelange** [comment]
@koti It's easy, hugo provides a simple way.
Read https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-installation/#sample-configyml

Put your Analytics id as shown in sample config.

**Comment by koti** [comment]
@adityatelange Thank you very much for your comment. Although I did both, nothing seems to be working yet. I'll do some troubleshooting, and I'll reach out back to you if the problem is not resolved.

**Comment by koti** [comment]
Update on my latest comment turns out that I didn't attach the provided script from Google Analytics at the ```head.html``` file. After I attached it, everything seemed to be working perfectly.
