### ISSUE TITLE
Make some page settings configurable from site config

### ISSUE THREAD

**Issue by fkohrt** [adityatelange/hugo-PaperMod#181]
I suggest making some page settings (`showtoc`, `tocopen`, `hidemeta`) configurable from the site config. This is already the case for `comments`:

https://github.com/adityatelange/hugo-PaperMod/blob/946cc1ffe35dbf5fcac4f5e2a636592110953610/layouts/_default/single.html#L64-L66

But the Hugo docs suggest that there's an easier way to achieve this: Just replacing [`.Params`](https://gohugo.io/variables/page/#page-level-params) by [`.Param`](https://gohugo.io/functions/param/) in the following code:

https://github.com/adityatelange/hugo-PaperMod/blob/946cc1ffe35dbf5fcac4f5e2a636592110953610/layouts/_default/single.html#L36-L47

**Comment by adityatelange** [comment]
Sure. That seems neat.
Interested in a PR ?

**Comment by fkohrt** [comment]
Done in #182
