### ISSUE TITLE
[Feature] Additional emphasis on blockquotes/ [discussion on custom.css]

### ISSUE THREAD

**Issue by singhkays** [adityatelange/hugo-PaperMod#19]
Often when you are quoting another article, you want to add additional emphasis on the quote. I like that there's a left border. But I have some more ideas that might help the blockquote text stand out

## Italic style
![image](https://user-images.githubusercontent.com/6164178/95008899-90783480-05d2-11eb-9904-9e163e32443d.png)

## Italic + serif font like Medium
![image](https://user-images.githubusercontent.com/6164178/95008920-a8e84f00-05d2-11eb-9e04-f59f05c4254e.png)

##  yellow background like Stratechery
![image](https://user-images.githubusercontent.com/6164178/95008767-adf8ce80-05d1-11eb-8e8e-4d08ca5c0042.png)

**Comment by adityatelange** [comment]
pull requests are welcome

**Comment by singhkays** [comment]
I don't know much about Go templates but I can take a crack at this by editing the default CSS. Does this theme also support custom css? I searched but couldn't find a reference to custom_css in the source code.

**Comment by adityatelange** [comment]
To keep it fast and performing the stuff like custom fonts and color gradings are not considered as a value to theme as it may make it slower as more resources are consumed

**Comment by singhkays** [comment]
makes sense to be the default but assuming I'm OK with the perf hit, what's the best way to make my style choices for my blog? I suppose other users of this theme would be in the same boat and would want to customize the look and feel of their blogs based on this theme.

**Comment by adityatelange** [comment]
> makes sense to be the default but assuming I'm OK with the perf hit, what's the best way to make my style choices for my blog? I suppose other users of this theme would be in the same boat and would want to customize the look and feel of their blogs based on this theme.

People using this theme are the one's who liked the minimalisim, dual-toned clean factor nature of [hugo -paper](https://github.com/nanxiaobei/hugo-paper) but miss customization features which helps them increase the functionality and accessibility 

The theme you're currently using (https://github.com/MunifTanjim/minimo/) is great as far as colors and features are a concern. Kudos for thier great work

**Comment by adityatelange** [comment]
> suppose other users of this theme would be in the same boat and would want to customize the look and feel of their blogs based on this theme.

checkout these 
https://theclonker.de/
https://brunoluiz.net/
https://raphaelgosteli.com/
https://veruu.github.io/
https://y2kappa.github.io/blog/

**Comment by singhkays** [comment]
> > suppose other users of this theme would be in the same boat and would want to customize the look and feel of their blogs based on this theme.
> 
> checkout these
> https://theclonker.de/
> https://brunoluiz.net/
> https://raphaelgosteli.com/
> https://veruu.github.io/
> https://y2kappa.github.io/blog/

Those look exactly the same as default. I hear you and as the theme author you have every right to make the default minimalistic choices for your users. However, hugo provides a way for users to customize their site using the custom.css file. Are you open to allow user customization in this way so that users who care about customizing their blogs can do so?

**Comment by adityatelange** [comment]
I had custom.css included earlier see this commit: https://github.com/adityatelange/hugo-PaperMod/commit/a22aa8aac37d848dfb27007fe158d87c4dd2446b


Reason being you can always override any `asset` or `layout` from the theme 
read here: https://gohugobrasil.netlify.app/themes/customizing/#override-template-files
and here: https://gohugo.io/hugo-modules/theme-components/

Also as papermod does not have any nodejs dependencies you're good to go just by editing the css and/or the template, just like that.

**Comment by adityatelange** [comment]
@singhkays check this out https://github.com/adityatelange/hugo-PaperMod/commit/b56f6dc774f57e712077f2302d0f2198d7d3fa6b

**Comment by singhkays** [comment]
@singhkays custom.css looks good in the commit. I'm not a web-dev so let me make sure I get this right:

1. Your branch custom-css includes an example of how to edit the head.html
2. I can use this head.html to override the default theme template using the Hugo doc link you shared above
3. Should I include the custom.css file in the theme's assets directory or the hugo blog's `static/css` directory?
4. I don't completely understand the minification comment. Are you saying custom css file will always be excluded from minification or if I include in the assets directory then it will be minified?
