### ISSUE TITLE
UX of Back Operation

### ISSUE THREAD

**Issue by QuarticCat** [adityatelange/hugo-PaperMod#196]
On article pages, if I click a header and then go back, I will direct go back to list pages. This is quite counterintuitive. Usually, I would expect that I go back to the position before navigating. For example:
- https://rust-lang.github.io/api-guidelines/interoperability.html
- https://docs.python.org/3/whatsnew/3.9.html
- https://vuejs.org/v2/guide/index.html

Also, on the search page, if I click a search result and then go back, the search results will just disappear. I hope they can stay there for a quicker next click.

**Comment by adityatelange** [comment]
> Also, on the search page, if I click a search result and then go back, the search results will just disappear. I hope they can stay there for a quicker next click.

Yes, it isn't complete yet, idk when I'll push it but it is on pipeline.
