### ISSUE TITLE
Images not center aligned with custom shortcode

### ISSUE THREAD

**Issue by singhkays** [adityatelange/hugo-PaperMod#20]
On my existing theme the custom `figure` shortcode below can center align images with the following usage

`{{< figure src="./media/rss-icon.png" caption="RSS Icon" alt="RSS Icon" align="center" width="100">}}`

Here's the HTML produced
```html
<div style="text-align: center;">
<figure>
    <img src="./media/rss-icon.png" alt="RSS Icon" width="100"> <figcaption>
            <small><i>RSS Icon</i></small>
        </figcaption>
</figure>
</div>
```

You can see this in action on my blog - https://www.singhkays.com/blog/how-spotify-is-killing-the-open-podcast-ecosystem/

but with the PaperMod theme, I get the following
![image](https://user-images.githubusercontent.com/6164178/95009235-45abec00-05d5-11eb-9e16-eda07d342905.png)

**Comment by adityatelange** [comment]
@singhkays can you share the custom short-code ?

**Comment by singhkays** [comment]
Sure. This gist (https://gist.github.com/cpbotha/deb310eed14308fe26f7b7d0fabeb34d)  from the below article 

https://cpbotha.net/2020/05/02/drop-in-replacement-for-hugo-figure-shortcode-with-img-srcset-support/

**Comment by adityatelange** [comment]
> Sure. This gist (https://gist.github.com/cpbotha/deb310eed14308fe26f7b7d0fabeb34d) from the below article
> 
> https://cpbotha.net/2020/05/02/drop-in-replacement-for-hugo-figure-shortcode-with-img-srcset-support/

The mentioned shortcode does not set alignment attribute to the image, hence doesn't match expected output :)
