### ISSUE TITLE
Theme toggle button inaccessible from keyboard

### ISSUE THREAD

**Issue by fkohrt** [adityatelange/hugo-PaperMod#204]
The link `#theme-toggle` is inaccessible (as in: [accessibility](https://www.a11yproject.com/)) for the following reasons.

1. It can't be reached by tabbing through the site
2. It can't be triggered by pressing enter

I suggest a solution along the following lines:

1. Add `tabindex="0"` to allow it being reached through tabbing
2. Add an `onkeypress` handler that triggers a theme toggle if the enter key is pressed

**Comment by adityatelange** [comment]
Can you try using `button` instead of `a` in code snippet below
https://github.com/adityatelange/hugo-PaperMod/blob/778ee39137dc69e8761c73af7a731ffc51854397/layouts/partials/header.html#L63-L82

**Comment by fkohrt** [comment]
That works! Only the spacing and stroke color need adjustment now:

![adjustment](https://user-images.githubusercontent.com/12914806/106273893-aa99ea80-6233-11eb-86a1-28f74ce90da8.png)

**Comment by adityatelange** [comment]
why would that not work? Did you try to find the reason ?
Svg uses currentColor to fill in !

**Comment by fkohrt** [comment]
There's no color assignment for buttons in here:

https://github.com/adityatelange/hugo-PaperMod/blob/789b1f824c61a4d9fd069aba92d2891a1c2375fc/assets/css/reset.css#L11-L20

And horizontal spacing for buttons needs to be added here:

https://github.com/adityatelange/hugo-PaperMod/blob/dc743ae5e20f9f367b9f186fc9e97a516a0c5cf9/assets/css/header.css#L25-L29

But there's also a slight vertical shift when going from `a` to `button` and I can't figure out why.
