### ISSUE TITLE
Make theme forestry.io friendly

### ISSUE THREAD

**Issue by ibragimof** [adityatelange/hugo-PaperMod#205]
Can anyone set all frontmatter params in forestry, so we can use this theme in cloud cms?

**Comment by adityatelange** [comment]
I've never used CMS for hugo.
PRs are welcome to improve CMS support as well as documentation for this to work

**Comment by kdkasad** [comment]
I may be wrong but I think they're just asking for someone to go into Forestry.io and manually create a configuration template with all the options for this theme.

**Comment by adityatelange** [comment]
> I may be wrong but I think they're just asking for someone to go into Forestry.io and manually create a configuration template with all the options for this theme.

Oh so anyone interested may do it, maybe this should be a discussion and not an issue

**Comment by kdkasad** [comment]
I agree. It's not really an issue, since it works fine in forestry.io
currently. (I know because I've done it).

**Comment by ibragimof** [comment]
> I've done it

Can you give some guides how to do that please? Parameters in template lost after installation in forestry....

**Comment by kdkasad** [comment]
I don't have any guides/tips. All I did was set the relevant configuration options in `config.yml`, then when I imported the Git repo into Forestry, it populated configuration menu (under the **Configuration** tab in the sidebar).
