### ISSUE TITLE
Crazy Syntax Highlighting when using R and Blogdown

### ISSUE THREAD

**Issue by baggiponte** [adityatelange/hugo-PaperMod#206]
Hello and thank you for the amazing theme!

I used R and the package `blogdown` to create a couple of blogs using Hugo and PapeMod. What I noticed, though, is that syntax highlighting behaves unpredictably, always changing its colours, as you can see [here](https://louisville-dockless-vehicles.rbind.io/post/2021-01-13-model-1-multinomial-logistic-regression/).

I also tried `Chroma` syntax highlighter, but it does not work at all, as you can see [here](https://coding-corner.netlify.app/post/covid-19-vaccinations-italy/).

Anyone has a suggestion?

Thank you!

**Comment by kdkasad** [comment]
Can you share the markdown source for the page(s)? It might help figure out the problem.

**Comment by adityatelange** [comment]
@baggiponte Have you read this ?
https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma

**Comment by baggiponte** [comment]
> Can you share the markdown source for the page(s)? It might help figure out the problem.

Hello @kdkasad, sure! It's just a plain `.Rmd` file. I attached it here, also you can find everything in my [repo](https://github.com/baggiponte/coding-corner).

---

Dear @adityatelange, thank you for your prompt answer and I'm sorry for being confused. 

> I didn't get it, what do you mean by?
> 
> > What I noticed, though, is that syntax highlighting behaves unpredictably, always changing its colours,

What I meant was that syntax highlighting is extremely inconsistent: sometimes even within the same code chunks. Here, for example, `select()` and `inner_join()` are functions highlighted in yellow, whereas `rename()` isn't, although it's a function too. The last `select()` is not highlighted at all and the line immediately above it is messed up.

![Screenshot 2021-01-28 at 13 22 59](https://user-images.githubusercontent.com/57922983/106138251-2c264580-616c-11eb-8503-9c590500e97f.png)

> @baggiponte Have you read this?
> https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma

Yes! I made sure to try it out, but it did not work. My guess is that `blogdown` only supports `highlight.js`: I could not figure out much more than this [from the documentation](https://bookdown.org/yihui/blogdown/templates.html#how-to).

By the way: I do not want to sound arrogant or expect you to fix this, at all. I was wondering if you had any idea. My guess is simply that PaperMod is not wholly compatible with `blogdown` (perhaps, @yihui might have something to say about it).

**Comment by adityatelange** [comment]
@baggiponte PaperMod is using the [default hljs package (1st one in the list)](https://cdnjs.com/libraries/highlight.js/10.2.1) with some languages, this may not have the language you are using, I am not quite sure. I am planning to remove highlight.js from theme but it has some glitches here and there.

You may download customized package from their website here: https://highlightjs.org/download/ and paste it at `assets/js/highlight.min.js` so that it replaces the theme's js file. Let me knoe if that works

**Comment by fkohrt** [comment]
@baggiponte As `blogdown` uses Pandoc, you could also `disableHLJS: true` and add [Pandoc's css](https://stackoverflow.com/a/62778531) to `assets/css/extended`.

**Comment by hfshr** [comment]
Hi @baggiponte, I've been playing around with `blogdown` and PaperMod and found that if you use .Rmarkdown instead of .Rmd  for your posts, the syntax highlighting is much better. This post https://www.r-bloggers.com/2020/05/syntax-highlighting-in-blogdown-a-very-specific-solution/ gives a good overview, with the main point being: 

> Turns out that each format is rendered to HTML through different converters. Rmarkdown uses something called Blackfriday and Rmd uses Pandoc. As I understanding then Rmd is rendered by R and Rmarkdown is rendered by Hugo and so posts need to be rendered by Hugo in order for all the configs in the .toml file to apply.

Hope that helps!

**Comment by fkohrt** [comment]
> > Rmarkdown uses something called Blackfriday and Rmd uses Pandoc.

@hfshr [Since 2019](https://gohugo.io/news/0.60.0-relnotes/) Hugo uses Goldmark instead of Blackfriday by default. Also, when choosing `.Rmarkdown` as extension you won't be able to use [bookdown's markdown extensions](https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html).

**Comment by hfshr** [comment]
Ah thanks @fkohrt, good to know.

**Comment by baggiponte** [comment]
> Hi @baggiponte, I've been playing around with `blogdown` and PaperMod and found that if you use .Rmarkdown instead of .Rmd for your posts, the syntax highlighting is much better. This post https://www.r-bloggers.com/2020/05/syntax-highlighting-in-blogdown-a-very-specific-solution/ gives a good overview, with the main point being:
> 
> > Turns out that each format is rendered to HTML through different converters. Rmarkdown uses something called Blackfriday and Rmd uses Pandoc. As I understanding then Rmd is rendered by R and Rmarkdown is rendered by Hugo and so posts need to be rendered by Hugo in order for all the configs in the .toml file to apply.
> 
> Hope that helps!

Hi @hfshr! I tried replacing `.Rmd` with `.Rmarkdown`: highlighting works, but then no code output such as plot is displayed (I made a test [here](https://coding-corner.netlify.app/post/2021-01-31-test/)). Perhaps this is due to the shift to Goldmark, as  @fkohrt was referring to?

---

@adityatelange I'll try to download highlight.js, but from the download page, R is included among the Common languages: if you picked those, then I'd say highlighting should work.

---

> @baggiponte As `blogdown` uses Pandoc, you could also `disableHLJS: true` and add [Pandoc's css](https://stackoverflow.com/a/62778531) to `assets/css/extended`.

I'll give a shot at this! From what I understand from the answer in Stackoverflow, I only have to generate the .css file, save it and put it into the `/assets/css/` directory, right?

I am also trying to `disableHLJS:true` and see if `.Rmarkdown` + `Chroma` works.

Thank you all for the support. You guys are amazing!

**Comment by baggiponte** [comment]
> Hi @baggiponte, I've been playing around with `blogdown` and PaperMod and found that if you use .Rmarkdown instead of .Rmd for your posts, the syntax highlighting is much better. This post https://www.r-bloggers.com/2020/05/syntax-highlighting-in-blogdown-a-very-specific-solution/ gives a good overview, with the main point being:
> 
> > Turns out that each format is rendered to HTML through different converters. Rmarkdown uses something called Blackfriday and Rmd uses Pandoc. As I understanding then Rmd is rendered by R and Rmarkdown is rendered by Hugo and so posts need to be rendered by Hugo in order for all the configs in the .toml file to apply.
> 
> Hope that helps!

Hi @hfshr! I tried replacing `.Rmd` with `.Rmarkdown`: highlighting works, but then no code output such as plot is displayed (I made a test [here](https://coding-corner.netlify.app/post/2021-01-31-test/)). Perhaps this is due to the shift to Goldmark, as  @fkohrt was referring to?

---

@adityatelange I'll try to download highlight.js, but from the download page, R is included among the Common languages: if you picked those, then I'd say highlighting should work.

---

> @baggiponte As `blogdown` uses Pandoc, you could also `disableHLJS: true` and add [Pandoc's css](https://stackoverflow.com/a/62778531) to `assets/css/extended`.

I'll give a shot at this! From what I understand from the answer in Stackoverflow, I only have to generate the 

I am also trying to `disableHLJS:true` and see if `.Rmarkdown` + `Chroma` works

**Comment by hfshr** [comment]
@baggiponte After a bit more digging, I found you can add the following to your config.yaml in order to get the outputs displaying with .Rmarkdown

```
markup:
    goldmark:
        renderer:
             unsafe: true
```
This might not be the best solution though!

Reference: https://hugodown.r-lib.org/articles/config.html#hugo

**Comment by fkohrt** [comment]
> I'll give a shot at this! From what I understand from the answer in Stackoverflow, I only have to generate the .css file, save it and put it into the `/assets/css/` directory, right?

@baggiponte The directory is `assets/css/extended/` (see PaperMod's FAQ: [Bundling Custom css with theme’s assets](https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-faq/#bundling-custom-css-with-themes-assets)), but you are correct on the rest! Don't forget to `disableHLJS: true` when you do this.

**Comment by adityatelange** [comment]
I think this is solved. Closing
