### ISSUE TITLE
Content not visible in profile mode

### ISSUE THREAD

**Issue by tabishimran** [adityatelange/hugo-PaperMod#21]
Hey, Firstly, love the theme, super clean, very minimal, kudos!

Is it possible to get the content to appear while using paper-mod in profile mode?
I created a test post that appears on the site when I switch to Home-Info mode.
I was going for a blog that looks like the image you posted in your examples.
https://i.ibb.co/K0HVPBd/paper-mod-profilemode.png

But I can't get the posts to appear while using the theme on profile mode.

**Comment by adityatelange** [comment]
Glad you like it, don't forget to star it ;)
---
all posts will be available in /posts/

in profile mode you need to add a link to all posts by creating a button or a link in menu 

here is example : https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite

and https://adityatelange.github.io/hugo-PaperMod/ is it's output

**Comment by tabishimran** [comment]
Got it, thanks!
Of course, you get a well-deserved star! 👍 🎉
