### ISSUE TITLE
Enable Yandex.Metrica as an alternative to Google Analytics

### ISSUE THREAD

**Issue by Jarmos-san** [adityatelange/hugo-PaperMod#210]
Google Analytics integration is great but it's a bit too much for most small scale blogging needs. That's where [Yandex.Metrica](https://metrica.yandex.com/) comes in. It's simple & minimalistic UI is a great alternative to Google Analytics. So, it would be nice to have that as an alternative integrations as well. 😄 

I'm no frontend developer mastermind so I'm not sure how to implement it myself. But if it helps, here's an example snippet you would've to integrate within either the `<head>`/`<body>` tags:

```html
<!-- Yandex.Metrika counter -->
<script type="text/javascript" >
   (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
   m[i].l=1*new Date();k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
   (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");

   ym(<CODE-PROVIDED-BY-YANDEX.METRICA>, "init", {
        clickmap:true,
        trackLinks:true,
        accurateTrackBounce:true
   });
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/<CODE-PROVIDED-BY-YANDEX.METRICA>" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->
```

**Comment by adityatelange** [comment]
You can add paste this snippet of code in `extended_head` using

**Comment by Jarmos-san** [comment]
Makes sense.
> You can add paste this snippet of code in extended_head using
https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#custom-head--footer

Closing it then.
