### ISSUE TITLE
image with target="_blank"

### ISSUE THREAD

**Issue by Jippay** [adityatelange/hugo-PaperMod#213]
Hello,
is it possible to add the _target="_blank"_ function to images in posts , like the cover ?

Thank you :)

**Comment by adityatelange** [comment]
Hugo's Figure Shortcode is what you want 
https://gohugo.io/content-management/shortcodes/#figure

**Comment by Jippay** [comment]
That's exactly it! Thank you!

**Comment by killarbyte** [comment]
Ty bro
