### ISSUE TITLE
How to enable inline HTML?

### ISSUE THREAD

**Issue by joelouthan** [adityatelange/hugo-PaperMod#215]
How do I enable inline HTML?

For example:
```
<div style="font-variant: small-caps;">
foobar
</div>
```

In my Markdown editor and other Hugo themes, it appears fine.

But in PaperMod, it's completely gone.

Repo: https://github.com/joelouthan/theologic.us/tree/staging

**Comment by kdkasad** [comment]
See the `unsafe` option in the **Goldmark** section: https://gohugo.io/getting-started/configuration-markup/#goldmark

Please check Hugo docs before opening issues.
