### ISSUE TITLE
Copyright option in config.yaml is unused

### ISSUE THREAD

**Issue by kdkasad** [adityatelange/hugo-PaperMod#22]
It would be great if there was a way to use copyright defined in the configuration file in the footer.

Currently, I can set a copyright in `config.yaml`:
```
copyright: "&copy; 2020 Some Organization"
```
But it doesn't have any effect on the resulting page(s).

I don't necessarily want the copyright note in the footer to reference my site's title.

**Comment by adityatelange** [comment]
Hello @kdkasad, thank you for contacting me over email for your theme `hugo-plains`, as both of themes are based on hugo-paper, we are already diverged, however you are welcome for more contibutions to this theme.
Thank you :)
