### ISSUE TITLE
How to enable Math Typesetting in PaperMod?

### ISSUE THREAD

**Issue by GAGANsinghmsitece** [adityatelange/hugo-PaperMod#236]
According to docs, i created a partial called `math.html` with following content,

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/katex.min.css" integrity="sha384-AfEj0r4/OFrOo5t7NnNe46zW/tFgW6x/bCJG8FqQCEo3+Aro6EYUG4+cU+KJWu/X" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/katex.min.js" integrity="sha384-g7c+Jr9ZivxKLnZTDUhnkOnsh30B4H0rpLUpJ4jAIKs4fnJI+sEnkvrMWph2EDg4" crossorigin="anonymous"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/contrib/auto-render.min.js" integrity="sha384-mll67QQFJfxn0IYznZYonOWZ644AWYC+Pt2cHqMaRhXVrursRwvLnLaebdGIlYNa" crossorigin="anonymous"
    onload="renderMathInElement(document.body);"></script>
Then i included `math.html` in layouts/default/single.html  using
 
    {{ if or .Params.math .Site.Params.math }}
    {{ partial "math.html" . }}
    {{ end }}

When i checked only `katex.min.js` and `auto-render.min.js` get loaded while katex.min.css is not loaded. How can I correct this error?

**Comment by kdkasad** [comment]
Are there any errors in the console when loading the page?

**Comment by GAGANsinghmsitece** [comment]
There is no error in console. I will deploy that page so that you can check it

**Comment by adityatelange** [comment]
> Then i included `math.html` in layouts/default/single.html using

You can directly add [Auto-render scripts](https://katex.org/docs/autorender.html#usage) in [extended_head.html](https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-faq/#custom-head--footer)
like for example

```html
{{ if or .Params.math .Site.Params.math }}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/katex.min.css" integrity="sha384-AfEj0r4/OFrOo5t7NnNe46zW/tFgW6x/bCJG8FqQCEo3+Aro6EYUG4+cU+KJWu/X" crossorigin="anonymous">
<script defer src="https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/katex.min.js" integrity="sha384-g7c+Jr9ZivxKLnZTDUhnkOnsh30B4H0rpLUpJ4jAIKs4fnJI+sEnkvrMWph2EDg4" crossorigin="anonymous"></script>
<script defer src="https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/contrib/auto-render.min.js" integrity="sha384-mll67QQFJfxn0IYznZYonOWZ644AWYC+Pt2cHqMaRhXVrursRwvLnLaebdGIlYNa" crossorigin="anonymous"
    onload="renderMathInElement(document.body);"></script>
{{ end }}
```

**Comment by GAGANsinghmsitece** [comment]
Thanks it solved the issue

**Comment by kopytjuk** [comment]
In case someone has an issue with inline math, pass the x to the `renderMathInElement` call:

```
...
    onload="renderMathInElement(document.body, 
    {
              delimiters: [
                  {left: '$$', right: '$$', display: true},
                  {left: '\\[', right: '\\]', display: true},
                  {left: '$', right: '$', display: false},
                  {left: '\\(', right: '\\)', display: false}
              ]
          }
    );"></script>
```

**Comment by BedirT** [comment]
> > Then i included `math.html` in layouts/default/single.html using
> 
> You can directly add [Auto-render scripts](https://katex.org/docs/autorender.html#usage) in [extended_head.html](https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-faq/#custom-head--footer) like for example
> 
> ```
> {{ if or .Params.math .Site.Params.math }}
> <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/katex.min.css" integrity="sha384-AfEj0r4/OFrOo5t7NnNe46zW/tFgW6x/bCJG8FqQCEo3+Aro6EYUG4+cU+KJWu/X" crossorigin="anonymous">
> <script defer src="https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/katex.min.js" integrity="sha384-g7c+Jr9ZivxKLnZTDUhnkOnsh30B4H0rpLUpJ4jAIKs4fnJI+sEnkvrMWph2EDg4" crossorigin="anonymous"></script>
> <script defer src="https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/contrib/auto-render.min.js" integrity="sha384-mll67QQFJfxn0IYznZYonOWZ644AWYC+Pt2cHqMaRhXVrursRwvLnLaebdGIlYNa" crossorigin="anonymous"
>     onload="renderMathInElement(document.body);"></script>
> {{ end }}
> ```

supposed to be `extend_head.html` I believe. And I think if you could update the documentation on [this page](https://adityatelange.github.io/hugo-PaperMod/posts/math-typesetting/) to remove math.html that would be easier to follow up.

**Comment by pedrohgodoys** [comment]
> > Then i included `math.html` in layouts/default/single.html using
> 
> You can directly add [Auto-render scripts](https://katex.org/docs/autorender.html#usage) in [extended_head.html](https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-faq/#custom-head--footer) like for example
> 
> ```
> {{ if or .Params.math .Site.Params.math }}
> <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/katex.min.css" integrity="sha384-AfEj0r4/OFrOo5t7NnNe46zW/tFgW6x/bCJG8FqQCEo3+Aro6EYUG4+cU+KJWu/X" crossorigin="anonymous">
> <script defer src="https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/katex.min.js" integrity="sha384-g7c+Jr9ZivxKLnZTDUhnkOnsh30B4H0rpLUpJ4jAIKs4fnJI+sEnkvrMWph2EDg4" crossorigin="anonymous"></script>
> <script defer src="https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/contrib/auto-render.min.js" integrity="sha384-mll67QQFJfxn0IYznZYonOWZ644AWYC+Pt2cHqMaRhXVrursRwvLnLaebdGIlYNa" crossorigin="anonymous"
>     onload="renderMathInElement(document.body);"></script>
> {{ end }}
> ```

I actually did that, but this isn't working at all. Not sure what am I doing wrong here.
I called `math: true` at the yml header of a populated _posts/file.md_ and also tried at the _config.yml_ file, but nothing seems to work. 
Any idea of what could go wrong? I'm pretty new to Hugo, so I'm figuring stuff out yet.

**Comment by pedrohgodoys** [comment]
I would like to add to this issue.

I do bioinformatics, and usually, I use the R language with RStudio and its capabilities. Not sure of the familiarity the reader has with R, but there, we have R Markdown, which is kinda similar to Anaconda/Google Collab to python (much more capable).
RStudio saves the R Markdown mainly as `file.Rmd`, but you can use the YAML header to add other output formats, such as the proper `file.md`.

### Direct .md files
The situation was: I copied both file extensions to _site/content/blog/_, and expected to see a seamless result once it was markdown after all. That's what I found: 

![image](https://user-images.githubusercontent.com/45294360/199885111-f8a8308b-a9a5-44cd-b087-46a7cff38281.png)

When I opened the _site/content/blog/file.md_ that was what I found:

![image](https://user-images.githubusercontent.com/45294360/199886098-419b7b78-947b-42a4-b31b-d00c968ceb4a.png)

For some reason, a simple copy-paste turned my LaTeX expression into a markdown image. The actual code to the expression is highlighted, so it's not that hard to manually fix it, as shown (but it could "just works", and for some reason, don't):

![image](https://user-images.githubusercontent.com/45294360/199886629-bf4809f4-94ce-480b-b432-f10fa3a19357.png)

****
### R Markdown files

> *Any of my _.Rmd_ files work.*

I don't have any clue, but in the case of just renaming the `file.Rmd`to `file.md`, some expression (inline and/or block) don't work, even with the actual code being right (when I coded it in R): 

![image](https://user-images.githubusercontent.com/45294360/199887284-694e6fc3-500e-4000-8ddf-dfa81734a6c2.png)
![image](https://user-images.githubusercontent.com/45294360/199887212-1a0498f8-3f9a-480e-a135-6de73942dc5d.png)

And some times work properly:

![image](https://user-images.githubusercontent.com/45294360/199887535-dc67f8c0-73f9-4871-ae1c-379eabed9a5f.png)
![image](https://user-images.githubusercontent.com/45294360/199887458-dc7195d3-5170-41d5-9057-b0b7127839eb.png)

## Solution
Actually, there's the [_blogdown_ R package](https://www.rdocumentation.org/packages/blogdown/versions/1.13), which is useful, but I don't solve the problem (at least for me). [Here](https://bookdown.org/yihui/blogdown/configuration.html) is a pretty nice bookdown about R Markdown and Hugo.
I don't have any actual solution, and it needs more testing. **I'm just reporting it.** But as soon I get another solution, I'll update this. It would be pretty cool to have this seamless workflow.

**Comment by varun-ml** [comment]
This is a good answer.

Adding this script helps with rendering math functions inline equations. 

```
<script>
    document.addEventListener("DOMContentLoaded", function() {
        renderMathInElement(document.body, {
            delimiters: [
                {left: "$$", right: "$$", display: true},
                {left: "$", right: "$", display: false}
            ]
        });
    });
</script>

```

[how to use math typesetting](https://mertbakir.gitlab.io/hugo/math-typesetting-in-hugo/)

**Comment by varun-ml** [comment]
A few additional pointers, using 
> \cr instead of \\\\
> \ast instead of *
> \begin<aligned> and \end<aligned> cannot be on their own line. See example below

Sample's i was able to write

```
$$
\begin{aligned} q(z_t|x) &= N(\sqrt\alpha_tz_{t-1}, (1 - \alpha_t )I) \cr 
&= \sqrt\alpha_tz_{t-1} + \sqrt(1-\alpha_t)*\epsilon_t \cr 
&= \sqrt\alpha_t(\sqrt\alpha_tz_{t-2} + \sqrt(1-\alpha_{t-1})\ast\epsilon_{t-1}) + \sqrt(1-\alpha_t)\ast\epsilon_t \cr
&= \sqrt\alpha_t\sqrt\alpha_tz_{t-2} + \sqrt\alpha_t\sqrt(1-\alpha_{t-1})\ast\epsilon_{t-1} + \sqrt(1-\alpha_t)\ast\epsilon_t \cr 
&= \sqrt\alpha_t\sqrt\alpha_tz_{t-2} + \sqrt(1-\alpha_t\alpha_{t-1})\ast\epsilon_{t-1}^\ast \quad where \thinspace \epsilon_{t-1}^\ast\in N(0, I) \cr
&= ... \cr
&= \sqrt(\bar\alpha_t)x + \sqrt(1 - \bar\alpha_t )\ast\epsilon  \quad where \thinspace \epsilon \in N(0, I) \cr
&= N(\sqrt(\bar\alpha_t)x, (1 - \bar\alpha_t )I) \quad where \thinspace \bar\alpha_t=\Pi_{i=1}^T(\sqrt\alpha_i) \cr \end{aligned}
$$
```

![katex output](https://user-images.githubusercontent.com/7286325/206972263-f025842d-d044-4f8a-881f-35d4c323ab83.png)

**Comment by varun-ml** [comment]
A few additional pointers, using 
> \cr instead of \\\\
> \ast instead of *
> \begin<aligned> and \end<aligned> cannot be on their own line. See example below

Sample's i was able to write

```
$$
\begin{aligned} q(z_t|x) &= N(\sqrt\alpha_tz_{t-1}, (1 - \alpha_t )I) \cr 
&= \sqrt\alpha_tz_{t-1} + \sqrt(1-\alpha_t)*\epsilon_t \cr 
&= \sqrt\alpha_t(\sqrt\alpha_tz_{t-2} + \sqrt(1-\alpha_{t-1})\ast\epsilon_{t-1}) + \sqrt(1-\alpha_t)\ast\epsilon_t \cr
&= \sqrt\alpha_t\sqrt\alpha_tz_{t-2} + \sqrt\alpha_t\sqrt(1-\alpha_{t-1})\ast\epsilon_{t-1} + \sqrt(1-\alpha_t)\ast\epsilon_t \cr 
&= \sqrt\alpha_t\sqrt\alpha_tz_{t-2} + \sqrt(1-\alpha_t\alpha_{t-1})\ast\epsilon_{t-1}^\ast \quad where \thinspace \epsilon_{t-1}^\ast\in N(0, I) \cr
&= ... \cr
&= \sqrt(\bar\alpha_t)x + \sqrt(1 - \bar\alpha_t )\ast\epsilon  \quad where \thinspace \epsilon \in N(0, I) \cr
&= N(\sqrt(\bar\alpha_t)x, (1 - \bar\alpha_t )I) \quad where \thinspace \bar\alpha_t=\Pi_{i=1}^T(\sqrt\alpha_i) \cr \end{aligned}
$$
```

![katex output](https://user-images.githubusercontent.com/7286325/206972263-f025842d-d044-4f8a-881f-35d4c323ab83.png)

**Comment by varun-ml** [comment]
Creating a shortcode for katex worked for me. Look at the solution provided here -- [soln](https://discourse.gohugo.io/t/how-to-render-math-equations-properly-with-katex/40998)

this prevents html processing before katex.

**Comment by Flecart** [comment]
https://github.com/adityatelange/hugo-PaperMod/issues/236#issuecomment-1302968905

Is this solved? seems that it still sees \_ \_ as cursive to me. Did you find a sol?

**Comment by Flecart** [comment]
I think i found a solution about the underscore problem.

## The solution

Just need to add 
```yaml

    # Add math compatibility
    extensions:
      passthrough:
        delimiters:
          block:
          - - \[
            - \]
          - - $$
            - $$
          inline:
          - - \(
            - \)
        enable: true
```

Under the markup engine settings as described https://gohugo.io/getting-started/configuration-markup/.

## Description of the problem

As explained [here](https://docs.mathjax.org/en/v2.7-latest/tex.html#:~:text=In%20Markdown%2C%20the%20underscore%20is,underscore%20to%20indicate%20a%20subscript.) katex and mathjax can't do anything if the underlying preprocessor sees the text as a <em> tag and converts it.

So you need to work at the markdown preprocessor level, and don't let it convert math stuff.
Hope this helps. Send a :heart:  if this helps you :)
