### ISSUE TITLE
[Feature] Edit button for posts

### ISSUE THREAD

**Issue by Syphdias** [adityatelange/hugo-PaperMod#238]
I was looking for an option to easily add the ability to suggest changes to posts. I saw another hugo theme did this [here](https://github.com/stapelberg/hugo/blob/947e73e83246507891f687c201ee7be0bb47adb9/themes/stapelberg/layouts/_default/single.html#L41) resulting in [this](https://michael.stapelberg.ch/posts/2012-09-23-systemd-ionice/).

I'd suggest making it optionally by specifying an `editUrl`:
```
params:
  editUrl: "https://github.com/stapelberg/hugo/edit/main/"
```

And adding a edit button/string to `layouts/_default/single.html`:
```
{{- if (.Param "editUrl") }}
  <a href="{{ .Param "editUrl" }}/content/{{ .File.Path }}">Suggest changes</a>
{{- end }}
```
I believe the originally used `.File.LogicalName` is not what is needed here since it does not account for subfolders.

I'M not good as designing stuff so it looks good or I would have opened a PR. If this is something that is wanted and someone could give me a hand with where to put it, I#d be happy to open an PR.

**Comment by adityatelange** [comment]
I'm not sure if we'll add buttons in post's meta, but a simple text link would be thoughtful
