### ISSUE TITLE
Support showing license under every post

### ISSUE THREAD

**Issue by QuarticCat** [adityatelange/hugo-PaperMod#239]
An [example](https://blog.skk.moe/post/hentaiverse-advice/) (zh-CN)

Sorry I didn't find an English example.

**Comment by Jarmos-san** [comment]
I could be wrong, but can't you customize your theme by adding the necessary changes under `layouts/_defaults`? Perhaps, you could take a look at the [documentations on Single Page Templates](https://gohugo.io/templates/single-page-templates/) as well.

**Comment by QuarticCat** [comment]
@Jarmos-san Thanks, I'll have a try.
