### ISSUE TITLE
[Feature][Discussion] Tree-style category list page

### ISSUE THREAD

**Issue by kdkasad** [adityatelange/hugo-PaperMod#24]
It's possible to list multiple categories for each page. This can be handled one of two ways:
1. The page is part of each category
2. The categories nest

Take the following example:
```
categories:
  - tutorials
  - git
```
With option 1, the page would be part of the `tutorials` category and the `git` category.  
With option 2, the page would be a part of the `git` subcategory of `tutorials`.

Anyways, with option 2, it's possible to have a nesting (tree-style) category list such as the following:
![image of tree-style category list](https://user-images.githubusercontent.com/63574107/95041024-5f5b3b00-068a-11eb-8bdd-37c52f05902c.png)
(This is public at https://kasad.com/blog/categories/)

How do you feel about implementing this feature?

**Comment by adityatelange** [comment]
That looks cool  `+1`
But categories aren't meant to be in hierarchy. I understand that categories can be inherited, but the format we use is list a list and is not a hierarchical list.
```
categories:
  - tutorials
  - git
```
Also a post can be of multiple categories which might fail for this structure and show repeated posts, consider "Creating a Blog with Hugo", it can be in categories of `web` `hosting` `blog` `hugo` etc , for people writing on multiple topics this can get overlapped and get complicated !

**Comment by kdkasad** [comment]
That makes sense. I use categories as a nested structure and tags for what you're talking about. I.E. if a page fits with both `blog` `hugo` and `web`, those tags will be applied, but it would be in only one category (tutorials > development > web)
