### ISSUE TITLE
How to set Rss fro this theme?

### ISSUE THREAD

**Issue by zach030** [adityatelange/hugo-PaperMod#251]

**Comment by kdkasad** [comment]
This has already been answered in the Discussions page: https://github.com/adityatelange/hugo-PaperMod/discussions/217#discussioncomment-343880

Please check existing issues and discussions before opening a new one.

**Comment by zach030** [comment]
> This has already been answered in the Discussions page: https://github.com/adityatelange/hugo-PaperMod/discussions/217#discussioncomment-343880
> 
> 
> 
> Please check existing issues and discussions before opening a new one.

Thanks for your answer, I will check it right now
