### ISSUE TITLE
Next Page and Previous Page are swapped

### ISSUE THREAD

**Issue by zwbetz-gh** [adityatelange/hugo-PaperMod#260]
Hi @adityatelange, nice theme you have here, and well documented. 

## The Issue

The Next Page and Previous Page values seem to be swapped. 

![Screen Shot 2021-02-23 at 8 58 33 PM](https://user-images.githubusercontent.com/37317628/108941011-edc06100-7619-11eb-8173-574769454a8b.png)

## Expected Behavior

Let's take your [Archive list](https://adityatelange.github.io/hugo-PaperMod/archives/) as an example. 

The first 2 items in the list are:
- Installation | Update
- Features

Now, when I view the **Installation | Update** page, I would expect the **Features** page to be the **Previous** page, but instead it is the Next page.

Note: If this is intended behavior, then feel free to close this issue.

**Comment by adityatelange** [comment]
> Hi @adityatelange, nice theme you have here, and well documented.

Thanks

> Note: If this is intended behavior, then feel free to close this issue.

Yes, this is intended behavior, it doesn't look good when user has to press go back, to view the next post, is what I would say. 
Most of visits are from home page and it doesn't seem a good UX when we have click previous button in order to view next post.

**Comment by zwbetz-gh** [comment]
We shall agree to disagree on this one. Closing.
