### ISSUE TITLE
Old mobile Safari (iPad 2 v 9.3.5) has wrong padding for top right buttons and space between tags

### ISSUE THREAD

**Issue by subsoap** [adityatelange/hugo-PaperMod#261]
If anyone has an old iOS device and knows CSS well should test this

What it looks like:
![problem](https://user-images.githubusercontent.com/409170/108975881-ced2c680-763b-11eb-9178-4700a34c00f7.png)

Also the toggle style button (sun/moon) does not work on this version of Safari (and maybe others, I seem to remember iOS Safari having weird touch behavior).

**Comment by subsoap** [comment]
@adityatelange think the stale bot is a little too aggressive with marking issue as stale before they can be solved?

Here is old iPhone Safari version
![2021-03-04 06_47_10-](https://user-images.githubusercontent.com/409170/109981145-79d72600-7cb5-11eb-8547-0eb5e5516a01.png)

Here is how it looks in browser
![2021-03-04 06_47_31-](https://user-images.githubusercontent.com/409170/109981182-852a5180-7cb5-11eb-9038-949ef6596421.png)

I'm still trying to figure out best way how to fix this so it only impacts the old mobile Safari versions.

**Comment by subsoap** [comment]
Tried this, didn't work. I'll note everything which did not work. I'm not a CSS pro so a lot of poking in the dark for me.

```
/* Safari 6.1-10.0 (10.1 is the latest version of Safari at this time) */
@media screen and (min-color-index:0) 
and(-webkit-min-device-pixel-ratio:0) { @media
{
    #menu li+li { 

        color:#0000FF; 
        background-color:#CCCCCC; 

    }
}}
```

**Comment by subsoap** [comment]
This on its own for testing did work to make it display better. So maybe need to tune it and get it to select for the right hack to only be working on old mobile Safari. I'll keep testing. 

```
#menu li+li { 

	margin-left: 20px;

}
```

![2021-03-04 07_02_04-](https://user-images.githubusercontent.com/409170/109983363-9a07e480-7cb7-11eb-9c45-aee24a0bf2d6.png)

**Comment by subsoap** [comment]
This works, but IDK if it will negatively impact newer iOS versions I don't know where my newer iPhone for testing is atm.

```
/* Safari 6.1-10.0 (10.1 is the latest version of Safari at this time) */

@media screen and (min-color-index:0) 
and(-webkit-min-device-pixel-ratio:0) { @media
{
	#menu li+li { 

		margin-left: 20px;

	}
}}

/* Safari 10.1+ */

@media not all and (min-resolution:.001dpcm) { @media
{
	#menu li+li { 

		margin-left: 20px;

	}
}}
```

**Comment by adityatelange** [comment]
@subsoap According to all these [issues](https://github.com/adityatelange/hugo-PaperMod/issues?q=safari) related to safari, I think it is outdated ?

**Comment by subsoap** [comment]
@adityatelange Tons of people still use these devices and the CSS is broken for them. I have it fixed in my copy of the theme at least and anyone can find this issue if they want to fix it in their own copy.
