### ISSUE TITLE
The 'DateFormat' variable is not mentioned in the wiki

### ISSUE THREAD

**Issue by RealA10N** [adityatelange/hugo-PaperMod#262]
Hi there!
I'm building a non-English blog and the English date string on pages on my site (_January 2, 2006_, for example) really bothered me.
After digging in this repo I found #39 which implemented the `DateFormat` parameter that solved my problem!
However, this variable was never documented in the [wiki.](https://github.com/adityatelange/hugo-PaperMod/wiki/Variables#site-variables-under-params)

I was thinking about adding something like:
````
| `DateFormat`                           | string        | "January 2, 2006"        | The format of date strings in the website. [More info](https://bit.ly/2Ml4FPn)      |
````

I think adding it to the wiki will help a lot of folks here that are looking for a solution to the same problem I had 😄

**Comment by adityatelange** [comment]
Thanks for letting us know about this :+1:  I have updated the wiki.
