### ISSUE TITLE
Stop wrapping pre-formatted code snippets on small screens

### ISSUE THREAD

**Issue by loganmarchione** [adityatelange/hugo-PaperMod#267]
I have some long code snippets on my site that I do not want to wrap:
```
cp /etc/letsencrypt/live/postgres.yourdomain.com/fullchain.pem /etc/postgresql/11/main/fullchain.pem
cp /etc/letsencrypt/live/postgres.yourdomain.com/privkey.pem /etc/postgresql/11/main/privkey.pem
chmod 600 /etc/postgresql/11/main/fullchain.pem /etc/postgresql/11/main/privkey.pem
chown postgres:postgres /etc/postgresql/11/main/fullchain.pem /etc/postgresql/11/main/privkey.pem
systemctl restart postgresql
```
On the desktop version of the site, the code does not wrap and I see a scrollbar. This is what I want.
![Screenshot_20210225_104537](https://user-images.githubusercontent.com/4955337/109178204-85d85a80-7780-11eb-90ab-05444be77048.png)

However, on mobile, the code wraps. Is there a way to override this and not wrap the lines? I would like the same experience on desktop and mobile.
![IMG_2992](https://user-images.githubusercontent.com/4955337/109178257-925cb300-7780-11eb-8789-0bd41b23501c.PNG)

I think this is the correct CSS class to edit, but I can't get the correct combination of attributes/values.
```
.post-content pre {
    white-space: pre;
    overflow: hidden;
}
```

**Comment by loganmarchione** [comment]
Ok, this is working for me. Displays correctly on desktop and mobile. Not sure if you want to add it to an example. Thank you!
```
.post-content pre code {
	white-space: pre;
	overflow: hidden;
	overflow-x: scroll;
	word-break: normal;
}
```

**Comment by adityatelange** [comment]
@loganmarchione Which mobile browser has this issue ? I am using chrome and/or firefox on android 10 and the lines aren't wraped

**Comment by loganmarchione** [comment]
I was using Firefox and Safari on iOS 14.4. On iOS, all browsers (Chrome, Firefox, etc..) use Safari to render the pages.

Interestingly, using Firefox's [responsive design mode](https://developer.mozilla.org/en-US/docs/Tools/Resonsive_Design_Mode) on a PC to make the virtual screen smaller did not produce the issue. So I'm guessing it's Safari/Apple and the way Safari renders pages.
