### ISSUE TITLE
Social icons not showing

### ISSUE THREAD

**Issue by abhiyanbeta** [adityatelange/hugo-PaperMod#27]
Hi,
The social icons are not displaying for me. I've tried following as per: https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-icons/ and even with the example config.yml the icons are now showing up (see attached screenshot). 

![image](https://user-images.githubusercontent.com/57075221/95253951-11277280-0817-11eb-9cc1-158fa2bf92f8.png)

Here is my code: https://github.com/abhiyanbeta/hugo-test

Any idea how I would be able to fix it? Much appreciated!

**Comment by adityatelange** [comment]
It works for me without any modifications for code at https://github.com/abhiyanbeta/hugo-test

![image](https://user-images.githubusercontent.com/21258296/95280585-fedb2200-0872-11eb-858d-90becd52801b.png)

**Comment by abhiyanbeta** [comment]
Tried again, works only in incognito for some reason. Thanks for your reply!

**Comment by adityatelange** [comment]
> Tried again, works only in incognito for some reason. Thanks for your reply!

That's not the case ! The resources were not linked by hugo as --disableFastRender , may not be enabled. 
This makes hugo server load cached website and serve the same, in incognito-mode there are no cached resources and every file is pulled freshly !
