### ISSUE TITLE
Add support for stackbit importer and stackbit site builder

### ISSUE THREAD

**Issue by Muhammad-Saad-01** [adityatelange/hugo-PaperMod#272]
Stackbit provides an array of tools for managing Jamstack sites. like WYSIWYG Editing, live previews, one-click deployment, and more.
all we need is just add [stackbit.yaml](https://www.stackbit.com/docs/stackbit-yaml/) configuration file.

**Comment by adityatelange** [comment]
Sure, PRs are welcome !

**Comment by Muhammad-Saad-01** [comment]
Thanks :)  
here another [blog post](https://www.stackbit.com/blog/hugo-stackbit-tutorial/) on how to configure the file. may it help :)
