### ISSUE TITLE
`hugo --minify` failed with `baseURL: "/"` after commit `e53bfe5`

### ISSUE THREAD

**Issue by essethon** [adityatelange/hugo-PaperMod#273]
Hi, 
After the commit 'fix json schema parsing error on pages not having a section' [`e53bfe5`](https://github.com/adityatelange/hugo-PaperMod/commit/e53bfe514a2c9c84a86e8d52ec48a24691f80dee) @adityatelange 

`hugo --minify` failed if:
- Set `baseURL` as `"/"` in `config.yml`, and
- At least one `.md` file under `content/somedir/`.

My OS and Hugo info:
- `macOS 11.2.2`, Intel Mac
```bash
$ hugo version
Hugo Static Site Generator v0.80.0/extended darwin/amd64 BuildDate: unknown
```

### Create a new Hugo site and clone PaperMod theme into `themes/papermod`
```bash
$ hugo new site papermod-issue-json
$ cd papermod-issue-json
$ git init
$ git submodule add https://github.com/adityatelange/hugo-PaperMod.git themes/papermod
```

### Edit `config.toml` or `config.yml`

1. set baseURL to `"/"`
2. set theme to `papermod`

```toml
# config.toml

baseURL = "/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "papermod"
```

### Then create something under `content/somedir`
```bash
$ mkdir content/posts
$ touch content/posts/test.md
```

### Finally get the error
```bash
$ hugo --minify
Start building sites …
Total in 65 ms
Error: Error building site: failed to render pages: JSON parse error: expected comma character or an array or object ending on line 12 and column 5
   12:     {
           ^
```

### Note
1. `hugo` and `hugo server` works well. Only `hugo --minify` failed.
2. If set baseURL = `""` (empty) or the real hostname, no error raised.
3. If change the if condition in `themes/papermod/layouts/partials/templates/schema_json.html` line 48 back to `{{- if $bc_list }}, {{end }}`, the above errors are gone. But I don't want to manually edit the external theme submodule.
3. Is setting baseURL as `"/"` a bad practice here?

Thanks a lot.

**Comment by adityatelange** [comment]
Yes setting baseURL as `"/"` gets weird results coz the theme uses Absolute URLs everywhere and not Relative ones

**Comment by essethon** [comment]
> Yes setting baseURL as `"/"` gets weird results coz the theme uses Absolute URLs everywhere and not Relative ones

Thanks a lot!
Just a minor question: is there a recommended practice on setting the baseURL if I want to publish the site to multiple domains?

**Comment by adityatelange** [comment]
@essethon Read hugo doce here https://gohugo.io/content-management/multilingual/#configure-multilingual-multihost

**Comment by petercottonswab** [comment]
haha

On Feb 28, 2021, at 12:32 AM, X ZHAO <notifications@github.com> wrote:

﻿
Yes setting baseURL as "/" gets weird results coz the theme uses Absolute URLs everywhere and not Relative ones

Thanks a lot!
Just a minor question: is there a recommended practice on setting the baseURL if I want to publish the site to multiple domains?
