### ISSUE TITLE
favicon does not show up on Github Pages

### ISSUE THREAD

**Issue by NguyenVuKhang** [adityatelange/hugo-PaperMod#275]
First of all, big thank you to everyone who contributed to this hugo theme.
I'm trying to host my site on Github Pages, and currently I have a full set of favicons in the `/static` folder, following instructions from https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-faq/
![Screen Shot 2021-02-28 at 20 48 56](https://user-images.githubusercontent.com/10664455/109419100-a6b1e180-7a06-11eb-8bd9-5c19f395b321.png)

when I run
`hugo server -D`

the favicon shows on safari, but when I push the project to Github and run the site on Github Pages, the favicon does not appear.

**Comment by adityatelange** [comment]
I can't reproduce your Issue, make sure you don't include `static` in image url

**Comment by NguyenVuKhang** [comment]
This was solved by editing lines 58-68 of `/themes/PaperMod/layouts/partials/head.html`,
from this:
```
<!-- <link rel="icon" href="{{- .Site.Params.assets.favicon | default "favicon.ico" | absURL -}}">
<link rel="icon" type="image/png" sizes="16x16" href="
    {{- .Site.Params.assets.favicon16x16 | default "favicon-16x16.png" | absURL -}}">
<link rel="icon" type="image/png" sizes="32x32" href="
    {{- .Site.Params.assets.favicon32x32 | default "favicon-32x32.png" | absURL -}}">
<link rel="apple-touch-icon" href="
    {{- .Site.Params.assets.apple_touch_icon | default "apple-touch-icon.png" | absURL -}}">
<link rel="mask-icon" href="{{- .Site.Params.assets.safari_pinned_tab | default "safari-pinned-tab.svg" | absURL -}}">
<meta name="theme-color" content="#2e2e33">
<meta name="msapplication-TileColor" content="#2e2e33"> -->
<link rel="icon" href="{{"static/favicon.png" | relURL}}" type="image/png">
```
to this:
```
<link rel="icon" href="{{- .Site.Params.assets.favicon | default "favicon.ico" | absURL -}}">
<link rel="icon" type="image/png" sizes="16x16" href="
    {{- .Site.Params.assets.favicon16x16 | default "favicon-16x16.png" | absURL -}}">
<link rel="icon" type="image/png" sizes="32x32" href="
    {{- .Site.Params.assets.favicon32x32 | default "favicon-32x32.png" | absURL -}}">
<link rel="apple-touch-icon" href="
    {{- .Site.Params.assets.apple_touch_icon | default "apple-touch-icon.png" | absURL -}}">
<link rel="mask-icon" href="{{- .Site.Params.assets.safari_pinned_tab | default "safari-pinned-tab.svg" | absURL -}}">
<meta name="theme-color" content="#2e2e33">
<meta name="msapplication-TileColor" content="#2e2e33">
<!-- <link rel="icon" href="{{"static/favicon.png" | relURL}}" type="image/png"> -->
```

**Comment by Allenxuxu** [comment]
I have the same problem

**Comment by Allenxuxu** [comment]
> This was solved by editing lines 58-68 of `/themes/PaperMod/layouts/partials/head.html`,
> from this:
> 
> ```
> 
> <link rel="icon" href="{{"static/favicon.png" | relURL}}" type="image/png">
> ```
> 
> to this:
> 
> ```
> <link rel="icon" href="{{- .Site.Params.assets.favicon | default "favicon.ico" | absURL -}}">
> <link rel="icon" type="image/png" sizes="16x16" href="
>     {{- .Site.Params.assets.favicon16x16 | default "favicon-16x16.png" | absURL -}}">
> <link rel="icon" type="image/png" sizes="32x32" href="
>     {{- .Site.Params.assets.favicon32x32 | default "favicon-32x32.png" | absURL -}}">
> <link rel="apple-touch-icon" href="
>     {{- .Site.Params.assets.apple_touch_icon | default "apple-touch-icon.png" | absURL -}}">
> <link rel="mask-icon" href="{{- .Site.Params.assets.safari_pinned_tab | default "safari-pinned-tab.svg" | absURL -}}">
> <meta name="theme-color" content="#2e2e33">
> <meta name="msapplication-TileColor" content="#2e2e33">
> 
> ```

@NguyenVuKhang   Why not open a Pull Request?
