### ISSUE TITLE
Suggestion: Option to move share buttons to right/left side

### ISSUE THREAD

**Issue by mohnoor94** [adityatelange/hugo-PaperMod#277]
**Suggestion**

I would suggest adding an option to move (or duplicate?) the share buttons to be sticky on the (middle) right side for LTR languages and on the (middle) left for RTL languages so that it would make them more visible and push the user to click them.

Example: https://blog.noor.guru/scala-and-functional-programming-why
Enhancement: I guess there will be no need for the background and border for the vertical share area.

**Comment by adityatelange** [comment]
PaperMod is not Hashnode. You are free to make changes by forking the theme and customizing it accordingly

**Comment by mohnoor94** [comment]
> PaperMod is not Hashnode. You are free to make changes by forking the theme and customizing it accordingly

That's why I mentioned it's a "suggestion" :)
