### ISSUE TITLE
reset.css needs to be placed first within css list, it is currently not being forced to be first

### ISSUE THREAD

**Issue by subsoap** [adityatelange/hugo-PaperMod#280]
reset.css should not be able to override main.css, which is possible now.

**Comment by adityatelange** [comment]
Doesn't matter if i works fine

**Comment by subsoap** [comment]
Fixing it may be annoying to do since putting the order right would probably break other things, but the way it is now it will just make it a little bit troublesome to maintain the CSS from outsiders to the project.

**Comment by adityatelange** [comment]
What solution do you suggest here ?

**Comment by subsoap** [comment]
Force reset.css to be the first CSS and then go through any issues that come up until they are resolved. This can be checked by comparing CSS rules. Maybe asking in the Hugo forum for ideas / CSS communities on a good way to fix it would give a better idea.

Put reset.css into is own reset folder so it's not included in common or extended and then in head.html reference it first just after  then they can be concacted as reset + common + extended.

I've not tested that myself to see what would happen but it should work to fix the order. Then all discrepancies between reset and common would need to be fixed since right now there are rules in reset which override the other css in common. 

Like you say it works right now doing this is only necessary to make it easier and clearer to maintain in the future.

**Comment by adityatelange** [comment]
> Force reset.css to be the first CSS and then go through any issues that come up until they are resolved. This can be checked by comparing CSS rules. Maybe asking in the Hugo forum for ideas / CSS communities on a good way to fix it would give a better idea.
> 
> Put reset.css into is own reset folder so it's not included in common or extended and then in head.html reference it first just after `<!-- Styles -->` then they can be concacted as reset + common + extended.
> 
> I've not tested that myself to see what would happen but it should work to fix the order. Then all discrepancies between reset and common would need to be fixed since right now there are rules in reset which override the other css in common.
> 
> Like you say it works right now doing this is only necessary to make it easier and clearer to maintain in the future.

Changing names of underlying files is what I don't want as there are people overriding `reset.css` and that will break their website if they don't out attention to what they are merging. But there is no other simpler option whatsoever rn
