### ISSUE TITLE
Smooth scrolling cannot work in Safari

### ISSUE THREAD

**Issue by Triple-Z** [adityatelange/hugo-PaperMod#297]
When I click the "back to top" button (or click the header refs in table of contents), I always get a smooth scrolling. But NOT in Safari. It will directly jump to the destination anchor when I'm using the Safari.

**Comment by adityatelange** [comment]
Idk but Safari is incompatible with lots of stuff here

**Comment by adityatelange** [comment]
Safari does not support this,

https://stackoverflow.com/questions/56011205/is-there-a-safari-equivalent-for-scroll-behavior-smooth/56011281

https://stackoverflow.com/questions/51229742/javascript-window-scroll-behavior-smooth-not-working-in-safari
