### ISSUE TITLE
[BUG]Cover images not showing when sharing on Whats app or Telegram  when using page bundles

### ISSUE THREAD

**Issue by mukhtharcm** [adityatelange/hugo-PaperMod#307]
**Describe the bug**
Social share images not showing. 
Before using page bundles it always shown cover image when sharing posts   
But after changing to page bundle it doesn't show. 

 - Device/Os: [e.g. Android 10]
 - Type: [e.g. Desktop/Mobile]
 - Browser and version [e.g. Chrome 86.0]: 
 - Hugo Version [ >=0.74 expected]: 
 - Theme Version [e.g. v4.0, master, or commit-id ]: 

**Steps to reproduce the behavior:**

**Expected behavior**:

**Screenshots**

**Additional context**

**Comment by mukhtharcm** [comment]
I examined and found out that the `og:image` is being rendered as `https://example.com/mypost.png` instead of 'https://example.com/mypost/mypost.png`

**Comment by mukhtharcm** [comment]
Sorry,
It was actually because of not setting `relative: true` FrontMatter.

**Comment by adityatelange** [comment]
> Sorry,
> It was actually because of not setting `relative: true` FrontMatter.

Ya, closing
