### ISSUE TITLE
[BUG] .Param hideSummary does not seem to work

### ISSUE THREAD

**Issue by yibinlin** [adityatelange/hugo-PaperMod#310]
**Describe the bug**

 - Device/Os: Mac OS Catalina
 - Type: Desktop
 - Browser and version [e.g. Chrome 86.0]: Chrome 89.0.4389.90
 - Hugo Version [ >=0.74 expected]: hugo v0.81.0+extended
 - Theme Version [e.g. v4.0, master, or commit-id ]: e76154d418e09ac5604e60437e0278dabb786a5e

**Steps to reproduce the behavior:**
1. Set article `hideSummary: true`
2. Run `hugo server -D`
3. the section .entry-content is still present.

**Expected behavior**:
If `hideSummary: true` the .entry-content section should not be shown, I guess?

**Screenshots**
N/A

**Additional context**
Thank you Aditya for the project, I like the theme!

**Comment by adityatelange** [comment]
@yibinlin Update your copy of theme. It wasn't present as on e76154d

![image](https://user-images.githubusercontent.com/21258296/111864459-0442a980-8987-11eb-907b-9ef3ed530802.png)

**Comment by yibinlin** [comment]
@adityatelange Yes by updating the theme repo it now works! Thank you! I think we can close this.
