### ISSUE TITLE
Series Support.

### ISSUE THREAD

**Issue by mukhtharcm** [adityatelange/hugo-PaperMod#316]
Is there any way to implement series in this theme?
I mean, some posts organized in a particular order, which are related to the same topic?

**Comment by tmakowski** [comment]
I think it is already covered by [Hugo taxonomies](https://gohugo.io/content-management/taxonomies/). Adding a post to a serie simply requires adding respective `series` entry to the post's front matter.

See [how it looks like on the example site](https://adityatelange.github.io/hugo-PaperMod/fr/series/), and how it is configured in  example site's config.yaml: [taxonomies](https://github.com/adityatelange/hugo-PaperMod/blob/exampleSite/config.yml#L174-L177) and [menu](https://github.com/adityatelange/hugo-PaperMod/blob/exampleSite/config.yml#L65-L67). It might not be a representative example with a single post, however there is [weight variable](https://github.com/adityatelange/hugo-PaperMod/wiki/Variables#page-variables) (and date) for manipulating posts order.

**Comment by mukhtharcm** [comment]
Oh!
Thanks for pointing out ☺️
But is there any way to show posts according to date in front (as normal) and show in another order in series Page?

**Comment by adityatelange** [comment]
You need to tweak out `terms.html` for `series` taxonomy, but this is out-of-scope for the current issue, you can head over to Discussions of this repo, so that someone could help you if they want to.
