### ISSUE TITLE
Mobile responsive menu

### ISSUE THREAD

**Issue by nevian427** [adityatelange/hugo-PaperMod#318]
Hi,

Great theme but is there way to enable hamburger menu for mobile devices (or just small screen)?

**Comment by kdkasad** [comment]
Currently, no.

**Comment by ODIRFY** [comment]
> Hi,
> 
> Great theme but is there way to enable hamburger menu for mobile devices (or just small screen)?

I like the current navigation. I think a hamburger menu isn't needed.
