### ISSUE TITLE
How to disable top-link button?

### ISSUE THREAD

**Issue by donchan922** [adityatelange/hugo-PaperMod#321]
I would like to disable top-link button as follows. It doesn't seem to have that function.

![image](https://user-images.githubusercontent.com/21258296/112305156-60c60180-8cc4-11eb-836b-a9a2a0608f2a.png)

**Comment by adityatelange** [comment]
> It doesn't seem to have that function.

What function do you expect ? It just scrolls to top of page.

**Comment by donchan922** [comment]
Thanks for reply.

I expect `params` parameter as follows.

```yml
params:
  disableScrollToTop: true
```

**Comment by donchan922** [comment]
Thank you, great!!!
