### ISSUE TITLE
Option to replace header text with image

### ISSUE THREAD

**Issue by derins** [adityatelange/hugo-PaperMod#328]
I'd like to be able to replace the header text with image. Is this currently possible?

**Comment by adityatelange** [comment]
Yes. use [Override theme template](https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#override-theme-template) to override [home_info.html](https://github.com/adityatelange/hugo-PaperMod/blob/master/layouts/partials/home_info.html) and put yout image in it with HTML tags
