### ISSUE TITLE
Image Gallery Feature Request

### ISSUE THREAD

**Issue by cryptic-code** [adityatelange/hugo-PaperMod#330]
Hi.

The PaperMod theme is already quite feature-packed. But how about adding an image gallery shortcode too? Maybe like using Lightbox2 or Photoswipe or some other way.

That would make it much more efficient to add multiple images in a post (for bloggers). It would be very helpful. :)

**Comment by adityatelange** [comment]
We don't have any external dependencies being fetch from some CDN as now, so we would like to stick to it...
Anyone is however free to modify a/c to their wish as always!
