### ISSUE TITLE
[BUG] Google Search Console complains: "Unparsable structured data: Incorrect value type" (`itemListElement` starts with comma)

### ISSUE THREAD

**Issue by JannikArndt** [adityatelange/hugo-PaperMod#331]
- Hugo Version [ >=0.74 expected]: v0.82.0
 - Theme Version [e.g. v4.0, master, or commit-id ]: master

Google Search Console complains about the `BreadcrumbList` in the `single.html` pages:

<img width="392" alt="image" src="https://user-images.githubusercontent.com/7119122/112727316-4c7f4000-8f22-11eb-9a29-374f057f28bb.png">

The `BreadcrumbList` > `itemListElement` starts with a comma:

```json
{
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  "itemListElement": [, 
    {
      "@type": "ListItem",
      "position":  2 ,
      "name": "Blog",
      "item": "https://www.jannikarndt.de/blog/"
    }, 
    {
      "@type": "ListItem",
      "position":  3 ,
      "name": "Using scalap, javap and the scala compiler to understand the journey from code to bytecode",
      "item": "https://www.jannikarndt.de/blog/2021/03/using_scalap_javap_and_the_scala_compiler/"
    }
  ]
}
```

on https://www.jannikarndt.de/blog/2021/03/using_scalap_javap_and_the_scala_compiler/.

I compared that to the example site:

```json
{
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    "itemListElement": [
        {
            "@type": "ListItem",
            "position": 1,
            "name": "Posts",
            "item": "https://adityatelange.github.io/hugo-PaperMod/posts/"
        },
        {
            "@type": "ListItem",
            "position": 2,
            "name": "Rich Content",
            "item": "https://adityatelange.github.io/hugo-PaperMod/posts/rich-content/"
        }
    ]
}
```

for https://adityatelange.github.io/hugo-PaperMod/posts/rich-content/.

Looking at the code in `schema_json.html`, the line `{{- if (and $index)}}, {{end }}` skips the first entry:

https://github.com/adityatelange/hugo-PaperMod/blob/0c0c6847e56e137664c1633e7f3e1d6fdc7f067a/layouts/partials/templates/schema_json.html#L33-L44

That makes sense, because `$bc_pg` is defined as 

https://github.com/adityatelange/hugo-PaperMod/blob/0c0c6847e56e137664c1633e7f3e1d6fdc7f067a/layouts/partials/templates/schema_json.html#L23

The difference here is that the "base" url for the example site is https://adityatelange.github.io/hugo-PaperMod/ whereas for my site it's https://www.jannikarndt.de/.

In fact, when running the site locally with `hugo server`, the issue does _not_ occur, because the base path then is `localhost:1313`:

```json
{
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    "itemListElement": [
        {
            "@type": "ListItem",
            "position": 1,
            "name": "Blog",
            "item": "http://localhost:1313/blog/"
        },
        {
            "@type": "ListItem",
            "position": 2,
            "name": "Using scalap, javap and the scala compiler to understand the journey from code to bytecode",
            "item": "http://localhost:1313/blog/2021/03/using_scalap_javap_and_the_scala_compiler/"
        }
    ]
}
```

<br><br><br><br>
 
 
 
------

<br><br><br><br>
 
…… long thinking break …… 🤦 
<br><br><br><br>

------

<br><br><br><br>

Okay, so `hugo` sets the `baseURL` parameter automatically. And it sets it "correctly". _My_ `config.yaml` on the other hand defined it as

```yaml
baseURL: "https://www.jannikarndt.de"
```

Note the missing trailing slash.

Nothing else in `hugo` breaks if you don't write that (at least I've noticed nothing). Actually, the Sample `config.yaml` on https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-installation/#sample-configyml even specifies it _without_ the slash 😄 

<img width="603" alt="image" src="https://user-images.githubusercontent.com/7119122/112727807-7b96b100-8f24-11eb-9f3c-fd98d8342b62.png">

(That makes me feel a little less stupid 😅)

I would propose

1. to change the sample `config.yaml`
2. to make the `$bc_list` more resilient to this config 😊 

I would have created a PR, but my go-template-skills are not up to that level. 

I also decided to file an issue despite having solved this for myself, because 1. it let's others find this and the solution and 2. there is a chance to limit user-frustration here 😉

**Comment by adityatelange** [comment]
@JannikArndt https://github.com/adityatelange/hugo-PaperMod/commit/0f0e027def4bce325f810be4c9f4e3c3a9218b68 
should fix #331 but the build is failing for some reason

**Comment by JannikArndt** [comment]
@adityatelange I _think_ that made it worse 😄 If I build my site with the current master, I get 

1. no comma between the entries
2. no increasing position

```json
{
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  "itemListElement": [
    {
      "@type": "ListItem",
      "position":  1 ,
      "name": "Blog",
      "item": "https://www.jannikarndt.de/blog/"
    }                     // <--- comma missing
    {
      "@type": "ListItem",
      "position":  1 ,       // <--- 1 instead of 2
      "name": "Using scalap, javap and the scala compiler to understand the journey from code to bytecode",
      "item": "https://www.jannikarndt.de/blog/2021/03/using_scalap_javap_and_the_scala_compiler/"
    }
  ]
}
```

That would also match the [error message of the build](https://github.com/adityatelange/hugo-PaperMod/runs/2212665428) ("JSON parse error: expected comma character or an array or object ending on line 12 and column 5")

**Comment by JannikArndt** [comment]
I think you want the _opposite_ effect of the `trim`. A trailing slash is fine, but if it's _missing_ it needs to be added for the rest of the code to work. (No idea how to do this, though 😬)

**Comment by adityatelange** [comment]
Don't know why, builds fine locally with 0.82 linux/amd64 

![image](https://user-images.githubusercontent.com/21258296/112755384-157e5c80-8ffe-11eb-8154-bec4699eb7c2.png)

**Comment by adityatelange** [comment]
What I have discovered is with the previous code at L21, `baseURL` having `/` will not have `/` in starting of `$lang_url` 

The `split` command adds redundant empty values in array `$bc_list`. Thus generating blank `$element` and printing a `,` after it

by adding `trim` there won't be any leading or trailing `/` thus there won't be any empty values in array `$bc_list`. Solving the problem!

https://github.com/adityatelange/hugo-PaperMod/blob/54744ba6943321c22e69d65ef2377b398f70eb7d/layouts/partials/templates/schema_json.html#L21-L24

**Comment by adityatelange** [comment]
when $baseURL is `https://loop.com/` len is `2`

![image](https://user-images.githubusercontent.com/21258296/112755810-faace780-8fff-11eb-9e97-4667cb1ab730.png)

when $baseURL is `https://loop.com/` len is `4` :man_shrugging: 

![image](https://user-images.githubusercontent.com/21258296/112755821-0ac4c700-9000-11eb-842e-9d7eabd71546.png)

**Comment by JannikArndt** [comment]
🤷 

Quick Googling: https://github.com/gohugoio/hugo/issues/3262

> Use `absURL` and friends, and you should not have to worry about slashes.

The docs (https://gohugo.io/functions/absurl/) specifically mention JSON-LD, and also point to `relURL`, which might be the easiest solution here.

As to what is _correct_, there's [a thread here](https://discourse.gohugo.io/t/hugo-support-for-urls-without-a-trailing-slash/6763) that makes the point that "urls should have a trailing slash". (So my config was "wrong" from an "official Hugo-standpoint")

**Comment by adityatelange** [comment]
I'll just say the effort is too much to fix a `/` in baseURL, It'd be better if ppl just use a `baseURL` with `/`

**Comment by andream16** [comment]
Having the same issue on the latest PaperMod version. It seems like the [fix](https://github.com/adityatelange/hugo-PaperMod/blob/master/layouts/partials/templates/schema_json.html#L21) was reverted?

**Comment by deuts** [comment]
I'm still encountering this issue. Had to remove the following code in the `schema_json.html`:

```
{{/* BreadcrumbList */}}
{{- $url := replace .Parent.Permalink ( printf "%s" site.Home.Permalink) "" }}
{{- $lang_url := strings.TrimPrefix ( printf "%s/" .Lang) $url }}
{{- $bc_list := (split $lang_url "/")}}

{{- $scratch := newScratch }}
<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  "itemListElement": [
  {{- range $index, $element := $bc_list }}

    {{- $scratch.Add "path" (printf "%s/" $element ) | safeJS }}
    {{- $bc_pg := site.GetPage ($scratch.Get "path") -}}

    {{- if (and ($bc_pg) (gt (len . ) 0))}}
    {{- if (and $index)}}, {{end }}
    {
      "@type": "ListItem",
      "position": {{ add 1 $index  }},
      "name": {{ $bc_pg.Name }},
      "item": {{ $bc_pg.Permalink | safeHTML }}
    }
    {{- end }}

  {{- end }}
  {{- /*  self-page addition  */ -}}
  {{- if (ge (len $bc_list) 2) }}, {{end }}
    {
      "@type": "ListItem",
      "position": {{len $bc_list}},
      "name": {{ .Name }},
      "item": {{ .Permalink | safeHTML }}
    }
  ]
}
</script>
```
