### ISSUE TITLE
[FEATURE] Add support for Google Analytics 4

### ISSUE THREAD

**Issue by elijahgagne** [adityatelange/hugo-PaperMod#332]
Google Analytics 4 is somewhat new, but is now the default when creating a Google Analytics configuration. This post gives some rationale:
https://brandcraft.com/blog/5-reasons-you-need-google-analytics-4

I have added support by using layout overrides and implementing based on:
https://levelup.gitconnected.com/build-a-personal-website-with-github-pages-and-hugo-6c68592204c7

If you are open to it, I'd be delighted to send you pull request adding this to the project. Thanks!

**Comment by adityatelange** [comment]
GA 4 is already present in hugo 0.82 https://github.com/gohugoio/hugo/commit/ba16a14c6e884e309380610331aff78213f84751

In papermod we use async one

https://github.com/adityatelange/hugo-PaperMod/blob/0f0e027def4bce325f810be4c9f4e3c3a9218b68/layouts/partials/head.html#L90

It does make sense to remove GA ? And let people choose what config they want to add via [`extend_head`](https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#custom-head--footer) ?
It's pretty easy to use it though https://gohugo.io/templates/internal#use-the-google-analytics-template

**Comment by elijahgagne** [comment]
Thank you pointing all of this out. For me, using `extend_head.html` will work just fine. That said, it feels to me like it makes it harder for a newbie to figure out what to do. The simplest solution IMO would be to have two config parameters: `googleAnalytics` and `googleAnalytics_v4`.

**Comment by elijahgagne** [comment]
I understand better now. They are reusing the `googleAnalytics` parameter for both types. So you really need to pick one. So I'd propose adding a new `useGoogleAnalyticsV4` parameter that would default to `false` if unspecified. If set to `true`, then it does the appropriate thing. If you like that idea, I'd be happy to send you a pull request.

**Comment by adityatelange** [comment]
Added by 55fe10e9d39850c955dcfdd1e1a708c378dc7705 :+1:

**Comment by adityatelange** [comment]
@elijahgagne The non-async version does support both v3 and v4. 
You can see it [here](https://github.com/gohugoio/hugo/blob/5656a908d837f2aa21837d39712b8ab4aa6db842/tpl/tplimpl/embedded/templates/google_analytics.html). So it won't break for anyone, but yes hugo 0.82.0 is necessary for this.
