### ISSUE TITLE
"disableHugoGeneratorInject: true" is overridden by papermod

### ISSUE THREAD

**Issue by poly-bally** [adityatelange/hugo-PaperMod#335]
Description:
I don't know if this exactly classifies as a bug but the disableHugoGeneratorInject: true does not seem to work/is overwritten by the papermod theme, no matter whether I configure disableHugoGeneratorInject: true in config.yml or papermod's theme.toml, it is always injected in source.

Environment variables:
 - Device/Os: Windows 10
 - Type: Desktop
 - Browser and version: Google Chrome Version 89.0.4389.90 (Official Build) (64-bit) 
 - Hugo Version : v0.80.0-DEV windows/amd64
- Theme Version:  ALL versions

Steps to reproduce this:
1. Set disableHugoGeneratorInject: true in either config.yml or theme.toml
2. inspect/view source of web page, and **meta name=generator content="Hugo 0.80.0-DEV"** is still present even though disableHugoGeneratorInject has been set to true.

Expected behavior:
disableHugoGeneratorInject: true is overwritten by papermod whereas **meta name=generator content="Hugo 0.80.0-DEV"** should not have been injected after setting disableHugoGeneratorInject to true.

**Comment by adityatelange** [comment]
I don't know the reason behind this, maybe search hugo docs/ hugo issues.

However may I know what issue you are facing with the `meta` string being displayed ? 

It is a tag to add the name of the program you used to create your website. Hugo is open-source and so is this theme. By displaying a meta generator strings is just to give credits to the software which helped you generate the website. 

Also read https://github.com/gohugoio/hugo/issues/2850#issuecomment-269673618

If you want to still want to remove it, you are free to edit `partials/head.html` in your copy of theme.
