### ISSUE TITLE
[Feature Request] code copy

### ISSUE THREAD

**Issue by kbc8894** [adityatelange/hugo-PaperMod#344]
Hello!
First of all, thank you for your theme.

I'm using it really well, but I'd like to add one more feature.
If you look at this [link](https://themes.gohugo.io//theme/hugo-clarity/post/markdown-syntax/#code-block-with-hugos-internal-highlight-shortcode), you can see an `copy` icon when you mouse over the code block.

<img width="864" alt="Screen Shot 2021-04-03 at 11 03 32 PM" src="https://user-images.githubusercontent.com/3617939/113480887-a7400b00-94d1-11eb-9b53-dbe834a254cc.png">

**Comment by kdkasad** [comment]
For reference, here's the code that handles copying code blocks in that theme:
https://github.com/chipzoller/hugo-clarity/blob/b6ad33fee80f88bec51eae5c2eb9a613b8118d52/assets/js/code.js#L165
