### ISSUE TITLE
Help wanted LOGO placement

### ISSUE THREAD

**Issue by cyberwr3nch** [adityatelange/hugo-PaperMod#346]
Hi I was wondering where should I keep my imgae files to provied as absolute path, I tried to give /home/kali/Downloads/iam.png but failed. Help me with these please. Thanks

**Comment by cryptic-code** [comment]
place your image files under static folder (of your hugo site repo) and give the relative path to the file.

Suppose you place `logo.jpg` in `imgs` folder inside the `static` directory you will reference to it as `imgs/logo.jpg` in the `config` file.

**Comment by cyberwr3nch** [comment]
Thanks @cryptic-code . But got around with jekyll will try sometimes thanks.
