### ISSUE TITLE
Overriding Syntax Highlighting

### ISSUE THREAD

**Issue by mukhtharcm** [adityatelange/hugo-PaperMod#35]
Is there any way to override the default syntax highlighting of the theme?

**Comment by adityatelange** [comment]
PaperMod uses highlight.js for syntax highlighting, there is no option to override default syntax highlighting as of now !

---

### If you know how to edit the theme..
Although, you may use any of styling at https://cdnjs.com/libraries/highlight.js
and put it under `assets` dir, then you can use it from templates to use it with your own customized theme :tada:

**Comment by singhkays** [comment]
> PaperMod uses highlight.js for syntax highlighting

Interesting. I read that Chroma is faster than Highlight.js from https://harrycresswell.com/articles/performant-syntax-highlighting-in-hugo/. Are there benefits to the highlight.js approach?

> The advantage of using Chroma over other JavaScript libraries like Highlight.js or Prisma.js is that it’s built right into Hugo and doesn’t require any external dependencies. This make it extremely fast and reliable.

**Comment by adityatelange** [comment]
> > PaperMod uses highlight.js for syntax highlighting
> 
> Interesting. I read that Chroma is faster than Highlight.js from https://harrycresswell.com/articles/performant-syntax-highlighting-in-hugo/. Are there benefits to the highlight.js approach?
> 
> > The advantage of using Chroma over other JavaScript libraries like Highlight.js or Prisma.js is that it’s built right into Hugo and doesn’t require any external dependencies. This make it extremely fast and reliable.

It was not by choice, but the og theme paper was using hljs.
The og Design part of paper was never took out from papermod, as it is an integral part of paper!
