### ISSUE TITLE
Installed Papermod and Hugo but it only shows the README.md file

### ISSUE THREAD

**Issue by MarioCatuogno** [adityatelange/hugo-PaperMod#352]
Hello,
first of all great job with this theme, is awesome!
I'm a total newbie with Hugo and Github pages, but I have a problem with this Github page: [link](https://mariocatuogno.github.io/): as you can see, even if I have followed all the steps, the link shows only the README.md file.
This is the repository: [link](https://github.com/MarioCatuogno/MarioCatuogno.github.io).

If I try with the localhost:1313 I can see it properly, but on Github not.

Can someone help me? What I'm doing wrong?

**Comment by kdkasad** [comment]
You need to tell GitHub pages to serve from the `public/` directory.

**Comment by MarioCatuogno** [comment]
Hi @kdkasad , how do I tell GitHub pages to serve from `public/` directory?
In GitHub settings I can choose only between `root/` and `docs/` (which I don't have in tree structure.

<img width="663" alt="Screenshot 2021-04-12 at 13 41 50" src="https://user-images.githubusercontent.com/12764373/114389214-04545480-9b95-11eb-81ab-f680e3329b81.png">

**Comment by kdkasad** [comment]
I'm not sure. You could also have hugo output to the `docs/` directory.

**Comment by MarioCatuogno** [comment]
Ok found how to do it! I had to add `publishDir = "docs"` into the config.toml file.

Thanks!
