### ISSUE TITLE
[BUG] Search not working with netlify bundle JS

### ISSUE THREAD

**Issue by canhtran** [adityatelange/hugo-PaperMod#353]
**Describe the bug**

 - Device/Os: Chrome, Firefox, Safari
 - Type: [e.g. Desktop/Mobile]
 - Hugo Version [ >=0.82.0 expected]: 0.82.0
 - Theme Version [e.g. v4.0, master, or commit-id ]: v5.0

**Steps to reproduce the behavior:**
- Turn on the Bundle JS on Netlify 
- Netlify compresses the js into one single url.

Full error messages
`“https://d33wubrfki0l68.cloudfront.net/js/e1fba0111e9e11863e93635f3857150a8900a5a6/assets/js/search.min.58dc975fb823b4b84aae2b3d18a679c0895da9741570fce9236191fd39b88a78.js” is not eligible for integrity checks since it’s neither CORS-enabled nor same-origin.`

Adding `crossorigin="anonymous"` doesn't solve the issue as well. It returns the SHA is incorrected.

**Screenshots**
![image](https://user-images.githubusercontent.com/3214379/114387867-8d837f80-9bc5-11eb-8cda-18642361d643.png)
![image](https://user-images.githubusercontent.com/3214379/114388077-ce7b9400-9bc5-11eb-9fd5-4b973aacfb3b.png)

**Comment by adityatelange** [comment]
Doesn't seem like this is a theme related issue nor a hugo issue.

**Comment by canhtran** [comment]
Hi @adityatelange the netlify bundle funtion is working fine with other theme. I guess in papermod, we hardcode the `integrity`, that's why when netlify compress the js, it cannot check SHA

**Comment by adityatelange** [comment]
@canhtran Have you read FAQs ? I think it answers your question https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs

**Comment by canhtran** [comment]
@adityatelange silly me! Thank you for you prompt reply
