### ISSUE TITLE
[IMPROVE] Add minimum hugo version in README.md

### ISSUE THREAD

**Issue by Hunter-CH3** [adityatelange/hugo-PaperMod#355]
PaperMod requires the latest Hugo version (v0.82) to run, otherwise user may run into `unexpected unclosed action in command`. This requirement is stated in wiki, but a user familiar with hugo themes may not refer to that webpage. Pointing it out in README.md may be better.

**Comment by adityatelange** [comment]
The fact that people don't want to read documentation is not so good feeling for a maintainer. Is it too much efforts to do it so ?
Never-mind I'll add it in the README :+1:
