### ISSUE TITLE
[BUG] social icons not rendering in Firefox

### ISSUE THREAD

**Issue by 1000283** [adityatelange/hugo-PaperMod#358]
**Describe the bug**

Having `ShowShareButtons: true` in config only works on Chromium but not Firefox.

 - Device/Os: Gentoo GNU/linux, amd64
 - Type: Desktop
 - Browser and version:  Chromium 89.0.4389.114 (Developer Build) (64-bit); Firefox 78.9.0esr (64-bit).
 - Hugo Version: hugo v0.83.0-DEV linux/amd64 BuildDate=unknown
 - Theme Version: master branch

**Screenshots**
attached
![papermod_chromium](https://user-images.githubusercontent.com/57144960/114767523-a32cac80-9d5f-11eb-9301-9f3bc7706e53.png)
![papermod_firefox](https://user-images.githubusercontent.com/57144960/114767525-a3c54300-9d5f-11eb-99b2-2aa5ca567055.png)

**Comment by 1000283** [comment]
Related to #283 ?

**Comment by 1000283** [comment]
Er.. after just checking out latest master (0430a98e74be0b850169b4ef3616d4b9cf6ce054) they stopped rendering in both browsers. Either i screwed up my config or something happened.

**Comment by adityatelange** [comment]
Works fine on my system.. FF 87.0 (64-bit) Firefox for Ubuntu. 

Can you see those with demo https://git.io/papermod_gh_demo ? I think this is system specific

**Comment by 1000283** [comment]
Indeed i _can_ see those on Firefox. Guess i borked my config somewhere.

**Comment by languitar** [comment]
In my case they vanish when uBlock origin is active.

**Comment by 1000283** [comment]
> In my case they vanish when uBlock origin is active.

You're absolutely right, disabling it for the site actually shows the social icons!

**Comment by languitar** [comment]
Does anyone know why they are blocked by a typical uBlock origin installation? The situation is not ideal this way.

**Comment by languitar** [comment]
Ok, I had a look at this. In my case this is caused by the Fanboy list that blocks `.social-icons`. Renaming this class should remove this problem.
