### ISSUE TITLE
Copy code button doesn't appear for many code blocks

### ISSUE THREAD

**Issue by kdkasad** [adityatelange/hugo-PaperMod#363]
> @kdkasad I just noticed this doesn't work with
> 
> ```yaml
> markup:
>     highlight:
>         lineNos: true
> ```
> 
> and code blocks not having a parent class `highlight` (ex. https://adityatelange.github.io/hugo-PaperMod/posts/markdown-syntax/)

It works fine with line numbers enabled for me. However you're right about it not working for non-`highlight` code blocks (i.e. ones indented with 4 spaces).

**Edit:** it also doesn't work for code blocks created using backticks with no syntax/language specified.

_Originally posted by @kdkasad in https://github.com/adityatelange/hugo-PaperMod/pull/345#issuecomment-817197431_

**Comment by adityatelange** [comment]
@kdkasad Should we revert existing code until this is fixed ? WDYT ?

**Comment by kdkasad** [comment]
> @kdkasad Should we revert existing code until this is fixed ? WDYT ?

Up to you. I'd lean towards no, since what we have works fine for what is probably the majority of cases.

I'll work on fixing this issue tomorrow, so it shouldn't be long anyways.

**Comment by zalexzperez** [comment]
Sorry to bump this issue, but I'm having trouble figuring out why I can get the copy code button to show up!

I'm using the latest Hugo version (v0.143.1) and I enabled the copy code buttons globally on my hugo.yaml file like this:

```
params:
    ShowCodeCopyButtons: true
```

Here's the test webpage: https://zalexzperez.github.io/
And this is the repository: https://github.com/zalexzperez/zalexzperez.github.io

Thanks in advance
