### ISSUE TITLE
[BUG] Error in build when using keywords variable

### ISSUE THREAD

**Issue by openact** [adityatelange/hugo-PaperMod#366]
**Describe the bug**

 - Device/Os: Windows
 - Type:  Desktop
 - Browser and version [e.g. Chrome 86.0]: 
 - Hugo Version [ >=0.82.0 expected]: 82
 - Theme Version [e.g. v4.0, master, or commit-id ]: Error in latest commits. Don't know exactly from which commit. But working without error for b6af9ed commit

**Steps to reproduce the behavior:**

1. Go to config.yml / toml file. I am using toml
2. use variable keywords = "blog". Checked inside and outside params.
3. Build

**Expected behavior**:

**Screenshots**

Build is not successful.

ERROR 2021/04/16 13:56:06 failed to render pages: render of "home" failed: execute of template failed: template: _default/list.html:5:8: executing "_default/list.html" at <partial "head.html" .>: error calling partial: "C:\Hugo\Sites\blog\themes\PaperMod\layouts\partials\head.html:15:84": execute of template failed: template: partials/head.html:15:84: executing "partials/head.html" at <.>: range can't iterate over blog

**Additional context**

**Comment by adityatelange** [comment]
We have mentioned here how to add keywords https://github.com/adityatelange/hugo-PaperMod/wiki/Installation#sample-configyml

`keywords` is not a single word but a list of words.

**Comment by openact** [comment]
@adityatelange  if I use keywords: [Blog, Portfolio, PaperMod] then error becomes

ERROR 2021/04/16 17:07:24 "C:\Hugo\Sites\blog\config.toml:50:1": unmarshal failed: Near line 50 (last key parsed 'params.keywords'): expected value but found "Blog" instead

**Comment by adityatelange** [comment]
@openact That is because that's not how it is used with toml 
https://learnxinyminutes.com/docs/toml/

**Comment by openact** [comment]
dumb I am.. Had used this previously but missed this time..  only changed colon to equal..
