### ISSUE TITLE
[BUG] Light Theme Background Color Inconsistencies

### ISSUE THREAD

**Issue by jamesgoodhouse** [adityatelange/hugo-PaperMod#369]
**Describe the bug**

When in "light" mode, the background color for posts appears to be slightly different than that of the rest of the pages. This inconsistency doesn't appear to exist when in dark mode, so I'm wondering if it's accidental or intentional?

 - Device/Os: MacOS
 - Type: Desktop
 - Browser and version: Chromium: 89.0.4389.114 (Official Build) (x86_64)
 - Hugo Version: 0.82.0
 - Theme Version: master

**Steps to reproduce the behavior:**

**Expected behavior**:

I would expect the colors to be consistent across all the different layouts.

**Screenshots**

<img width="841" alt="Screen Shot 2021-04-17 at 6 35 35 PM" src="https://user-images.githubusercontent.com/4684194/115131281-c481d880-9fab-11eb-908a-c9dd73b8a223.png">

**Additional context**

**Comment by adityatelange** [comment]
Yes this is intentional and not accidental.

**Comment by jamesgoodhouse** [comment]
oh ok, good to know. any additional context as to why this is the case for just the light theme?

**Comment by adityatelange** [comment]
> oh ok, good to know. any additional context as to why this is the case for just the light theme?

It's part of the design to be honest. You can't see the cards specifically if you don't have the bg in light theme, whereas this isn't the case in dark one.

**Comment by brianly** [comment]
@adityatelange Is there an easy way to make pages and posts consistent, if you want that appearance?

**Comment by adityatelange** [comment]
> @adityatelange Is there an easy way to make pages and posts consistent, if you want that appearance? 

IMO there's no point in consistency if it doesn't look good or rather better than what is is rn.

Also I don't want to make any abrupt changes to core colors and design of this theme as people who are currently using it (including myself) like the way it is (maybe not all).

Way out is ofc, people can and they should modify and tweak the theme the way they like it to be (I have also done this..). Hugo offers a flexible templating with a way overriding them easily.

**Comment by jamesgoodhouse** [comment]
I made some small tweaks via CSS to attempt to make things consistent. I didn't notice issues with elements not be clear enough or hard to see, but my page is rather basic at the moment.

**Comment by brianly** [comment]
@adityatelange That makes sense. I found a fix for my needs by modifying baseof.html, so the body class is "list" in all cases. This will help with further development.
