### ISSUE TITLE
Custom scripts to head and footer?

### ISSUE THREAD

**Issue by mukhtharcm** [adityatelange/hugo-PaperMod#37]
I there any way to add custom scripts to the header and footer of the site?
I have seen this feature in many themes.

ps: I am not try to spam this theme with issues. Sorry If you think so.

**Comment by adityatelange** [comment]
@mukhtharcm Tell me what you want to add css/js ? or just make some changes in existing css ? I'll explain how you can do it.

**Comment by mukhtharcm** [comment]
I am trying to add staticman to blog. 😉 
I am gonna fork and try to do it myself. 
if you can give me any advice, it'll be great. 😄

**Comment by adityatelange** [comment]
> I am gonna fork and try to do it myself.

Great ! I like your approach :)

---

You can also simply add css/js by copying head.html and footer.html to your websites directory and adding stuff you want
read https://zwbetz.com/override-a-hugo-theme/ .

---

This isn't merged but you can checkout how you can add custom css to existing one

https://github.com/adityatelange/hugo-PaperMod/commit/b56f6dc774f57e712077f2302d0f2198d7d3fa6b

**Comment by ITAYC0HEN** [comment]
What about providing an approach similar to LoveIt?
https://hugoloveit.com/theme-documentation-basics/#33-style-customization

From my experience, it gives the website owner a very nice experience of adding custom stylesheets without having to care about copying header files.

**Comment by adityatelange** [comment]
> What about providing an approach similar to LoveIt?
> https://hugoloveit.com/theme-documentation-basics/#33-style-customization
> 
> From my experience, it gives the website owner a very nice experience of adding custom stylesheets without having to care about copying header files.

@ITAYC0HEN cutom header and footer can be added !
If you will check commit logs you'll find it . I haven't documented it yet
