### ISSUE TITLE
rss feed does not take content of the posts

### ISSUE THREAD

**Issue by mrtrkmn** [adityatelange/hugo-PaperMod#372]
**Describe the bug**
When RSS enabled in profileMode, it does not take content of the posts.  Instead, it just brings titles and subtitles with post date and link. 

**Steps to reproduce the behavior:**
[mrturkmen.com/index.xml](https://mrturkmen.com/index.xml)

**Expected behavior**:

I am expecting to get everything like all post content. 

**Screenshots**

<img width="1350" alt="index xml" src="https://user-images.githubusercontent.com/13614433/115280683-dea8eb80-a150-11eb-9ed9-5cb4787a8137.png">

**Comment by adityatelange** [comment]
PaperMod has the template what HUGO ships with, by default. You can see here -> https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/_default/rss.xml

We have just added a override for the default one for not having pages such as `search` and `archives` in RSS feed.

**Comment by mrtrkmn** [comment]
I got it but that's a little bit weird actually, because in this context, it is not possible to import a blog post to another website through RSS, since it does not provide content of the post.
I am a little bit in doubt that what would be the purpose of this RSS feature then. 
Do not you think that RSS should include the post content as well ?

**Comment by adityatelange** [comment]
> I got it but that's a little bit weird actually, because in this context, it is not possible to import a blog post to another website through RSS, since it does not provide content of the post.
> I am a little bit in doubt that what would be the purpose of this RSS feature then. 
> Do not you think that RSS should include the post content as well ?  

I'm not aware if RSS is used for importing blog posts to another website. 

RSS is meant for providing quick short updates about the posts added. That includes summary, heading, date, etc.

IMO RSS is used for getting updates about the content being added on a website so that the reader remains updated about it. RSS makes it simpler because users don't need to add any of their personal details such as email to get the updates, instead RSS relies on client apps which fetches the feed periodically.

IMHO RSS was never meant to be a bypass for the users/readers to not visit the website and read all of the content via the feeds.

**Comment by mrtrkmn** [comment]
Well, I still think that it should include the content of posts, I have used to use Jekyll template earlier and there was no such a thing that RSS provides only summary, heading and date. 
I do not know which one is better or correct, but I think it is not good that RSS does not include content of the post.

**Comment by daSmirnov** [comment]
By default Hugo and most themes (but definitely not all!) will show the post summary in the RSS feed, getting full content is easy to achieve however just edit the below in your install.

/themes/PaperMod/layouts/_default/rss.xml and change line 47 to:

`      <description>{{ .Content | html }}</description>

Could get into debate about the best default. Back in the early 2000s it was rare to see anything but full content in feeds, but as it became more popular with websites that had an ad driven business model so it was more used to drive traffic to those websites. I role with full content as it just makes things more open and accessible - plus I read almost entirely in an RSS reader, and avoid hitting websites where possible as the reading experience usually isn't as good. I'm much more likely to subscribe to a site with full content. :-)

**Comment by mrtrkmn** [comment]
@daSmirnov thanks for your input, however your proposal does not seem working. However, yeah it is easy to fix I agree, nevertheless, it would be nice to have it in the theme repository as a support to have. For this reason, I will not change it on my local for now. I hope, @adityatelange  has a plan about it.

**Comment by adityatelange** [comment]
> @daSmirnov thanks for your input, however your proposal does not seem working. However, yeah it is easy to fix I agree, nevertheless, it would be nice to have it in the theme repository as a support to have. For this reason, I will not change it on my local for now. I hope, @adityatelange  has a plan about it. 

Maybe we can add an option to enable full post contents with `.Content` as said in above comment. However it would be difficult to track _upstream_ template changes by Hugo. 
Also IDK about how fine this would work with non text objects in the post.

**Comment by mrtrkmn** [comment]
Thanks @adityatelange for the update !
