### ISSUE TITLE
Start a GitHub sponsors program

### ISSUE THREAD

**Issue by bee-san** [adityatelange/hugo-PaperMod#376]
Hey,

I'd love to sponsor this project. Can you make a github sponsors account, please? :) 

https://github.com/sponsors

**Comment by adityatelange** [comment]
Thank you @bee-san for wanting to sponsor this project, I really appreciate it!

But unfortunately there's no way I could receive sponsorships via GitHub as this service isn't available for country I reside in (India). :(

![6729.png](https://user-images.githubusercontent.com/21258296/115540362-a2de6500-a2bb-11eb-9683-55636b3ddb6d.png)
