### ISSUE TITLE
[BUG] Space after images

### ISSUE THREAD

**Issue by tunix** [adityatelange/hugo-PaperMod#377]
**Describe the bug**

When an image is placed inside the content, there seems to be no margin/padding added by default which causes the image be very close to the paragraph underneath.

 - Device/Os: Ubuntu 20.10
 - Type: Desktop
 - Browser and version: Firefox 88.0
 - Hugo Version: hugo v0.83.0-DEV-243951EB+extended linux/amd64 BuildDate=2021-04-22T17:07:16Z
 - Theme Version: master (commit: fb0393fa125f04e95d54d8ed32ed817e861876da)

**Steps to reproduce the behavior:**

Place the following code piece before a paragraph:

```
{{< figure src="path/to/image.png" >}}
```

**Expected behavior**:

A default margin/padding should be applied to the image.

**Screenshots**

![image](https://user-images.githubusercontent.com/47731/115932777-45ead680-a496-11eb-8152-bef2d52cdc7b.png)

**Comment by kdkasad** [comment]
I checked and this wasn't introduced by my changes in #247, so it's up to @adityatelange whether he wants to change the style.
