### ISSUE TITLE
[BUG] `rss+xml` in <head><link> is encoded into `rss&#43;xml`

### ISSUE THREAD

**Issue by JannikArndt** [adityatelange/hugo-PaperMod#392]
**Describe the bug**

The `<link>` tag gets a "safe url" encoding:

```html
<link rel="alternate" type="application/rss&#43;xml" href="/index.xml">
```

 - Device/Os: MacOS 11.3
 - Hugo Version [ >=0.82.0 expected]: `hugo v0.82.1+extended darwin/amd64 BuildDate=unknown`
 - Theme Version [e.g. v4.0, master, or commit-id ]: `master`

**Steps to reproduce the behavior:**

Works on `master`:

```shell
$ git clone https://github.com/adityatelange/hugo-PaperMod.git
…
$ cd hugo-PaperMod
$ hugo
…
$ tail -n +20 public/index.html | head -n 5 
```
gives you
```html
<meta name="msapplication-TileColor" content="#2e2e33">
<meta name="generator" content="Hugo 0.82.1" />
<link rel="alternate" type="application/rss&#43;xml" href="/index.xml">
<meta property="og:title" content="" />
<meta property="og:description" content="" />
```

**Expected behavior**:

It should be 

```html
<link rel="alternate" type="application/rss&+xml" href="/index.xml">
```

**Additional context**

The implementation is exactly as specified in the docs: <link rel="alternate" type="application/rss&#43;xml" href="/index.xml">

**Potential fix**

This _does_ work on 
```html
<atom:link href="/categories/index.xml" rel="self" type="application/rss+xml" />
```
which is generated differently. 
The same can be done in `head.html` with

```go
{{ printf "<link rel=%q type=%q href=%q>" .Rel .MediaType .Permalink | safeHTML }}
```

**Comment by adityatelange** [comment]
This is weird. 
As you said - The implementation is exactly as specified in the docs.
Don't you think this should be reported to HUGO?

**Comment by JannikArndt** [comment]
> Don't you think this should be reported to HUGO?

Probably, but I didn't have time to dive _that_ deep 😅 

>This can be easily fixed by .MediaType.Type | html

Aaahhh I tried `safeURL` and `safeHTML` 🙈 I updated #393 to use this smaller change.
