### ISSUE TITLE
[BUG] Missing Aliases

### ISSUE THREAD

**Issue by chris-short** [adityatelange/hugo-PaperMod#395]
**Describe the bug**

 - Device/Os: macOS 11.3
 - Type: [e.g. Desktop/Mobile] Desktop
 - Browser and version [e.g. Chrome 86.0]: Brave Version 1.23.73 Chromium: 90.0.4430.85 (Official Build) (x86_64)
 - Hugo Version [ >=0.82.0 expected]: 0.83.0
 - Theme Version [e.g. v4.0, master, or commit-id ]: Unknown

**Steps to reproduce the behavior:**

Build a site with aliases in content frontmatter

**Expected behavior**:

Aliases should create pages that redirect to the desired URL.

**Screenshots**

N/A

**Additional context**

Aliases seem to not be created.

**Comment by adityatelange** [comment]
I am not sure why they aren't working for you. 
Aliases is a hugo feature and PaperMod doesn't have any control over it. 

Please refer to hugo docs about aliases here
https://gohugo.io/content-management/urls/#aliases

What I guess is you're missing something with the syntax. Aliases is of `list` type and may not work with `strings`.
