### ISSUE TITLE
I want to show 5 posts in per page,what can I do to make it happen?

### ISSUE THREAD

**Issue by PwnerZhang** [adityatelange/hugo-PaperMod#399]
Just like https://adityatelange.github.io/hugo-PaperMod/
then I click the button 《Next Page》,it shows the next 5 posts for me.
I have read the documents,but I have not found the solution.

**Comment by kdkasad** [comment]
Many things are not theme-specific, so you should also read the Hugo docs:
https://gohugo.io/templates/pagination/#configure-pagination

**Comment by PwnerZhang** [comment]
Sorry.Thanks for your reply.
