### ISSUE TITLE
Feature request: allow customization of logo URL

### ISSUE THREAD

**Issue by kishorenc** [adityatelange/hugo-PaperMod#400]
Thanks for this great theme. 

When people host the blog on a `/blog` subdirectory, the logo link usually points to the primary website at `/` (this is a very common pattern). However, with the way the header partial is templated at the moment, the logo link seems to rely on the base url:

```
<a href="{{ "" | absLangURL }}" accesskey="h" title="{{ $label_text }} (Alt + H)">
```

Making this customizable will help a lot of people.

**Comment by adityatelange** [comment]
According to hugo docs, we should use baseURL like : 
```yml
baseURL: "https://example.site/blog/"
```

That way "logo link" will point to correct path

**Comment by kishorenc** [comment]
@adityatelange What I meant is that often the logo link points to a **different** link than the `baseURL` link. For e.g. see this page: https://fly.io/blog/livebook-for-app-documentation/

The logo on the top left corner actually points to the homepage URL and **not** the blog URL. So the `href` attribute value in the following snippet should be made customizable:

```
<a href="{{ "" | absLangURL }}" accesskey="h" title="{{ $label_text }} (Alt + H)">
```
