### ISSUE TITLE
Feature request: Image gallery

### ISSUE THREAD

**Issue by HariprasadManimozhi** [adityatelange/hugo-PaperMod#413]
Hi @adityatelange 
Building the feature of "image gallery", by creating a gallery of all images in a directory as a part of this theme would make this theme more useful & robust.
May I know if this feature is anywhere on the roadmap? 
If not, kindly request to accept my request of developing this feature. Thanks in advance. 

Looking forward to your response.

**Comment by kdkasad** [comment]
This has been mentioned before in #330. However, if you can do it with no external scripts/libraries, go ahead. If @adityatelange doesn't want to add it to the theme, at least you'd have it for your site.

**Comment by geronimo-iia** [comment]
I have the same needs and to do that I've introduce this pull request: https://github.com/adityatelange/hugo-PaperMod/pull/438 in order to include dedicated external js like slick or PhotoSwipe without adding them to this project.

**Comment by adityatelange** [comment]
No plans to add sorry 🙂
