### ISSUE TITLE
Bold markdown doesn't work

### ISSUE THREAD

**Issue by hwwilliams** [adityatelange/hugo-PaperMod#42]
![image](https://user-images.githubusercontent.com/20447447/96348802-65cdb780-1079-11eb-99de-c0f7ea0d971a.png)

**Comment by adityatelange** [comment]
![3388.png](https://user-images.githubusercontent.com/21258296/96348941-f338f800-10c9-11eb-96e3-1fd54e233ff9.png)

hmm ... ?!
That is Bold, on my device.

**Comment by hwwilliams** [comment]
Apologies, it seems to be an issue on my Firefox.

**Comment by adityatelange** [comment]
> Apologies, it seems to be an issue on my Firefox.

Firefox desktop ? 
As, I took that snap from, FF mobile client !

**Comment by hwwilliams** [comment]
Yes it does work fine for me on Chrome, Firefox mobile, and Safari. It doesn't work on my Firefox desktop instance.

**Comment by adityatelange** [comment]
> Yes it does work fine for me on Chrome, Firefox mobile, and Safari. It doesn't work on my Firefox desktop instance.

![image](https://user-images.githubusercontent.com/21258296/96349497-bd960e00-10cd-11eb-90b6-1e55de442f46.png)

Just tried on FF desktop 82.0 (64-bit), it works as expected maybe something wrong on your end.
