### ISSUE TITLE
Extra space causing issues in Cloudflare Pages build

### ISSUE THREAD

**Issue by adyanth** [adityatelange/hugo-PaperMod#426]
I am trying to build a static site with cloudflare pages, and the build fails with:
```
<!--StartFragment-->
19:20:31.838 | Installing Hugo 0.54.0
-- | --
19:20:32.402 | Hugo Static Site Generator v0.54.0-B1A82C61A/extended linux/amd64 BuildDate: 2019-02-01T10:04:38Z
19:20:32.403 | Started restoring cached go cache
19:20:32.406 | Finished restoring cached go cache
19:20:32.434 | go version go1.14.4 linux/amd64
19:20:32.440 | go version go1.14.4 linux/amd64
19:20:32.442 | Installing missing commands
19:20:32.442 | Verify run directory
19:20:32.443 | Executing user command: hugo --gc --minify
19:20:32.489 | Error: "/opt/buildhome/repo/themes/PaperMod/layouts/partials/toc.html:71:1": parse failed: template: partials/toc.html:71: illegal number syntax: "-"
19:20:32.492 | Failed: build command exited with code: 255

<!--EndFragment-->

```
This seems to point to an extra space here:
https://github.com/adityatelange/hugo-PaperMod/blob/573e673efae17255fc46ae44670de9ce51faf9d8/layouts/partials/toc.html#L71

`"#{{- $cleanedID  -}}"` should be `"#{{- $cleanedID -}}"` ?

I do see that the version used by cloudflare is old (even thought I set the environment variable to 0.83.1), but that should not be causing the builds to fail, right?

**Comment by adyanth** [comment]
Apparently the environment variables aren't saved until the site is saved. After that, in the new Hugo version, there weren't any errors. That space still seems out of place, but if nothing else, this issue can be closed.

**Comment by adityatelange** [comment]
I never faced such error on newer `hugo` versions. I recommend using `hugo 0.82+` with this theme.
