### ISSUE TITLE
[Feature Request] Make social media share buttons customizable

### ISSUE THREAD

**Issue by miynat** [adityatelange/hugo-PaperMod#431]
When I use `ShowShareButtons: true`, all the social media share buttons are shown.

Let's say, I would like to use Twitter and Linkedin share buttons, but not the others. How can I achieve that?

Is it possible to make these buttons customizable?

**Comment by stclj** [comment]
This would be great!

**Comment by adityatelange** [comment]
We can do this by having an list `[ ]` having values as names of platforms we have icons of inside it.
Ex. socialcons: ["whatsapp"]
But would it look nice? Imagine having only 2 small buttons down there.

Better option would be to simply disable the share icons and let the reader share it however they want.

**Comment by miynat** [comment]
I think, making it selectable, and letting the blog owner decide which ones to select (rather than making it a single on-off decision) will make it more user-friendly.

On the other hand, disabling it completely, and making that share process totally manual will decrease the social interaction, IMO.

**Comment by besendorf** [comment]
Thanks a lot for this feature. I think this should be documented in the Wiki
