### ISSUE TITLE
[documentation] copyright for config.yml is undocumented

### ISSUE THREAD

**Issue by aemacleod** [adityatelange/hugo-PaperMod#432]
Thanks for a great theme. I was playing around and noticed a helpful but undocumented feature for changing the copyright notice in the footer using config.yml. If we have the following config lines:
```
baseURL: "https://example.com"
title: example blog
#copyright: "**[time.gov](https://time.gov)**"
```
The footer will render as "© 2021 [example blog](https://example.com)" using the title and baseURL by default, but if we uncomment/add the copyright line it will render as a customizable markdown-able link.

**Comment by adityatelange** [comment]
Thank you @aemacleod. I have added that here https://github.com/adityatelange/hugo-PaperMod/wiki/Variables#site-variables
