### ISSUE TITLE
Incomplete PL translation at some places

### ISSUE THREAD

**Issue by develladin** [adityatelange/hugo-PaperMod#437]
Hello, I'm building a blog with this theme and I must have Polish translation. I know PL translation exists, but it's incomplete at places below:
- `Archive`, `Tags`, `About Me` and other Default Pages (propeties like date and its contents too)
- Copyright at footer
- Suggest changes

and I guess a lot more. Let me know what you think about this 🙂

**Comment by adityatelange** [comment]
Yeah, it is incomplete. I don't think it will ever be a fully translated one.

- For date, there are limitations to hugo's translation and so will be for this theme. 
- Archive, Tags, About Me, Suggest changes ? If you are talking about title, you can change it, per language.
- Yeah copyright has "powered by" in english, but is it a problem if you have a small line in bottom of page? I don't think so :slightly_smiling_face:
