### ISSUE TITLE
AWS Amplify build issue

### ISSUE THREAD

**Issue by LeninGangwal** [adityatelange/hugo-PaperMod#45]
Hi,
The local build works fine, but deploying on AWS Amplify causes this error.

` Error: "/codebuild/output/src304702036/src/blog/themes/hugo-PaperMod/layouts/partials/toc.html:65:1": parse failed: template: partials/toc.html:65: illegal number syntax: "-"`

There is an extra space in line 65. I am not sure why my local build(Mac) works fine but the one on AWS does not.

**Comment by adityatelange** [comment]
Hi @LeninGangwal,
Can you please check hugo versions you are using ? It seems like your Mac and AWS have different versions.
Let me know.

**Comment by LeninGangwal** [comment]
You are right. I tried using the "latest" version, but there is a bug aws amplify, and we need to specify the exact version.
For future references:
https://github.com/aws-amplify/amplify-console/issues/820

**Comment by LeninGangwal** [comment]
Thanks a lot for this template! Closing this.
