### ISSUE TITLE
GoogleAnalytics is enable on development, it is expected to only work  on production[BUG]

### ISSUE THREAD

**Issue by leezicai** [adityatelange/hugo-PaperMod#457]
**Describe the bug**

 - Device/Os: Mac hugo 0.85 
 - Type: Desktop
 - Browser and version : Chrome 91.0
 - Hugo Version [ >=0.82.0 expected]: 0.85 
 - Theme Version [e.g. v4.0, master, or commit-id ]: 09accb9566ff4029270d2659c13942ff9dfc5536

**Steps to reproduce the behavior:**

**Expected behavior**:

Environment: "development, GoogleAnalytics should be  disabled. 

**Screenshots**

**Additional context**

![image](https://user-images.githubusercontent.com/48158066/124583115-4388fd80-de85-11eb-9b6e-dd10d7ac072e.png)

**Comment by adityatelange** [comment]
Do you have `.Site.Params.env` set to  `production` ?

https://github.com/adityatelange/hugo-PaperMod/blob/09accb9566ff4029270d2659c13942ff9dfc5536/layouts/partials/head.html#L120-L126

**Comment by leezicai** [comment]
> Do you have `.Site.Params.env` set to `production` ?
> 
> https://github.com/adityatelange/hugo-PaperMod/blob/09accb9566ff4029270d2659c13942ff9dfc5536/layouts/partials/head.html#L120-L126

yes, i hava
![image](https://user-images.githubusercontent.com/48158066/124582216-6830a580-de84-11eb-90d3-eb3c4c32cfb0.png)

**Comment by leezicai** [comment]
My markdown file is a draft type, and it is not pushed to the website, just local.

**Comment by adityatelange** [comment]
@leezicai I cannot reproduce this issue, does not load GA scripts on development server.
