### ISSUE TITLE
[feature request] responsive navigation menue

### ISSUE THREAD

**Issue by techducks** [adityatelange/hugo-PaperMod#458]
Hello there, 

is there any plan to design the navigation menue "more responsive"?

I mean that you don't need to scroll throw the menue list. If the screen is to small it will pop up a navigation symbol and if you press it it will open the menue.

Here is an example: 

https://ublogger.netlify.app/

if this is doesn't fit with your themes main idea just close this issue.

**Comment by adityatelange** [comment]
Already answered here https://github.com/adityatelange/hugo-PaperMod/discussions/379#discussioncomment-653849

**Comment by techducks** [comment]
oh sorry ... i searched for similar requests :D Maybe i am blind

i can unterstand your reasons, but when thinking about "mobile first" this is the only thing missing in your theme.

But this is your theme. Feel free to close my issue. i am using your theme anyways 👍🏻 Thank you for your work

**Comment by schwrzstrbn** [comment]
> oh sorry ... i searched for similar requests :D Maybe i am blind
> 
> i can unterstand your reasons, but when thinking about "mobile first" this is the only thing missing in your theme.
> 
> But this is your theme. Feel free to close my issue. i am using your theme anyways 👍🏻 Thank you for your work

Making the responsive hamburger menu optional is not a bad idea. It'll be up to the users of the theme to whichever they prefer.
