### ISSUE TITLE
Localization of months for archives page

### ISSUE THREAD

**Issue by Northerner-coder** [adityatelange/hugo-PaperMod#46]
Current archives page great, however names of the month are always in English, which is an issue for non-English blogs. I couldn't find any out-of-the-box way to localize it.  The only thing that comes to mind is to pass the month name through i18n which should contain the correct translation. 

![image](https://user-images.githubusercontent.com/50540933/96374839-413e1200-1143-11eb-8793-9d79e2ccba29.png)

Hugo official documentation suggests using data files with an array of month names: https://gohugo.io/content-management/multilingual/#customize-dates .  I see two issues with this approach.  First, it does not look very clean to me: if we use i18n for translation already, I see no reason to separate translation of month into a different mechanism.  Second, it will not work in archives.html as we are working with array key rather than with date object.

Does anybody know of a better or already existing way? Would like to fix this issue for the theme but do not want to reinvent the wheel )

**Comment by adityatelange** [comment]
@Northerner-coder Take a look at #48.
Actually I had this thing in my mind but never pushed it as no one requested :p 

The `i18n` idea is more of a time consuming process, I think if user wants his/hers website localized best way is add the months yourself for language needed 
The linked PR does that. 

Also can you test the code out for your native language and let me know if it goes well. 

Thank You.
~ Aditya

**Comment by Northerner-coder** [comment]
@adityatelange Thank you!  Checked the https://github.com/adityatelange/hugo-PaperMod/pull/48 - works like a charm.

Main advantage of `i18n` before this solution: it will work out-of-the-box if filled in the localization file, user needs only to choose the language.  Additionally, all localization stays in one place, leaving config with more settings and less content directives.

Do you mind if I test `i18n` option out to see whether and how it works in practice?  After that you can decide which option to use.

**Comment by adityatelange** [comment]
@Northerner-coder even if we add i18n we cannot support each and every language.
Translations can be tough, words mean different than the actual action that the keyword button does.
After this I am even thinking to rule of i18n and let the user choose the keywords they want. What do you think ? 

Hugo's Internationalisation never worked out of the box, there are few things yet to be implemented.

**Comment by Northerner-coder** [comment]
> After this I am even thinking to rule of i18n and let the user choose the keywords they want. What do you think ?

Sorry, didn't get the part about choosing the 'let the user choose the keywords'.

**Comment by adityatelange** [comment]
> > After this I am even thinking to rule of i18n and let the user choose the keywords they want. What do you think ?
> 
> Sorry, didn't get the part about choosing the 'let the user choose the keywords'.

I mean let the user choose the translations for words on the buttons if they aren't listed

**Comment by adityatelange** [comment]
Also I am rethinking about PR #48, 
This will only add month translations to archive page, 

We can add to other elements too but hugo supports multiple formats for date 
This format can be applied only to a few( not `Mon Jan 2 2006` , not `Mon, 02 Jan 2006 15:04:05 -0700`, moreover the days, will remain as it is.

**Comment by Northerner-coder** [comment]
> > > After this I am even thinking to rule of i18n and let the user choose the keywords they want. What do you think ?
> 
> > 
> 
> > Sorry, didn't get the part about choosing the 'let the user choose the keywords'.
> 
> 
> 
> I mean let the user choose the translations for words on the buttons if they aren't listed

I guess it means adding i18n for all interface text.  As far as I understand this is a standard way for multi-language support.

**Comment by Northerner-coder** [comment]
> Also I am rethinking about PR #48, 
> 
> This will only add month translations to archive page, 
> 
> 
> 
> We can add to other elements too but hugo supports multiple formats for date 
> 
> This format can be applied only to a few( not `Mon Jan 2 2006` , not `Mon, 02 Jan 2006 15:04:05 -0700`, moreover the days, will remain as it is.

The issue with localized date is a Go problem in general. There are packages that allow to sort it out. I do not think that it is feasible to use them in Hugo theme context. 

Yes, months translation will be limited to archives and any other cases where month should be written in full (none at the moment). 

As to dares in general, I proposed date format exactly to avoid commotion with the dates localization.  For instance in Russia it is customary to use date format 18.10.2020. Using digits only I am not concerned with the localization.  This is a half measure, but an effective one.

**Comment by adityatelange** [comment]
> I guess it means adding i18n for all interface text. As far as I understand this is a standard way for multi-language support.

Yes it is a standard way but the problem is we cannot translate over languages people use, so it might be better to give them a choice to add their own translations for themselves without touching the `i18n` directory, but from` config.yml` itself, 

As we can have [multople config file](https://gohugo.io/getting-started/configuration/#configuration-directory) user could add a `config.tranlate.yml` so that preferred translations could be used

**Comment by Northerner-coder** [comment]
@adityatelange tried alternative implementation for months translation via i18n https://github.com/adityatelange/hugo-PaperMod/pull/50 - for better comparison.

Sure, translations can be done in config as well.  However i18n provides additional functionality for translations, for instance including integer inside of a translation string and multiple options depending on the integer (one, many, etc.).  I am not sure that it is easy to implement via config.

**Comment by ZzMark** [comment]
consider to using js: moment  or dayjs ?

defect:
 - not static
 - need some language pack

**Comment by adityatelange** [comment]
> consider to using js: moment or dayjs ?
> 
> defect:
> 
> * not static
> * need some language pack

Yes, it hinders performance.
