### ISSUE TITLE
[BUG] ShowCodeCopyButtons doesn't work with Asciidoc

### ISSUE THREAD

**Issue by marioortizmanero** [adityatelange/hugo-PaperMod#463]
**Describe the bug**

The `copy` button should be available when hovering over the code snippet: 

![image](https://user-images.githubusercontent.com/25647296/124802748-98e20f00-df58-11eb-9fc4-672849d41494.png)

See how it's available in the HTML:

![image](https://user-images.githubusercontent.com/25647296/124802913-c333cc80-df58-11eb-8d0a-1963f3beb448.png)

But this doesn't happen if the article is written with [asciidoc](https://asciidoctor.org/) because the HTML is slightly different:

![image](https://user-images.githubusercontent.com/25647296/124802991-d9418d00-df58-11eb-9a57-f2184f4eaea7.png)

This is because the JS code in `layouts/partials/footer.html` doesn't take asciidoc into account.

**Comment by adityatelange** [comment]
Can you explain what do you use `asciidoc` for? It works fine on Hugo, as this theme is intended to work with Hugo.

**Comment by marioortizmanero** [comment]
Hugo supports asciidoc: https://gohugo.io/content-management/formats/. It's just another format like markdown. 

But it generates a slightly different HTML, so it doesn't work out of the box with things like this.

**Comment by marioortizmanero** [comment]
Uh, don't ask me why or how, this seems to be working now. Closing this.
