### ISSUE TITLE
[Feature Request] Floating table of contents

### ISSUE THREAD

**Issue by zznewclear13** [adityatelange/hugo-PaperMod#465]
Hello,

I think it might be nice to have a floating table of contents next to the article. Any plans for that?

**Comment by adityatelange** [comment]
No plans sorry 🙂

**Comment by dadav** [comment]
Did anyone create a template for this and could share it? :)

**Comment by zznewclear13** [comment]
> Did anyone create a template for this and could share it? :)

@JannikArndt made a floating toc for [his website](https://www.jannikarndt.de/blog/2021/08/comparison_of_chart_libraries_for_swiftui/). Maybe he would like to share it.

**Comment by dadav** [comment]
> > Did anyone create a template for this and could share it? :)
> 
> @JannikArndt made a floating toc for [his website](https://www.jannikarndt.de/blog/2021/08/comparison_of_chart_libraries_for_swiftui/). Maybe he would like to share it.

Woah, thanks for this hint, I think I found the commit: https://github.com/JannikArndt/jannikarndt.github.io/commit/8b99f6cbc61c6b4f0238c592d5315cefe07c0599

**Comment by JannikArndt** [comment]
Glad I could help 😊 If you find improvements for it (my css-skills are _really_ basic), let me know!
Also: Anyone may copy, change, improve the code and if it should be good enough, propose it as a PR to this theme 😉

**Comment by zznewclear13** [comment]
> Glad I could help 😊 If you find improvements for it (my css-skills are _really_ basic), let me know! Also: Anyone may copy, change, improve the code and if it should be good enough, propose it as a PR to this theme 😉
Thanks for your sharing! I am using your template in [my web pages](https://zznewclear13.github.io/posts/draw-equal-width-outline-in-unity/). I modified it a little bit to hide the table of contents when not `@media (min-width: 1280px)`.

**Comment by zznewclear13** [comment]
> Glad I could help 😊 If you find improvements for it (my css-skills are _really_ basic), let me know! Also: Anyone may copy, change, improve the code and if it should be good enough, propose it as a PR to this theme 😉

Thanks for your sharing! I am using your template in [my web pages](https://zznewclear13.github.io/posts/draw-equal-width-outline-in-unity/). I modified it a little bit to hide the table of contents when not `@media (min-width: 1280px)`.
