### ISSUE TITLE
The Arabic translation is incomplete!

### ISSUE THREAD

**Issue by AboTyim** [adityatelange/hugo-PaperMod#466]
Some words can not translate like (Categories, tags, Series)

![image](https://user-images.githubusercontent.com/8638284/125590356-fde0f17b-fe1a-4ce7-a83d-999bf5251a90.png)

**Comment by kszpieg** [comment]
There was a similar issue #373

**Comment by AboTyim** [comment]
![image](https://user-images.githubusercontent.com/8638284/126678156-513c60bc-71eb-4a0d-a360-c6d8368649f0.png)

When I applied the steps, the problem was solved, but there is another problem, which is that the tags do not appear

**Comment by ahmedselim2017** [comment]
Hi, I got the same problem with Turkish too

**Comment by adityatelange** [comment]
@AboTyim @ahmedselim2017 

Can you try this ?

Create `content/tags/_index.md`

and put

```yml
---
title: Whatever you want
---
```

**Comment by AboTyim** [comment]
Thanks
