### ISSUE TITLE
404 page not found

### ISSUE THREAD

**Issue by michaelsync** [adityatelange/hugo-PaperMod#477]
I just cloned this repo, switch the branch to exampleSite and run the project "hugo server". It shows as below.

![image](https://user-images.githubusercontent.com/192911/126774616-931079d8-1c4b-4d3b-9054-b078c496458f.png)

I am on Windows 10.  My hugo version are ~ 

Hugo: 0.86.0
Hugo Extended: 0.86.0

![image](https://user-images.githubusercontent.com/192911/126774641-1a3e98e1-ea2e-42ff-a0a8-a7136711bbe2.png)

![image](https://user-images.githubusercontent.com/192911/126774722-46b2f8ba-e164-44df-b308-7dd5de74881d.png)

**Comment by sarkrui** [comment]
I experienced the same issue when `hugo server` on exampleSite but later it's fixed by 
```bash
git submodule init
git submodule update
```
(source: https://stackoverflow.com/a/65745209)
