### ISSUE TITLE
Language switcher menu

### ISSUE THREAD

**Issue by mehdy** [adityatelange/hugo-PaperMod#49]
I think a global language switcher menu is needed to let the user switch between different language home pages and not just only the translated posts.

**Comment by adityatelange** [comment]
I am not against language switch, but I am against menus.
Also it seems like there is very little space lest over which switch can be added.

Design point of view a/c to paper, is keep is plain as possible, this is the uniqueness ig which me and you guys like :)
This is the reason I had that "Also read in" kind of on each post when user wishes to read it in another language.
Also the home-permalink stays on selected language so that once switched, user need not to go back to default language again.
Let me know your thoughts on this.

~ Aditya

**Comment by mehdy** [comment]
You're absolutely right. I don't want to sacrifice the simplicity either.

My problem is that I'm not using the multilingual feature for translations where each post has its own counterpart. I'm blogging in two languages as I if I'm running two separate blogs. So instead of translations for each post, I need a link somewhere to let the users know there are other posts I've written.

**Comment by adityatelange** [comment]
@mehdy 

WDYT about this ..
![image](https://user-images.githubusercontent.com/21258296/96493082-27472100-1262-11eb-8b1c-538dfc53a368.png)

**Comment by mehdy** [comment]
Between these two I like the second one better.

I was thinking about providing something like `profileMode.buttons` for `homeInfoParams`.

And an ability to provide language selection via these buttons.

What do you think?

**Comment by adityatelange** [comment]
> Between these two I like the second one better.

Me too

--- 
> I was thinking about providing something like `profileMode.buttons` for `homeInfoParams`.
> 
> And an ability to provide language selection via these buttons.
> 
> What do you think?

We can add it so that _any link_ can be added as a button, not just for language selection :wink: 
But will have to think about design part, **HomeInfo** isn't meant for other stuff leaving texts about personal info/ blog info / welcome messages.

**Comment by mehdy** [comment]
Well, I think letting users know there are other languages available as well, is part of the welcome messages or the blog info, isn't it?

**Comment by adityatelange** [comment]
> Well, I think letting users know there are other languages available as well, is part of the welcome messages or the blog info, isn't it?

Sure, you are correct. But if we are implementing a feature, it should be accessible to other modes too !

**Comment by mehdy** [comment]
@adityatelange You're right.
By the way, thank you for the PR! :)

**Comment by adityatelange** [comment]
> @adityatelange You're right.
> By the way, thank you for the PR! :)

@mehdy PR #54 is ready to be merged, can you check any glitches are present, using your multilingual config ?

**Comment by mehdy** [comment]
@adityatelange Nice! I'll look into it.

**Comment by mehdy** [comment]
@adityatelange I checked everything. Works fine on both RTL and LTR languages. both on desktop and mobile. The only thing I could think of was what if the title was too long on mobile. In this situation, although does not apply to me, it's not working properly.

**Comment by adityatelange** [comment]
> @adityatelange I checked everything. Works fine on both RTL and LTR languages. both on desktop and mobile. The only thing I could think of was what if the title was too long on mobile. In this situation, although does not apply to me, it's not working properly. 

Yeah ik.. the thing is it's breaking aesthetics.
You know that it could not fit in some other place right ? 

Also if it was in the navbar it is difficult for a first time visiter who doesn' know the language well, to scroll and get navigated to translated page..(in case where menu has lot of links in it ) 

suggestions are welcome :)

**Comment by adityatelange** [comment]
> @adityatelange I checked everything. Works fine on both RTL and LTR languages. both on desktop and mobile. The only thing I could think of was what if the title was too long on mobile. In this situation, although does not apply to me, it's not working properly.

@mehdy should be fine now..

**Comment by mehdy** [comment]
@adityatelange Thanks. Works like a charm!

**Comment by adityatelange** [comment]
> @adityatelange Thanks. Works like a charm!

@mehdy Merged :)
