### ISSUE TITLE
Is line highlighting supported?

### ISSUE THREAD

**Issue by johnnymetz** [adityatelange/hugo-PaperMod#500]
In other themes, I can highlight a specific line of code (using two backticks below instead of three for display purposes):

```
```python {hl_lines=[2]}
def hello(name):
    print(f"Hello {name}!")
``
```

Which renders something like this:

![Screen Shot 2021-08-13 at 12 28 06 AM](https://user-images.githubusercontent.com/20693145/129320613-6c5a710c-2ef2-4dba-945f-19fef519b9f5.png)

However, using this theme I don't see any highlight on line 2:

![Screen Shot 2021-08-13 at 12 27 28 AM](https://user-images.githubusercontent.com/20693145/129320635-88a39291-f139-42d5-a72f-927357d3d5c9.png)

Is this a bug or is this not supported?

**Comment by xiaogit00** [comment]
facing the same problem
