### ISSUE TITLE
[BUG] Comments section not appearing on post page

### ISSUE THREAD

**Issue by aormsby** [adityatelange/hugo-PaperMod#502]
**Describe the bug**

I've enabled comments in my config file and included the internal Disqus template in the comments partial as needed, but the comment section does not appear on my posts. It's a fresh site, so not much other config.

`config.toml`
```toml
disqusShortname= "my_shortname"
[params]
    comments = true
```

`layouts/partials/comments.html`
```html
{{ template "_internal/disqus.html" . }}
```

To narrow down the problem, I tried a few things. I ran the internal template on another theme, worked fine. I changed the `comments.html` file to just have some text like 'hello world', and it appeared fine. But when I went back to the internal disqus template as recommended,  nothing showed up on the page (and nothing appeared in the HTML source, either). I think maybe your theme is somehow not accessing the internal template correctly. Not sure.

 - Device/Os: MacBook Air (M1, 2020), MacOS Big Sur v11.4
 - Type: Desktop
 - Browser and version: Brave Browser, Version 1.27.109 (also did not work in Safari, browser agnostic)
 - Hugo Version: hugo v0.87.0+extended darwin/arm64
 - Theme Version: 7d67d64b

**Steps to reproduce the behavior:**

1. Create new hugo site
2. Install paper mod theme
3. Enable comments in config
4. Set internal disqus template in comments.html
5. Add some quick test posts
6. Run hugo server

**Expected behavior**:
When running hugo server, I should at least see a text display at the end of the post about Disqus comments being disabled on localhost.

**Comment by rcdailey** [comment]
comments has to be under `params` I think.

**Comment by aormsby** [comment]
Oh, I do have the variable under params, and I have edited the original post to make that clear.

But as you can see in this short video, the internal template for the disqus element fails to display anything. I prove that your theme's partial and variables work by putting hello world in there, but the comments section won't display with the template in use.

https://user-images.githubusercontent.com/1312251/129627013-06916774-09e6-42a7-9ee1-ee5e01f2cb56.mov

**Comment by drizzl4** [comment]
i just tried it in yml, and didn't find any problem

**Comment by danielfdickinson** [comment]
In toml it is an error to have a key-value pair (``disqusShortname = "admonormsby"``) after a map (such as ``[params]`` and ``[module]]`` in your example.  Try moving it before any ``[]`` blocks.

**Comment by aormsby** [comment]
@danielfdickinson Thank you, that did the trick. I didn't realize that about toml, but that's why I'm learning about it. 🙂

**Comment by xiang0805** [comment]
This article is about set-up the disqus on papermod.

https://chzlab.net/2022/01/30/2022-%E6%B2%92%E5%B7%A5%E4%BD%9C%E7%B3%BB%E5%88%97-03-hugo-papermod-%E4%B8%BB%E9%A1%8C%E5%AE%89%E8%A3%9D-disqus/
