### ISSUE TITLE
[BUG] animated images not animating

### ISSUE THREAD

**Issue by sarkrui** [adityatelange/hugo-PaperMod#518]
**Describe the bug**

 - Device: MacBook Air M1 11.5.2 (20G95)
 - Type: Desktop
 - Browser and version: Chrome 92.0.4515.131
 - Hugo Version: hugo v0.86.0+extended
 - Theme Version [v5.0, master]:

**Expected behavior**:

The resized APNG and GIFs are supposed to animate if the originals do.

**Additional context**
So basically as this moment, Hugo doesn't support `resource.Resize` or `resource.Fill` animated images (APNG or GIFs), as it will make animated images into static ones and PaperMod seems doesn't take that into considerations?

**My solution**
Perhaps we could take "gif" "png" out of the `$processableFormats` and apply a if...else and functions (cropping css, `<picture> srcset=""` fallback for legacy broswers, etc.) onto the images that are included in `$animateFormats`
```
{{- $processableFormats := (slice "jpg" "jpeg" "tif" "bmp") }}
{{- $animateFormats := (slice "webp" "gif" "png") }}
```

**Comment by adityatelange** [comment]
Hi @sarkrui you can now disable the page having animated image  as cover 5bc9c5a

User `responsiveImages: false` in your page config vars
