### ISSUE TITLE
Add setting to hide footer text

### ISSUE THREAD

**Issue by johnnymetz** [adityatelange/hugo-PaperMod#543]
Can we add a setting to hide the footer text?

> © 2021 John Doe Powered by Hugo & PaperMod

I've noticed other popular themes do this (e.g. [hugo-coder](https://github.com/luizdepra/hugo-coder/wiki/Configurations) has a `hideFooter` setting).

My current workaround is to create a custom footer file at `layouts/partials/footer.html` without the `footer.footer` element [here](https://github.com/adityatelange/hugo-PaperMod/blob/master/layouts/partials/footer.html#L1) but I constantly need to check this file for updates to make sure I have the latest changes.

I'm happy to put up a PR for this if needed.

**Comment by adityatelange** [comment]
> Can we add a setting to hide the footer text?
> 
> > © 2021 John Doe Powered by Hugo & PaperMod
> 
> I've noticed other popular themes do this (e.g. [hugo-coder](https://github.com/luizdepra/hugo-coder/wiki/Configurations) has a `hideFooter` setting).
> 
> My current workaround is to create a custom footer file at `layouts/partials/footer.html` without the `footer.footer` element [here](https://github.com/adityatelange/hugo-PaperMod/blob/master/layouts/partials/footer.html#L1) but I constantly need to check this file for updates to make sure I have the latest changes.
> 
> I'm happy to put up a PR for this if needed.

So, you want to check for updates to make sure you have latest changes, but you are not comfortable supporting the project with a lil footer text?

Contributors add stuff to this project to make it better, but people are lazy to check through code and make changes to their own copy. This just makes me sad.

**Comment by johnnymetz** [comment]
@adityatelange so do you not want to implement a `hideFooter` setting in general or are you asking me to implement it? Like I said above, I'm happy to put up a PR.

**Comment by adityatelange** [comment]
You can user `hideFooter` to hide Footer and copyright stuff

**Comment by johnnymetz** [comment]
Thank you!
