### ISSUE TITLE
Why does PaperMod modifies the default <strong> style?

### ISSUE THREAD

**Issue by mehdy** [adityatelange/hugo-PaperMod#55]
Here it modifies the `strong` tag's style to use a custom `font-weight` (500) and not the default `bold` value.
https://github.com/adityatelange/hugo-PaperMod/blob/16213a37e5e6748e0951e0547402996317238856/assets/css/reset.css#L54-L57

I was wondering if there is any reason for this I don't know about or is it just about different tastes?
In my opinion, the bolded phrases are not as bold as I wanted them to be.
Isn't it better to let the user's font decides how much bold should actually be bold?

Thanks

**Comment by adityatelange** [comment]
@mehdy It is for differentiating between  **h** tags from **bold** ig, that was inherited from paper :)

**Comment by mehdy** [comment]
@adityatelange Humm...Thanks. Well, do you think it's better to change it for everyone or should I use my own custom CSS to achieve what I want?

**Comment by mehdy** [comment]
Ping @adityatelange

**Comment by adityatelange** [comment]
> Ping @adityatelange 

hmm ... is it a breaking issue ? idk, haven't decided anything on this.

**Comment by mehdy** [comment]
@adityatelange Thank you so much!
I'll close the issue then.
