### ISSUE TITLE
[BUG] Wiki Features page homeInfoParams example wrong line mention

### ISSUE THREAD

**Issue by smailzhu** [adityatelange/hugo-PaperMod#553]
**Describe the bug**

On [wiki/Features](https://github.com/adityatelange/hugo-PaperMod/wiki/Features) page mention params/homeInfoParams configuration

I think it should be Line 127 but not 106
https://github.com/adityatelange/hugo-PaperMod/blob/exampleSite/config.yml#L127

I don't know how to raise a PR for wiki page, so I raise an issue

**Comment by adityatelange** [comment]
Fixed!
