### ISSUE TITLE
[BUG] structured data broken when baseURL has no trailing slash (/)

### ISSUE THREAD

**Issue by danielfdickinson** [adityatelange/hugo-PaperMod#558]
**Describe the bug**

Google Search Console reports an error in structured data when breadcrumbs are enabled and the baseURL is configured without a trailing slash (/), for example.

```yaml
baseURL: https://www.princesandmadmen.ca
```
This results in the following in \<head>

```html
<html>
<body>
<script type=application/ld+json>
{
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  "itemListElement": [, 
  {
  "@type": "ListItem",
  "position":  2 ,
  "name": "Blog",
  "item": "https://www.princesandmadmen.ca/post/"
  }
 ]
}
</script>
```
I will have a PR (momentarily) that resolves the issue, but another option is just to document that a trailing slash is required.

**Comment by adityatelange** [comment]
This isssue is already discussed, #331 #336

**Comment by danielfdickinson** [comment]
Oops. Sorry, I forgot to search closed issues.
