### ISSUE TITLE
[BUG] label.logo disappear when changed from homepage to single page

### ISSUE THREAD

**Issue by qvieth** [adityatelange/hugo-PaperMod#563]
**Describe the bug**

 - Device/Os: [Mobile, Desktop]
 - Type: [e.g. DesktopMobile]
 - Browser and version [e.g. Firefox 92]:
 - Hugo Version [ >=0.82.0 expected]:
 - Theme Version [e.g. master lasted ]:
1. Entering homepage the logo is still good:
![image](https://user-images.githubusercontent.com/71810726/133889052-c90d8def-935f-44f4-b712-73bdcc2d9184.png)

2. Bug happens when move to other tabs, or any page that's not homepage, the logo disappear and being replaced by "logo" string:
![image](https://user-images.githubusercontent.com/71810726/133889078-64d7cf38-9283-4673-8d3d-a397b319bc4c.png)

Here's might be the relevant part of config.yml
![image](https://user-images.githubusercontent.com/71810726/133889093-70acd0b9-ec6d-476f-a63a-2c577589f759.png)

**Comment by adityatelange** [comment]
Try using `icon: "/favicon.svg"`

**Comment by qvieth** [comment]
> Try using `icon: "/favicon.svg"`

This works, thank you @adityatelange
