### ISSUE TITLE
Request to remove `target="_blank"`

### ISSUE THREAD

**Issue by cbondurant** [adityatelange/hugo-PaperMod#588]
For the social media buttons that can be added with the `socialIcons` option, I would like the ability to either configure them to not have the `target="_blank"` property set or for the property to be completely removed. 

I personally consider it to be an anti-feature of a property, as if the user wishes to open a new tab, all modern browsers support the middle mouse button as a way to manually open in new tab, and a user rarely wishes to have their tabs cluttered by additional pages they no longer are viewing. 

Additionally this causes problems for my personally hosted webpage, as the webserver uses the CSP: sandbox with no popup allowed, which silently fails all `target=_blank` links.

**Comment by Arusekk** [comment]
A small FYI: a similar restriction is currently true regarding SourceHut Pages: https://srht.site/limitations/

However, they have relaxed the CSP before, and I requested it to be relaxed again.
