### ISSUE TITLE
Netlify CMS

### ISSUE THREAD

**Issue by ibragimof** [adityatelange/hugo-PaperMod#59]
Can you make this template friendly for NetlifyCMS?

**Comment by adityatelange** [comment]
Hey @ibragimof, 

I have not used Netlify CMS, hence I have no idea how that works.
I'll surely look into it and if possible I'll add that, however I don't know when ... :)

**Comment by ibragimof** [comment]
Netlify CMS [docs](https://www.netlifycms.org/docs/add-to-your-site/).

**Comment by adityatelange** [comment]
@ibragimof As far as I can see you can add netlify cms yourself 
https://willschenk.com/articles/2018/adding_a_cms_to_hugo/

`admin/config.yml` will be different for each.

**Comment by cjreinhardt** [comment]
@ibragimof I was looking for the same thing!I was able to get Netlify CMS working pretty well for posts.  I created a [starter project here](https://github.com/cjreinhardt/Hugo-PaperMod-NetlifyCMS-Starter/), but you could also copy my /admin/config.yml file here:  https://github.com/cjreinhardt/Hugo-PaperMod-NetlifyCMS-Starter/blob/main/static/admin/config.yml

Good luck!
