### ISSUE TITLE
Valid HTML Improvement: ul tag for language switch shouldn't be a child of a span

### ISSUE THREAD

**Issue by drohen** [adityatelange/hugo-PaperMod#599]
I tried validating the HTML of my website, and it failed on the Site-level language switch. The `ul` tag used to list the available languages is a block-level element, and this is nested within various `span` elements. As `span` is a phrasing element, it also should only contain phrasing elements. Either the `ul` should be replaced with something else, or the parent tags should be changed to something like a `div`.

If you would prefer me to make a PR for this I can do so.

**Comment by adityatelange** [comment]
Is HTML validation everything? Like a `<span>` here works the same as using 2 or more CSS rules. It gets the job done.

**Comment by louisfoster** [comment]
I figured as it's a blog theme, blogs generally contain valid HTML to help with parsers for search engine indexing and accessibility. I was merely pointing this out in case you weren't aware. It's your theme, If you're not concerned, then feel free to close the issue.

**Comment by Rotzbua** [comment]
I observed the same problems.

## W3 validator

### Current demo
https://validator.w3.org/nu/?doc=https%3A%2F%2Fadityatelange.github.io%2Fhugo-PaperMod%2F

### Error output

![grafik](https://user-images.githubusercontent.com/7337347/160304997-14ea4201-c9fd-4a99-8f30-9de519dafe31.png)

### Warning output

![grafik](https://user-images.githubusercontent.com/7337347/160305878-93af9ef7-d06b-43cd-a200-b01d255d8625.png)

### Solution

Created two PRs which solved the problems for my setup. Not sure if they solve it for every configuration.
