### ISSUE TITLE
Social icons on homepage are filtered by uBlock's "Cosmetic Filtering"

### ISSUE THREAD

**Issue by atmosfar** [adityatelange/hugo-PaperMod#60]
![Screenshot 2020-10-26 182449](https://user-images.githubusercontent.com/6472079/97212618-8fdd5300-17b8-11eb-84e8-ca51676d4fbb.png)

Filtered out by the "##.social-icons" rule from one of the default lists. This is "working as intended" behaviour in terms of hiding share icons from posts, but should not be allowed to break the display of the homepage imo.

**Comment by adityatelange** [comment]
If the person visiting your website has these filters added, it's by choice that the person doesn't want to see any of those.
So, the homepage isn't broken by theme, nor by the owner, but by the person viewing the webpage.

And as you said it is working as intended.

**Comment by atmosfar** [comment]
It is working as intended to remove "cosmetic" features, like Share buttons
on a blog post.

Links to social media accounts on a profile landing page are core
functionality, not cosmetic.

**Comment by adityatelange** [comment]
> It is working as intended to remove "cosmetic" features, like Share buttons
> on a blog post.
> 
> Links to social media accounts on a profile landing page are core
> functionality, not cosmetic.

hmm.. !?
The person using ad-blocker is breaking the webpage ! The filter is not added by me, thus all the icons work as they should be. If you'll remove the filter they'll work fine.

I personally use dns level ad blocker and see some blank patches on webpages with ads, does this mean that the site owner is breaking the core functionaliy? No.
