### ISSUE TITLE
Parameter to make custom post snippet

### ISSUE THREAD

**Issue by EnokiRumle** [adityatelange/hugo-PaperMod#61]
Thanks for a great theme Aditya.

Is it possible to add a page and post parameter, to make the snippet seen on the list page custom?
<img width="851" alt="Screenshot 2020-10-27 at 22 04 44" src="https://user-images.githubusercontent.com/62760121/97361871-7e6f7600-18a0-11eb-903d-b085ca3b2eee.png">

**Comment by adityatelange** [comment]
@EnokiRumle 

I didn't get you, wdm by "page and post" param ?


Do you mean that summary text? 

> ExampleSite source can be found here: exampleSite. Demo is built up with exampleSite as source.

(text from from readme)

**Comment by EnokiRumle** [comment]
Yes, I simply want to change the summary text snippet on my own site. Right now it just shows the first two lines of the body text inside the post.

**Comment by adityatelange** [comment]
> Yes, I simply want to change the summary text snippet on my own site. Right now it just shows the first two lines of the body text inside the post.

68b04af186d6f0b6b7edf38fc9db7173d08873c4 see this commit
