### ISSUE TITLE
Search error 

### ISSUE THREAD

**Issue by Anzlim** [adityatelange/hugo-PaperMod#616]
When i am trying to add Search its giving error 

> Error: Error building site: failed to render pages: render of "page" failed: execute of template failed: template: _default/search.html:5:8: executing "_default/search.html" at <partial "head.html" .>: error calling partial: "/home/anzar/Red Themers/red-blog-source/themes/PaperModx/layouts/partials/head.html:74:54": execute of template failed: template: partials/head.html:74:54: executing "partials/head.html" at <js>: can't evaluate field Build in type string

**Comment by adityatelange** [comment]
Use [Bug Report Template](https://github.com/adityatelange/hugo-PaperMod/issues/new?assignees=&labels=bug&template=bug_report.md&title=%5BBUG%5D) for reporting bugs
