### ISSUE TITLE
Navbar Submenu

### ISSUE THREAD

**Issue by yunusemreaydinli** [adityatelange/hugo-PaperMod#62]
Hello,

When can a Navbar Submenu be added?
Good work.

**Comment by adityatelange** [comment]
> Hello,
> 
> When can a Navbar Submenu be added?
> Good work.

No plans to add Navbar submenu, nor a drop-down menu.

**Comment by yunusemreaydinli** [comment]
Thanks! Good work.

**Comment by jasonbraganza** [comment]
@adityatelange I understand your reasons not to. But if I need one, is it possible for me to go spelunking Hugo Documentation and add a submenu?
Asking as a noob at all this.
I don’t want to switch away from Papermod, it is perfect. All i need is more my more link on my [homepage at janusworx.com](https://janusworx.com) to be a dropdown.

**Comment by adityatelange** [comment]
Hello @jasonbraganza 
Hamburger menu source had been added as a thread in PaperMod's Discord recently.

Please check it out here:

🔗 https://discord.com/channels/971046860317921340/1047919068075802714/1047919071787765890

**Comment by jasonbraganza** [comment]
Thank you so much @adityatelange! You’re awesome!
Will go sign up and check it out.
