### ISSUE TITLE
Numbering entries for a series

### ISSUE THREAD

**Issue by marioortizmanero** [adityatelange/hugo-PaperMod#625]
It'd be great to be able to add numbering to the posts in the series page. The title in each card should be prepended by the number of post in that series. For example, instead of "Post A", "Post B", and "Post C", "1. Post A", "2. Post B", and "3. Post C", assuming that "Post A" was the first article, and "Post C" was the last one.

This would help avoid confusion, making the order of the series clear.

**Comment by hannagoodbar** [comment]
This sounds similar as issue #464, where I added a comment for listing and numbering articles in a series.

**Comment by marioortizmanero** [comment]
Not the same, what I meant here was numbering the series entries in the series page. The other issue is about listing them in the article page.
