### ISSUE TITLE
Telegram doesn't show a preview of cover image.

### ISSUE THREAD

**Issue by fahimscirex** [adityatelange/hugo-PaperMod#630]
While Facebook, Twitter and a few other sites I've checked generates a preview of cover image that has been added into a post, Telegram doesn't show any image previews. I'm not sure if it's a Telegram issue or Papermod's, cause Telegram generates preview of other sites such as GitHub, Twitter.

**Comment by adityatelange** [comment]
Ok let's test this.

I have created a channel https://t.me/test_3334555 or https://t.me/s/test_3334555 where I have added 3 links having a cover image.

Please open this link into your telegram app and let me know whether if it shows cover images for you.

**Comment by fahimscirex** [comment]
Well, it's showing.

**Comment by fahimscirex** [comment]
I checked your page source, image URLs are relative there. So when I set `relative: true`, the generated link heads to a 404 page.
I'm keeping images in `static/img/` folder. Is it the correct path?

Leaving the repo just in case https://github.com/fahimscirex/fahimscirex.github.io

**Comment by adityatelange** [comment]
> Well, it's showing.

So its not an issue related to papermod, please configure the site properly. Closing.
