### ISSUE TITLE
[Feature Request] Add a subscription form

### ISSUE THREAD

**Issue by navendu-pottekkat** [adityatelange/hugo-PaperMod#632]
Add a template (partial) for a subscription form and a new page with this form embedded.

The form submit action can point to a link the user provides. The form needs to be in the PaperMod theme.

Users can reuse this template anywhere on the website (at the end of the blog post, home page etc).

**Comment by navendu-pottekkat** [comment]
I have created a subscription form with the same styling as the rest of the website.

You can check it out here: [navendu.me](https://navendu.me)

Screenshots:

![Screenshot 2021-11-16 at 3 41 54 PM](https://user-images.githubusercontent.com/49474499/141966316-92478ec3-0fd1-4c63-9da5-29ccd76afaf5.png)
![Screenshot 2021-11-16 at 3 42 01 PM](https://user-images.githubusercontent.com/49474499/141966341-50080eef-8486-4ede-9198-be70128c8e3b.png)
![Screenshot 2021-11-16 at 3 42 12 PM](https://user-images.githubusercontent.com/49474499/141966348-b2d14239-dc9f-477b-b0b8-0221109ac9d8.png)

**Comment by adityatelange** [comment]
Hi @navendu-pottekkat, that looks great!

The only reason we don't have it is people have different choices about how their `form` should be and the vendors/3rd party platforms they are using to process the input. All of this is not generic and varies implementation for every provider apparently, which opens doors to lot of configuration related to this.

**Comment by navendu-pottekkat** [comment]
Yes. Makes sense.
