### ISSUE TITLE
[BUG] Use of font-family monospace does not work on Windows

### ISSUE THREAD

**Issue by dantewang** [adityatelange/hugo-PaperMod#634]
**Describe the bug**

 - Device/Os: PC/Windows 10
 - Type: Desktop
 - Browser and version Chrome 96 and Microsoft Edge 95
 - Hugo Version 0.88.1
 - Theme Version a57cb762c320c05b616f7911c8b5dc78e3080a72

**Steps to reproduce the behavior:**
Visit any post with code block on Windows

For example: https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-features/

**Expected behavior**:
The code block is displayed using one of the monospace fonts that are available on Windows, like Consolas

**Actual behavior**
The code block is displayed using the default fallback font on Windows, because Windows does not recognize font family "monospace"

**Screenshots**
![font-on-windows](https://user-images.githubusercontent.com/1185063/142651671-8afa9eac-0cb7-41c7-bec9-3ebe008b01ae.png)

**Additional context**
This seems to be a common issue when I use different blog platform (Wordpress, Typecho, Ghost, etc.) with different themes.

**Comment by adityatelange** [comment]
Works fine on older Edge:
![image](https://user-images.githubusercontent.com/21258296/157888132-7773c33a-ce6f-45d6-8176-b606c73a2ef6.png)

**Comment by adityatelange** [comment]
@JonBCraig if you see it worked fine when I tried in a VM (windows 10) https://github.com/adityatelange/hugo-PaperMod/issues/634#issuecomment-1065173248 any idea why it looks fine over there?

**Comment by adityatelange** [comment]
If you visit `chrome://settings/fonts` what do you see in `Fixed-width font`?
