### ISSUE TITLE
[Request] Setting to not overwrite the scrollbar style

### ISSUE THREAD

**Issue by JannikArndt** [adityatelange/hugo-PaperMod#637]
Hi! 👋 

I'm not a fan of overwriting the scrollbar-style. Unfortunately, resetting it doesn't seem possible. My approach would have been to add

```css
::-webkit-scrollbar {
    all: unset !important;
}
```

to the `custom.css`, or any combination of more specific, more nested settings. `initial` or `auto` instead of `unset` also don't work. The only thing that _does_ work is to remove styles from `zmedia.css`. Messing with the original theme is not great, though.

Is it possible to only load the scrollbar-styles if `.Site.Params.ColourScrollBar == true` via the config?

**Comment by adityatelange** [comment]
I'll look into it if we can make it modular, but it is really hard to make each and eveything optional.
Yes I do respect your opinion, but yes it is not really possible to make a theme where eveyone likes eveything.

**Comment by lorenviol** [comment]
It would be a great thing to have the scrollbar optional, not a fan of it either
