### ISSUE TITLE
[BUG] - Tags are missing in site builds, but only on some posts

### ISSUE THREAD

**Issue by aormsby** [adityatelange/hugo-PaperMod#648]
**Describe the bug**
For some reason, tags are not being included in my builds for **_some_** posts. Some posts have them, some posts don't. But I do have front-matter data set for tags on every post. I'm not sure if this is a theme issue or a Hugo issue, but it's a bit frustrating to have half my posts untagged.

 - Seen in desktop browser (any, because the build itself does not include the tags)
 - Hugo Version 0.88.1 and 0.89.4 tested
 - Theme Version 7c930ee4ea1b and 386d84578278 (latest) tested

**Steps to reproduce the behavior:**
Not sure, it's inconsistent. All of my posts have tags in the front matter, but only some of the older ones are actually building with them included. https://adamormsby.com for reference.

**Expected behavior**:
I would expect all posts to include my tags.

**Screenshots**

One with tags:
<img width="877" alt="Screen Shot 2021-11-26 at 19 20 01" src="https://user-images.githubusercontent.com/1312251/143663823-2b3af32b-c925-4db4-af8e-9d1a57c8fc6c.png">

One missing tags:
<img width="820" alt="Screen Shot 2021-11-26 at 19 20 13" src="https://user-images.githubusercontent.com/1312251/143663828-a1717ce5-ad36-4af6-9f89-085f349a5bae.png">

**Additional context**
No idea if this is Hugo- or theme-related, will try to investigate further

**Comment by adityatelange** [comment]
Can you share the `front matter` source for 'one with tags' and 'one missing tags' post? So that we can replicate it.

**Comment by aormsby** [comment]
My apologies, I figured out the problem. I had an older front-matter setup that I hadn't audited in a while, and some of my params with nested values were listed above the base params (like tags). Because of that, they were getting ignored during builds.

Incorrect:

```toml
summary = "my summary"

[cover]
    image = "cover.png"

tags = ["tag 1", "tag2"]
```

Correct:

```toml
summary = "my summary"

tags = ["tag 1", "tag2"]

[cover]
    image = "cover.png"
```

Order matters! :+1:
