### ISSUE TITLE
Images not rendering in Safari browsers

### ISSUE THREAD

**Issue by taptiger** [adityatelange/hugo-PaperMod#65]
Hi @adityatelange, great theme!

I can't get images to render using `![alt text](/path/to/local/image.jpg`. I also see that the images stored as `.webp` in the example site are not rendering: [anchor link](https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-features/#regular-mode-default-mode).

Is this a bug or is there a step that I should take between adding an image to the site directory and expecting to see it render?

**Comment by adityatelange** [comment]
@taptiger images stored as webp are of course rendering.

for local images refer 

https://github.com/adityatelange/hugo-PaperMod/tree/754e47fc1cf92238bc6a53ecfa554f6dac959d7a/content/posts/papermod/papermod-features

and 

https://raw.githubusercontent.com/adityatelange/hugo-PaperMod/754e47fc1cf92238bc6a53ecfa554f6dac959d7a/content/posts/papermod/papermod-features/index.md

**Comment by taptiger** [comment]
Correction: images (webp and local jpgs) are not rendering on **Safari browsers**. Images render fine on Chrome and Firefox.

**Comment by adityatelange** [comment]
> Correction: images (webp and local jpgs) are not rendering on **Safari browsers**. Images render fine on Chrome and Firefox.

@taptiger Yeah so it is Safari's issue and not theme specific

**Comment by adityatelange** [comment]
@taptiger can you share source of website?

I still doubt about local jpeg images.

also are you telling about cover image or using with markdown (although you have mentioned it in 1st comment)

**Comment by taptiger** [comment]
@adityatelange I am talking about inline markdown, using a `.jpg` file.

Here's my example
- [code](https://github.com/taptiger/blog/pull/1)
- [site preview](https://deploy-preview-1--taptiger.netlify.app/posts/theme-images/)

In the build logs I can see "Processed images |  0" after running `hugo --gc --minify` which is why I originally asked about whether there is a step I should be taking beyond just dropping an image file into the source tree.

**Comment by adityatelange** [comment]
@taptiger You are not doing it in correct way.

The post bundle for local images to work a/c to hugo is different, 
refer 

https://github.com/adityatelange/hugo-PaperMod/tree/754e47fc1cf92238bc6a53ecfa554f6dac959d7a/content/posts/papermod/papermod-features

and 

https://raw.githubusercontent.com/adityatelange/hugo-PaperMod/754e47fc1cf92238bc6a53ecfa554f6dac959d7a/content/posts/papermod/papermod-features/index.md

properly
