### ISSUE TITLE
[BUG] The appearance of the scroll bar in Safari

### ISSUE THREAD

**Issue by pawelwiejkut** [adityatelange/hugo-PaperMod#654]
**Describe the bug**
The scrollbar looks weird in Safari, kindly please check screenshots.

 - Device/Os: Macbook / Mac OS 12.0.1
 - Type: Desktop
 - Browser and version [e.g. Chrome 86.0]: Safari 15.1 (17612.2.9.1.20)
 - Hugo Version [ >=0.83.0 expected]: same as in adityatelange.github.io
 - Theme Version [e.g. v4.0, master, or commit-id ]: same as in adityatelange.github.io

**Steps to reproduce the behavior:**

1. Go to  https://adityatelange.github.io/hugo-PaperMod/
2. Click on any post inside, check the scrollbar

**Expected behavior**:
The scrollbar doesn't look nice like in Chrome.

**Screenshots**
Chrome:
<img width="1322" alt="Screenshot 2021-12-01 at 23 15 08" src="https://user-images.githubusercontent.com/11619019/144322868-52c2155a-dd9d-40e7-bebf-6db3b6558c52.png">

Safari:
<img width="1071" alt="Screenshot 2021-12-01 at 23 16 19" src="https://user-images.githubusercontent.com/11619019/144323007-e752a845-9fd5-4e39-b53b-fbdbd65f1fa6.png">

**Comment by pawelwiejkut** [comment]
Hi all,

I'm not into css best practices but as a workaround, you can add

`::-webkit-scrollbar{
    background: var(--theme);
}`

into theme-vars.css. It will fix the scrollbar.

**Comment by adityatelange** [comment]
> Hi all,
> 
> I'm not into css best practices but as a workaround, you can add
> 
> `::-webkit-scrollbar{ background: var(--theme); }`
> 
> into theme-vars.css. It will fix the scrollbar.

Using this as solution, Thanks!
