### ISSUE TITLE
Request for ExampleSite and .toml file?

### ISSUE THREAD

**Issue by umitbulut** [adityatelange/hugo-PaperMod#66]
Hello there. Thank you for this enhanced version of the theme. It looks so good! 
But somehow I couldn't figure it out to deploy theme like the demo version and I am wondering is there any way to add ExampleSite folder like the demo (including content) and .toml file? 
Thank you in advance. 
Have a nice day. 🤗

**Comment by adityatelange** [comment]
I guess you haven't read  README !

**Comment by umitbulut** [comment]
I am new to hugo and your reply isn't so welcoming. 
I have read the readme file and after my tries, I haven't succesfull in deploying site. So, when I try some other theme's straight exampleSite and .toml version, it was just worked fine. That is why I was kindly made a request.

**Comment by adityatelange** [comment]
@umitbulut 
Everything is mentioned step by step here, I don't know what probs you are facing :man_shrugging: 
https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-installation/#guide

Talking about my reply it was straight forward as I was busy, also I have edited it later on :)

**Comment by umitbulut** [comment]
I've come across .yml issues, somehow I couldn't deploy with it somehow. 
Thanks! :)
