### ISSUE TITLE
[improvement] adding extended_poweredby in footer

### ISSUE THREAD

**Issue by Thorgrimson** [adityatelange/hugo-PaperMod#664]
I use the theme for my blog and wanted to add my webspace-provider in the powered by section of the footer. I did with use of a custom footer.html and extended_poweredby.html. If there is interest for this I would open a merge request ;)
![grafik](https://user-images.githubusercontent.com/73939988/145099897-26f2111a-7503-4505-a880-becb408a410c.png)

**Comment by wbamberg** [comment]
@Thorgrimson , I'm interested! See https://github.com/openwebdocs/website/pull/3 where we are dealing with the same thing. We wanted the "Powered by..." bit in a new line, which seemed to cause problems with the layout, but perhaps I misunderstood how to use the customisation.
