### ISSUE TITLE
[BUG] Archive is not displayed

### ISSUE THREAD

**Issue by Nathan-Furnal** [adityatelange/hugo-PaperMod#702]
Hi, 

I'd like to use the archives layout for my posts but it doesn't work, I get the "Archive" title with an empty page. 
![image](https://user-images.githubusercontent.com/45597572/147500514-cab42687-eb7f-4bc9-8d27-d7b1ccdf23fc.png)

Even though posts are displayed properly as seen here : 

![image](https://user-images.githubusercontent.com/45597572/147500579-60db50aa-4f4b-46d4-bdf0-ea1bacd538de.png)

- OS & info : 
Operating System: Manjaro Linux
KDE Plasma Version: 5.23.4
KDE Frameworks Version: 5.89.0
Qt Version: 5.15.2
Kernel Version: 5.15.11-1-MANJARO (64-bit)
Graphics Platform: X11
Processors: 16 × AMD Ryzen 7 PRO 4750U with Radeon Graphics
Memory: 14.9 GiB of RAM
Graphics Processor: AMD RENOIR

- Type: Desktop
- Browser : Google Chrome 96.0.4664.110
- Hugo version: hugo v0.91.2+extended linux/amd64 BuildDate=unknown
- Theme version :  Built from master with submodules 

As per the doc, I added a `archives.md` in the `content/` folder, I use `toml` but had the same issue with `yaml`, the file content is : 

```md
+++
title = "Archive"
layout = "archives"
draft = false
[menu.main]
  identifier = "archive"
  weight = 7
+++
```
The entirety of the code can be consulted at my repo : https://gitlab.com/nathanfurnal/blog

Thanks for help

**Comment by adityatelange** [comment]
@Nathan-Furnal Posts are displayed in Archives if they have date. Try adding date field to the post, it will be there in Archive list.

**Comment by Nathan-Furnal** [comment]
That's embarassing, I thought there was some internal date system my bad! It's fixed =)

**Comment by arjun921** [comment]
@adityatelange Thanks for this amazing theme!
But umm I seem to be facing the same trouble as Nathan
Can you help me understand what am I doing wrong?

Repo: https://github.com/arjun921/apple-release-dates
Archives: https://applereleasedate.com/archives/
Posts: https://applereleasedate.com/posts/

**Comment by arjun921** [comment]
Okay, my bad.
It doesn't support if the post md is in not under posts I guess.
probably where it broke. 

I cloned the exampleSite and made changes to that, that seems to be working now :) 

Thanks once again for the theme :)
