### ISSUE TITLE
Wide code layout

### ISSUE THREAD

**Issue by TonioGela** [adityatelange/hugo-PaperMod#72]
I just noticed that in mobile the code boxes hit the viewport and have no margin.
Is this a choice?
![Screen Shot 2020-11-10 at 09 03 50](https://user-images.githubusercontent.com/41690956/98646560-d5ab2700-2333-11eb-83c9-11a325dd950d.png)

**Comment by adityatelange** [comment]
@TonioGela Yes it is. Both on Desktop as well as Mobile.
This is inherited from hugo-paper of which this theme is based.

**Comment by TonioGela** [comment]
Okay, I think I'll modify it for my pages. Thanks!
