### ISSUE TITLE
How to enable utteranc

### ISSUE THREAD

**Issue by rahulinux** [adityatelange/hugo-PaperMod#74]
Is there any support for https://utteranc.es ?

**Comment by adityatelange** [comment]
why not simply add it to `comments.html`

https://utteranc.es/#heading-enable

https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-features/#comments

**Comment by rahulinux** [comment]
I will try option you suggested and I was looking for config option something link this:

```
 [params.utteranc]         # utteranc is a comment system based on GitHub issues. see https://utteranc.es 
   enable = false 
   repo = "repo/path"    # The repo to store comments 
   issueTerm = "pathname" 
```

**Comment by adityatelange** [comment]
> I will try option you suggested and I was looking for config option something link this:
> 
> ```
>  [params.utteranc]         # utteranc is a comment system based on GitHub issues. see https://utteranc.es 
>    enable = false 
>    repo = "repo/path"    # The repo to store comments 
>    issueTerm = "pathname" 
> ```

currently nothing implemented like that, I don't think it is a big deal, anyways will see to add it in future. :+1:
