### ISSUE TITLE
Documentation request

### ISSUE THREAD

**Issue by akuzni2** [adityatelange/hugo-PaperMod#744]
Request to update documentation - 

I just learned that my posts do not show up on the main "home" page correctly unless I make a new post under `content/posts`.

If for instance I put them under `content/my-post-title/post.md` it doesn't show up on the paginate option. 

Would be good to make that explicit so others don't spend time figuring it out

**Comment by adityatelange** [comment]
This is a Hugo related issue pls visit Hugo documentation gohugo.io for clarification.
