### ISSUE TITLE
Add an "About me" or "Author" in main menu

### ISSUE THREAD

**Issue by nowshed-imran** [adityatelange/hugo-PaperMod#746]
PaperMod is missing a great feature. In config file, there is no option to create an "About me" or "Author" in main menu.

It can be a simple markdown file which can be used to describe the website or a bio of the page owner.

Kindly consider adding this feature.

**Comment by adityatelange** [comment]
You can add it yourself.
Just create a page and link it in the menu.

This is not a thing missing in the theme nor this is a feature which can be implemented here.
Thanks
