### ISSUE TITLE
[BUG] PaperMod does not respect GoldMark ToC customizations

### ISSUE THREAD

**Issue by sethforprivacy** [adityatelange/hugo-PaperMod#747]
**Describe the bug**
The current design of PaperMod does not allow a user to specify the start and end level of headers to use for the Table of Contents, leading to some extremely large ToCs depending on the way a user approaches headings.

The customization here should be allowed, or a new format for PaperMod should be specified so that users can limit what headers get rendered in the ToC:

https://gohugo.io/getting-started/configuration-markup/#table-of-contents

Currently this configuration is completely ignored and all header levels are pulled into the ToC no matter what configuration a user specifies.

 - Device/Os: [e.g. Android 10] All
 - Type: [e.g. Desktop/Mobile] All
 - Browser and version [e.g. Chrome 86.0]: All
 - Hugo Version [ >=0.83.0 expected]: hugo v0.92.0+extended darwin/amd64 BuildDate=unknown
 - Theme Version [e.g. v4.0, master, or commit-id ]: master

**Steps to reproduce the behavior:**
1. View my config.yml specifying headers to use in ToC here: https://github.com/sethforprivacy/sethforprivacy.com/blob/master/clearnet_config.yml#L148-L151
2. View my website built using that config here: https://blog.sethforprivacy.com/posts/switching-to-calyxos/
3. Notice how headers at H4 are added to ToC despite configuration

**Expected behavior**:
Headers are only added to ToC while respecting markdown config in config.yml

**Comment by adityatelange** [comment]
@sethforprivacy Can you show me a way we could use the variables mentioned here https://github.com/sethforprivacy/sethforprivacy.com/blob/master/clearnet_config.yml#L148-L151 in templates?

**Comment by sethforprivacy** [comment]
I'm not that familiar with it to be able to recommend a technical approach, but the variables shown here work with the default ToC in Hugo (and any theme that does not modify the ToC, like https://github.com/panr/hugo-theme-terminal, my previous theme).

Sorry I don't have more input :(

**Comment by adityatelange** [comment]
I have added a new paramer `UseHugoToc`.
You can set it to true and use Hugo's default ToC generator and use the mentioned customization you's like to have.

I have done what I could do , as it is not possible to fetch
```
markup:
  tableOfContents:
    endLevel: 2
    ordered: false
    startLevel: 1
```

in templates.
