### ISSUE TITLE
Right Side Toc

### ISSUE THREAD

**Issue by linsn0w** [adityatelange/hugo-PaperMod#758]
Put the TOC sidebar on the right, because you can't click the sidebar when you slide to the bottom. I hope to provide this function. Thank you🎈

**Comment by adityatelange** [comment]
No plans to implement.

**Comment by fatFire** [comment]
> No plans to implement.

Very useful feature, why not consider implementing it?

**Comment by kchousos** [comment]
Very much agree with @fatFire
