### ISSUE TITLE
bug: toc not support to scroll non-ascii title

### ISSUE THREAD

**Issue by ZzMark** [adityatelange/hugo-PaperMod#78]
question:
  use chinese title, toc click will error.
![image](https://user-images.githubusercontent.com/23636931/99370582-d4ac6380-28f8-11eb-8a47-c788ed3cbb4b.png)

this bug come to [layouts/partials/footer.html#L34](https://github.com/adityatelange/hugo-PaperMod/blob/62477e7d1b3a69bf76d413e6a4281f93b582b03d/layouts/partials/footer.html#L34)

**Comment by ZzMark** [comment]
i fixed this problem, but only passed some simple test

[layouts/partials/footer.html#L34](https://github.com/adityatelange/hugo-PaperMod/blob/62477e7d1b3a69bf76d413e6a4281f93b582b03d/layouts/partials/footer.html#L34)
```js
document.querySelector(`[id='${decodeURIComponent(id)}']`).scrollIntoView({
  behavior: "smooth"
});
``

**Comment by adityatelange** [comment]
@ZzMark Gotcha will fix it !

https://gomakethings.com/handling-chinese-and-cyrillic-character-hash-and-href-values-in-javascript/
