### ISSUE TITLE
What am I missing out of Hugo or server side to fix Reading Time?

### ISSUE THREAD

**Issue by joelouthan** [adityatelange/hugo-PaperMod#794]
URL: http://localhost:1313/home-devos/2022-02-04-Fri-home-devos-mark/

This is local install (macOS Monterey) running Hugo server.

On prod at Netlify, it appears good: https://theologic.us/gospel-nt/2022-02-01-gospel-nt-titus/

On my localhost, it appears as:

`%!s(int=7) min`

**Comment by joelouthan** [comment]
Like so.

<img width="782" alt="image" src="https://user-images.githubusercontent.com/8844984/155166146-59160c7c-9fda-4d27-bfcb-cb09418238b9.png">

**Comment by adityatelange** [comment]
Can u try with latest version/commit on master branch

This was fixed in https://github.com/adityatelange/hugo-PaperMod/commit/537ec0038f9016f3833020521bcf82179a38da4e  by #427
