### ISSUE TITLE
[Feature Request] Support for webm in cover image

### ISSUE THREAD

**Issue by 4HMZA** [adityatelange/hugo-PaperMod#795]
Would it be possible to add support for use of webm to the cover image section of pages.
This would increase page performance compared to gifs.

**Comment by 4HMZ4** [comment]
![image](https://user-images.githubusercontent.com/20662000/155402808-ee9aa1bc-421a-43ad-a016-dabe89c4c2bf.png)

So I found this and it references and extended version of Hugo which adds support for webp.

Question 1) would adding webm to this also work
Question 2) where do I get the extended Hugo binary

**Comment by 4HMZ4** [comment]
So I compiled the Hugo extended version and added webm to the line after hugo.IsExtended and it did not work. could just be me but from my testing this was a dud. It should be possible as I am able  to use the webm format elsewhere in the posts

**Comment by adityatelange** [comment]
- #540 Adds this. You can use Hugo's extended version for that to work.
