### ISSUE TITLE
Lighthouse will report canonical url not an absolute URL

### ISSUE THREAD

**Issue by qddtdlko** [adityatelange/hugo-PaperMod#803]
under default theme.
use production mode
command line:
hugo server -D --bind="0.0.0.0" --port=1234 --baseURL="121.12.25.141" --evrionment="production"
html sourcecode about canonicalURL is like blow:
<link rel="canonical" href="//121.12.25.141:1234/nav/" />
and lighthuose will report canonical url is not an absolute URL
![image](https://user-images.githubusercontent.com/81072363/155876208-50a4ec72-bb2c-49f1-823a-dff4006c4c77.png)

**Comment by adityatelange** [comment]
Setting a baseURL in config should fix this. https://github.com/adityatelange/hugo-PaperMod/blob/22dea01e858a4f1a7dab25086222921f76310ed7/config.yml#L1
