### ISSUE TITLE
[BUG] Matrix social icon

### ISSUE THREAD

**Issue by fourstepper** [adityatelange/hugo-PaperMod#806]
On my page https://robinopletal.com/, the second social icon in use is the Matrix social icon. Wouldn't it be better to use the "official" matrix.org logo, as can be seen for example here: https://github.com/matrix-org/matrix.org/blob/master/content/matrix.png ?

Thanks for considering this :)

**Comment by adityatelange** [comment]
#484 Adds this. The icon added matches the other icons added as well as size fits well with size of social icon we have here, so it is better to keep it as it this way.

**Comment by fourstepper** [comment]
Great! Thanks!
