### ISSUE TITLE
[BUG] FastSearch not working

### ISSUE THREAD

**Issue by jaswdr** [adityatelange/hugo-PaperMod#813]
**Describe the bug**
The search feature using FastSearch is not working on a fresh install.

 - Device/Os: MacBook Pro, Big Sur
 - Type: Desktop
 - Browser and version [e.g. Chrome 86.0]: Any
 - Hugo Version [ >=0.83.0 expected]: 0.93.2
 - Theme Version [e.g. v4.0, master, or commit-id ]: 43c810c3e20bcf04e17a3e26a4ceacd9dfd9f22a

**Steps to reproduce the behavior:**
1. Create a new blog website and import the theme
2. Create a search page following the wiki [instructions](https://github.com/adityatelange/hugo-PaperMod/wiki/Features#search-page)
3. Run hugo
4. `Error: Error building site: JSBUILD: failed to transform "js/fastsearch.js" (application/javascript): Could not resolve "@params"`

**Expected behavior**:

Not seeing the error and complete the generation of the search page.

**Comment by jaswdr** [comment]
Working in latest version of Hugo

**Comment by shekharidentv** [comment]
IT showing this error : 
```Built in 55 ms
Error: Error building site: failed to render pages: render of "page" failed: execute of template failed: template: _default/search.html:5:8: executing "_default/search.html" at <partial "head.html" .>: error calling partial: "/mnt/ddc8aaf7-caa6-4121-a651-563580270299/shekhar/BlogBackup/themes/PaperMod/layouts/partials/head.html:64:54": execute of template failed: template: partials/head.html:64:54: executing "partials/head.html" at <js>: can't evaluate field Build in type string```
