### ISSUE TITLE
Add support for centering image captions in post (Mirror cover image behavior for all images in post)

### ISSUE THREAD

**Issue by swallace17** [adityatelange/hugo-PaperMod#816]
I'd like to recommend that functionality be added to handle displaying image captions on all images in a given post. PaperMod  [already handles captions and alt text for cover images wonderfully ](https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-features/#post-cover-image), and it would be nice if it could do the same for other images in a given post. 

As far as I can tell, images can currently be included in a PaperMod post through 2 ways: 

[Standard markdown formatting](https://www.markdownguide.org/basic-syntax/#images), and the [Hugo-included Figure Shortcode](https://gohugo.io/content-management/shortcodes/#figure). Only the shortcode method supports adding a caption, but if you do, these items are left-aligned by default, and do not look right when displayed on the site. I believe I could do some trickery with wrapping the figure in a class with custom CSS, but it'd be a heck of a lot easier if it was included in the theme natively. 

I believe this could be done with custom render hooks [as described in this link,](https://sebastiandedeyne.com/captioned-images-with-markdown-render-hooks-in-hugo/) and looking through the theme files, I think something like this may be how Papered is already handling cover images, but I'm quickly nearing the end of the grasp I have on building/modifying themes with Hugo. 

Curious what others might think, and what the best way to go about implementing this might be. If someone can point me in the right direction, be more than happy to spend some time on it and submit a PR. Thanks!

**Comment by adityatelange** [comment]
The shortcode method is customised.
Checkout https://github.com/adityatelange/hugo-PaperMod/commit/14ebcdecf31b1480ae997a0ab4d68207d31e083c #256
