### ISSUE TITLE
Date internationalization 

### ISSUE THREAD

**Issue by brunomiguel** [adityatelange/hugo-PaperMod#839]
Is it possible to have date internationalization (archives included) on a future release?

**Comment by adityatelange** [comment]
I think that should be possible with `time.Format`

![image](https://user-images.githubusercontent.com/21258296/160139892-21de4bf6-bab6-41e2-a559-d3bac05b8cff.png)

https://github.com/gohugoio/hugo/releases/tag/v0.87.0

https://github.com/adityatelange/hugo-PaperMod/blob/975972e04181007c61302054d18735dc440a0586/layouts/_default/archives.html#L36

https://github.com/adityatelange/hugo-PaperMod/blob/975972e04181007c61302054d18735dc440a0586/layouts/partials/post_meta.html#L3-L5
