### ISSUE TITLE
Command line error in wiki regarding installation as a submodule

### ISSUE THREAD

**Issue by McPringle** [adityatelange/hugo-PaperMod#841]
The order of the command is wrong. The `depth` parameter is shown last, which does not work for the submodule command. The parameter needs to be moved before the repository URL.

**Wrong:**
```
git submodule add https://github.com/adityatelange/hugo-PaperMod.git themes/PaperMod --depth=1
```

**Correct:**
```
git submodule add --depth=1 https://github.com/adityatelange/hugo-PaperMod.git themes/PaperMod
```

For the clone command above this section, parameters are allowed after the repository URL. But not for the submodule command. To be consistent, you might want to change it, too. But you don't need to.

**Comment by adityatelange** [comment]
Hi @McPringle updated the wiki with the correct command. 
Thanks for reporting 👍
