### ISSUE TITLE
Document the role of the parameters "privacy"

### ISSUE THREAD

**Issue by RoneoOrg** [adityatelange/hugo-PaperMod#865]
See the [config example](https://github.com/adityatelange/hugo-PaperMod/blob/exampleSite/configTaxo.yml#L9). A search in the whole repo does not give any result

**Comment by adityatelange** [comment]
It has been a part of Hugo pls refer hugo docs 

We cannot document each and every part mentioned. Users are expected to search Hugo docs as well as PaperMod docs for SSG related and theme related config respectively.
