### ISSUE TITLE
add icon for keyoxide

### ISSUE THREAD

**Issue by techducks** [adityatelange/hugo-PaperMod#866]
can someone help adding an icon for keyoxid?

Website:
https://keyoxide.org/

Logo:
https://docs.keyoxide.org/keyoxide/design/

**Comment by Lovegupta112** [comment]
Yes.I can but could you explain where you have to add icon ??

**Comment by techducks** [comment]
I do not understand the question.

**Comment by techducks** [comment]
> Yes.I can but could you explain where you have to add icon ??

I do not understand the question.

**Comment by mwt** [comment]
I've done this before, but the icon just looks terrible when sized down :frowning:
