### ISSUE TITLE
[bug]after first installation, can not build up 

### ISSUE THREAD

**Issue by 1eez** [adityatelange/hugo-PaperMod#877]
the following message:

➜  hugo serve
Start building sites …
hugo v0.88.1+extended darwin/amd64 BuildDate=unknown
ERROR 2022/04/12 15:16:02 render of "page" failed: execute of template failed: template: _default/single.html:3:5: executing "_default/single.html" at <partial "head.html" .>: error calling partial: execute of template failed: template: _internal/opengraph.html:37:17: executing "_internal/opengraph.html" at <index $siteSeries ($name | urlize)>: error calling index: index of untyped nil
ERROR 2022/04/12 15:16:02 render of "page" failed: execute of template failed: template: _default/single.html:3:5: executing "_default/single.html" at <partial "head.html" .>: error calling partial: execute of template failed: template: _internal/opengraph.html:37:17: executing "_internal/opengraph.html" at <index $siteSeries ($name | urlize)>: error calling index: index of untyped nil
Error: Error building site: failed to render pages: render of "page" failed: execute of template failed: template: _default/single.html:3:5: executing "_default/single.html" at <partial "head.html" .>: error calling partial: execute of template failed: template: _internal/opengraph.html:37:17: executing "_internal/opengraph.html" at <index $siteSeries ($name | urlize)>: error calling index: index of untyped nil
Built in 2519 ms

**Comment by adityatelange** [comment]
Use bug report template ton report bugs
