### ISSUE TITLE
Archives page not work in another language

### ISSUE THREAD

**Issue by newvertex** [adityatelange/hugo-PaperMod#88]
Hi,  
I'm trying to build a multilingual blog with this theme and I get 404 error when try to open archives page in another language other than default one!!!!  
the default language archives page works nice `localhost:1313/archives` but when try to open archives in another language i.e: `localhost:1313/en/archives` I get 404 !!!!

I don't care about month localization I just want to list posts archive in any language separately.
other things works fine and thanks for the great job 👍

I create a test repo [here](https://github.com/newvertex/HugoPaperMod_test)

let me know if I made a mistake, thanks

**Comment by adityatelange** [comment]
@newvertex 

create `content/archive.<lang>.md` for it to be dispalyed for specific language

---

ex `archive.es.md`

```yml
---
title = "archivo"
layout = "archives"
---
```

**Comment by newvertex** [comment]
@adityatelange  

thank you it worked well 
I think this have to be added to the documentation
