### ISSUE TITLE
[BUG] You are indexing 404 page

### ISSUE THREAD

**Issue by git-Hmmm** [adityatelange/hugo-PaperMod#887]
![image](https://user-images.githubusercontent.com/102938585/164149679-8475c179-4a3c-4e30-a3be-cdc190087582.png)
Please don't use index, follow here at 404 page it can cause random issues that can take several hours to sort out.

**Comment by adityatelange** [comment]
> ![image](https://user-images.githubusercontent.com/102938585/164149679-8475c179-4a3c-4e30-a3be-cdc190087582.png) Please don't use index, follow here at 404 page it can cause random issues that can take several hours to sort out.

Can you explain what 'random issues' you have faced?
