### ISSUE TITLE
When hosting on github the theme is not rendered correctly. 

### ISSUE THREAD

**Issue by MariosKaramanis** [adityatelange/hugo-PaperMod#89]
I have the following code:

https://github.com/MariosKaramanis?tab=repositories

Here you can see the two repositories I am using. 
marioskaramanis.github.io contains the public contents after running `hugo -t PaperMod`

and marioskaramanis-blog contains the files I used to build the hugo website.

When I run the code locally using `hugo server` I am getting the desired format: https://prnt.sc/vqxj5j
but when I host it in github, I am getting this: https://marioskaramanis.github.io/ 

I checked my yaml file and there is a correct mapping between the baseUrl and the host url.

It seems that it does not find the css correctly or I am missing some configurations. Could you please help me out? 

Thanks a lot!

**Comment by adityatelange** [comment]
@MariosKaramanis add proper baseURL 
https://github.com/MariosKaramanis/marioskaramanis-blog/blob/main/config.yml#L1

baseURL: "https://marioskaramanis.github.io/"

**Comment by MariosKaramanis** [comment]
This is what I had in the beginning and it didn't work. I will try tomorrow again and let you know.

**Comment by adityatelange** [comment]
> This is what I had in the beginning and it didn't work. I will try tomorrow again and let you know.

I see you had `baseURL: "http://marioskaramanis.github.io"` it is https rather than http.

**Comment by MariosKaramanis** [comment]
I can't try on github right now. But the local index.html file gives again the same undesired result.

**Comment by MariosKaramanis** [comment]
I just updated both files. I added the baseUrl as you mentioned: https://github.com/MariosKaramanis/marioskaramanis-blog/blob/main/config.yml

Then I built the project with hugo -t PaperMod, and then I updated the files of the website repository

Again it does not work :(

**Comment by adityatelange** [comment]
> I just updated both files. I added the baseUrl as you mentioned: https://github.com/MariosKaramanis/marioskaramanis-blog/blob/main/config.yml
> 
> Then I built the project with hugo -t PaperMod, and then I updated the files of the website repository
> 
> Again it does not work :(

Stop complaining and look into the problem !
No one else is facing issues but you are.

try rebuiling with `hugo --cleanDestinationDir --gc`

**Comment by MariosKaramanis** [comment]
You see all the codes. How is it possible that it does not work ? I followed exactly the instructions. I am not complaining. I just asked a question. If you don't know the answer it is totally fine. 

Btw I just posted a question on stackoverflow: https://stackoverflow.com/questions/65040931/hugo-site-renders-locally-but-not-on-github

**Comment by adityatelange** [comment]
@MariosKaramanis You should look at what the error is, instead asking me to find out the error !

Have you seen the error in your browser dev tools ? console..!? ig not

**Comment by MariosKaramanis** [comment]
Please check the errors in the update section of my question:
https://stackoverflow.com/questions/65040931/hugo-site-renders-locally-but-not-on-github

**Comment by adityatelange** [comment]
@MariosKaramanis 

Read 
https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity#How_browsers_handle_Subresource_Integrity

This is what papermod uses by default

https://github.com/adityatelange/hugo-PaperMod/blob/master/layouts/partials/head.html#L23-L26

---

your resource file conflicts with generated hash by hugo, thus browser denies loading it as per the rule !

---

what you can do is rm your whole gh pages repo and rebuild it/ re deploy it !

**Comment by MariosKaramanis** [comment]
if I replace integrity="{{ $stylesheet.Data.Integrity }}" with integrity="" it will work right?

**Comment by MariosKaramanis** [comment]
Update:

My issue was solved. I did exactly what I described in the previous comment and everything worked perfectly. Thanks for the help. You made a great theme!

**Comment by MariosKaramanis** [comment]
Actually it didn't work. I am not sure how to make integrity="" in this file.

**Comment by MariosKaramanis** [comment]
I confirmed my last comment. It worked !

**Comment by adityatelange** [comment]
Hey @MariosKaramanis, 
I have added an option to disable Fingerprinting, just in case someone in future has the same issue !

**Comment by MariosKaramanis** [comment]
Thanks, I am sure this will benefit some future readers. Thanks for the theme and for your help.

**Comment by h0wardch3ng** [comment]
This bug still exists.

**Comment by labeveryday** [comment]
Yes this is still an issue. If you do this fix before sure to clear your cache. https://github.com/lxndrblz/anatole/issues/114#issuecomment-828750909

**Comment by marchyeler** [comment]
issue still exists but removing setting integrity="" works

**Comment by oxendy** [comment]
Holy cow 2023 and it's still a prevailing issue.
