### ISSUE TITLE
Drop title attribute from main menu

### ISSUE THREAD

**Issue by peterk** [adityatelange/hugo-PaperMod#893]
First of all, thank you for all the work you have put into making a great hugo theme!

The default top menu creates an [unnecessary title attribute](https://www.tpgi.com/using-the-html-title-attribute/) repeating the page name. Tested in Theme Version: master as of today.

Current output:
```
<li><a href="http://localhost:1313/about/" title="About"><span>About</span></a></li>
```
Suggested output:
```
<li><a href="http://localhost:1313/about/"><span>About</span></a></li>
```

**Comment by adityatelange** [comment]
I'd recommend doing it on your exisiting website 
![image](https://user-images.githubusercontent.com/21258296/164971509-a02f3bb7-9fe0-4d44-a804-aa7b12bda304.png)

**Comment by peterk** [comment]
I am. I am moving my website from Wordpress to Hugo and I am in the process of cleaning it up. But errors in my blog wordpress theme har little to do with improvements in PaperMod, right?

**Comment by adityatelange** [comment]
> I am. I am moving my website from Wordpress to Hugo and I am in the process of cleaning it up. But errors in my blog wordpress theme har little to do with improvements in PaperMod, right?

Solving non-existent problems is not gonna lead to improvements.

**Comment by peterk** [comment]
> Solving non-existent problems is not gonna lead to improvements.

Sorry if I offended you in some way.
