### ISSUE TITLE
Got to Top button overlaps Next Page button on mobile

### ISSUE THREAD

**Issue by fabiansteuer** [adityatelange/hugo-PaperMod#91]
<img width="346" alt="overlap" src="https://user-images.githubusercontent.com/24892157/100516548-988cc480-317c-11eb-9666-01c134c93194.png">

Not sure how to improve this. Maybe center the Go to Top button on small screens in order to not overlap the Previous/Next Page buttons?

Thanks for the great work overall. 👏 I'm probably going to use this theme for my personal blog.

**Comment by adityatelange** [comment]
@fabiansteuer Yes I am aware of that, I am still searching for new position for go-to-top button, which won't affect aesthetics as well as accessibility. :)

**Comment by ITAYC0HEN** [comment]
I think that if you'll center the "Next Page" button on mobile, and keep the same vertical position (i.e don't touch) it will lookg good

**Comment by adityatelange** [comment]
How about 

| | |
| - | - |
| a | ![image](https://user-images.githubusercontent.com/21258296/100549998-bfdab300-329c-11eb-8c64-5a5a2d71cd9a.png) |
| b | ![image](https://user-images.githubusercontent.com/21258296/100550005-cbc67500-329c-11eb-9a27-1e542cb639ed.png) |

just for `list` pages (where `next` or `prev` buttons will be present)

**Comment by fabiansteuer** [comment]
I agree, option A looks nicer. 👍
