### ISSUE TITLE
[Question] Archives to include multiple subfolders?

### ISSUE THREAD

**Issue by 4nner** [adityatelange/hugo-PaperMod#912]
Is there a way that the archives page can include the posts available in multiple subfolders?
I will make a sample hierarchy to make it easier to understand.
```
├── content/
│   ├── archives.md 
│   ├── articles/
│   └── posts/
├── static/
└── themes/
    └── PaperMod/
```
The goal is to make archives.md show the posts that are in articles and the one that are in 'posts' rather than only one of them.

Thanks!

**Comment by adityatelange** [comment]
Yes https://github.com/adityatelange/hugo-PaperMod/commit/fc87fc3a29e8e515dff866159601a734e3ad4a2f
