### ISSUE TITLE
Converting Pagination buttons translation

### ISSUE THREAD

**Issue by adityatelange** [adityatelange/hugo-PaperMod#914]
We had a discussion poll here https://github.com/adityatelange/hugo-PaperMod/discussions/892

Which results update the Pagination buttons that say: `Next Page` & `Prev Page`to  `Next` & `Prev` respectively.
So calling out everyone who has previously contributed to translations to update the strings present at https://github.com/adityatelange/hugo-PaperMod/tree/master/i18n
which updates the strings:
https://github.com/adityatelange/hugo-PaperMod/blob/b0ab8ea4959c07fe13c1667297e986e1d65aafe1/i18n/en.yaml#L1-L5
to
https://github.com/adityatelange/hugo-PaperMod/blob/cf5b2d59b290a86a9390a685bfcfb584346f0282/i18n/en.yaml#L1-L5

**Comment by IvanAprea** [comment]
it still happen? can i work on that?

**Comment by adityatelange** [comment]
> it still happen? can i work on that?

Yes Sure. Please update translations for languages you are sure with.

**Comment by IvanAprea** [comment]
Hey, i will do the spanish translation, but i have problems to do the PR. Is needed to have the issue assigned to me?
