### ISSUE TITLE
[BUG]Code block line number can't be shown properly when the number is bigger than two digit 

### ISSUE THREAD

**Issue by gingerhot** [adityatelange/hugo-PaperMod#923]
**Describe the bug**
The line number bigger than 99 can't be shown properly. And there's a tiny scroll bar on the bottom, you need to scroll to see the whole number.

 - Device/Os: macOS
 - Type: Desktop
 - Browser and version: Chrome 101.0
 - Hugo Version: v0.99.1 
 - Theme Version: master

Step:
1. setup hugo, add PaperMod as a theme
2. put [the post](https://github.com/xianmin/hugo-theme-jane/blob/master/exampleSite/content/post/syntax-highlighting.md) under `content/post`.
3. check the post's last part,  `highlight shortcode`,  as an example

**Expected behavior**:

The line number bigger than 99 should be shown properly. And no scroll bar is shown.

**Screenshots**

<img width="436" alt="WechatIMG2085" src="https://user-images.githubusercontent.com/1658618/169773059-3927810d-b9e8-4577-a431-29fbc4bfe1f0.png">
<img width="397" alt="WX20220523-155122@2x" src="https://user-images.githubusercontent.com/1658618/169773546-4a3c01eb-8ac8-4d24-b389-594ab44f0f28.png">

**Comment by adityatelange** [comment]
Hello @gingerhot 

Trying on my local instance I do not see any effect over 2+ digits line nums

![image](https://user-images.githubusercontent.com/21258296/170833451-f14cd7a7-f242-49f1-9f1a-4505940c6f96.png)

**Comment by gingerhot** [comment]
@adityatelange Thank you! I'll have a try.

**Comment by JoJoJotarou** [comment]
@adityatelange  I got this too. Have you ever used highlight lines? like this:
`````text
```html {hl_lines=["1-3"],linenostart=199}
```
`````
Please see https://github.com/adityatelange/hugo-PaperMod/discussions/922

**Comment by gingerhot** [comment]
> @adityatelange I got this too. Have you ever used highlight lines? like this:
> 
> ```
> ```html {hl_lines=["1-3"],linenostart=199}
> ```
> ```
> 
> Please see #922

Yes, that's the case. Thank you!

**Comment by adityatelange** [comment]
Hello @gingerhot @JoJoJotarou Can you try putting thefollowing in config.yml

```yml
# baseURL: "https://adityatelange.github.io/"
# theme: PaperMod
pygmentsUseClasses: true
```

**Comment by adityatelange** [comment]
## Note:

> @adityatelange When I set `pygmentsUseClasses: true` or `markup.highlight.noClasses=false`, the highlight just dissapeared. Here's the website https://github.com/QuarticCat/QuarticCat.github.io

True that will happen you will have to use https://gohugo.io/content-management/syntax-highlighting/#generate-syntax-highlighter-css and generate a style-sheet for highlighting code or use highlight.js
Can do 
```sh
hugo gen chromastyles --style dracula > assets/css/extended/dracula.css
```

_Originally posted by @adityatelange in https://github.com/adityatelange/hugo-PaperMod/issues/695#issuecomment-1152537639_

**Comment by gingerhot** [comment]
> Hello @gingerhot @JoJoJotarou Can you try putting thefollowing in config.yml
> 
> ```yaml
> # baseURL: "https://adityatelange.github.io/"
> # theme: PaperMod
> pygmentsUseClasses: true
> ```
> 
> or `markup.highlight.noClasses=false`

This config setting works for me, no need to generate a style-sheet at all. Thank you a lot!
