### ISSUE TITLE
Force dark or light

### ISSUE THREAD

**Issue by chris-short** [adityatelange/hugo-PaperMod#931]
I would love to be able to keep the theme in only light mode. I’ve seen other themes implement this feature and is handy for those of us with certain embeds that aren’t dark mode friendly.

**Comment by adityatelange** [comment]
Please checkout `defaultTheme` Param here
https://github.com/adityatelange/hugo-PaperMod/wiki/Variables#site-variables-under-params

**Comment by chris-short** [comment]
Thank you so much!

*Chris Short* <https://linktr.ee/TheChrisShort>
He/Him/His
TZ=America/Detroit
