### ISSUE TITLE
[BUG] post nav links works for only one section

### ISSUE THREAD

**Issue by fplanque** [adityatelange/hugo-PaperMod#940]
**Describe the bug**

 - Device/Os: any
 - Type: desktop
 - Browser and version [e.g. Chrome 86.0]: any 
 - Hugo Version [ >=0.83.0 expected]: v0.100.1+extended darwin/amd64
 - Theme Version [e.g. v4.0, master, or commit-id ]: master branch  from 2022-06-11

**Steps to reproduce the behavior:**

1. Enable `params:    ShowPostNavLinks: true` in hugo config. 
2. Create at least 2 main sections, let's say `/content/dev/` and `/content/misc/`. 
3. Navigate to a post in dev, like `/dev/post21/`. The post nav links to previous and next post appear at the bottom (as expected)
4. Navigate to a post in misc, like `/misc/post42/`. The post nav links to previous and next post DO NOT appear at the bottom!  

**Expected behavior**:

I expect the post nav links to appear in every section of the site.

But they only appear in the first one (in alphabetical order it seems)

**Screenshots**

This appears only in section `dev`:

<img width="748" alt="2022-06-11_21-57-11" src="https://user-images.githubusercontent.com/1156771/173202985-4dbca44c-5a5e-415f-917e-44b378fb678e.png">

**Additional context**

I traced it down to the partial template `/themes/papermod/layouts/partials/post_nav_links.html`:

This partial template does get called as expected but the first lines fail in the case of additional sections:

    {{- $pages := where site.RegularPages "Type" "in" site.Params.mainSections }}
    {{- if and (gt (len $pages) 1) (in $pages . ) }}

The second line is false in all sections but the first one (yet I guarantee there are many posts in each section).

**Comment by loyayz** [comment]
config.yml
```
params:
    mainSections:
        - dev
        - misc
```

https://gohugo.io/functions/where/#mainsections

**Comment by fplanque** [comment]
Thank you.

I guess this is not a bug then.

I suggest to add a reference to https://gohugo.io/functions/where/#mainsections in the doc wiki in these 2 places:

1. https://github.com/adityatelange/hugo-PaperMod/wiki/Features#other-posts-suggestion-below-a-post
2. description of `ShowPostNavLinks` here: https://github.com/adityatelange/hugo-PaperMod/wiki/Variables#site-variables-under-params. (or give it a "details" section like other variables have)
