### ISSUE TITLE
Add Social Icon for Sourcehut

### ISSUE THREAD

**Issue by biehlerj** [adityatelange/hugo-PaperMod#963]
Website(s) in question:

- [git.sr.ht](https://git.sr.ht)
- [sourcehut](https://sourcehut.org/)

**Comment by claudinec** [comment]
Just commenting to say that this doesn't seem to be documented in the [wiki](https://github.com/adityatelange/hugo-PaperMod/wiki/Icons) (I only realised there was a sourcehut icon by searching the repo).
