### ISSUE TITLE
Breadcrumbs does not show sections/subsections

### ISSUE THREAD

**Issue by yatharthb97** [adityatelange/hugo-PaperMod#966]
The breadcrumbs on the website only includes `home`.

For this URL: https://yatharthb97.github.io/blog/welcome/
The breadcrumbs are:

![image](https://user-images.githubusercontent.com/52491002/177287693-7e2500c7-f575-4d80-84c1-c38789ea7c20.png)

Website: https://yatharthb97.github.io/
Source: https://github.com/yatharthb97/yatharthb97.github.io

`contents` folder:
/content/
│   archives.md
│   search.md
├───aboutme
│       _index.md
├───blog
│       Welcome!.md
│       _index.md
├───categories
│       _index.md
├───collaborate
│       _index.md
├───gallery
│       patchyparticles.md
│       _index.md
├───projects
│       KGLab.md
│       python-Time-Literals.md
│       _index.md
├───publications
│       BeetleBox.md
│       ScienceThroughVisuals_TIFRH.md
│       _index.md
└───tags
        _index.md

Config file declares the mainSections:
![image](https://user-images.githubusercontent.com/52491002/177288217-a7557805-08e9-49f0-8117-c34fb834278c.png)

**Comment by adityatelange** [comment]
Interesting, can you use bug report template to report this?

**Comment by adityatelange** [comment]
@yatharthb97 your blog's _index.md does not have a title field in it. 
add it and it'll display fine .. not a bug.
![image](https://user-images.githubusercontent.com/21258296/178110090-9b923e55-b607-4659-8d5f-a8d206b58746.png)
