### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by schwrzstrbn** [adityatelange/hugo-PaperMod#973]
**Describe the bug**
The theme cannot be changed and I set the default theme to `defaultTheme: dark` but only displayedt the light theme. It only happened earlier, must be affected by recent commits on the repo.

 - Device/Os: ALL
 - Type: BOTH
 - Browser and version: ALL
 - Hugo Version [ >=0.83.0 expected]: v0.93.3
 - Theme Version [e.g. v4.0, master, or commit-id ]: [621c9f6](https://github.com/adityatelange/hugo-PaperMod/commit/621c9f60fbf5fb96415fa2c031d50c83514164a8)

**Steps to reproduce the behavior:**
1. All I did was clone the upstream, and hit `hugo serve` the bug showed up.

**Expected behavior**:

**Screenshots**

**Additional context**

**Comment by adityatelange** [comment]
Can you share the source where this can be reproduced? Or maybe an example repo?

**Comment by schwrzstrbn** [comment]
> Can you share the source where this can be reproduced? Or maybe an example repo?

I found the root cause, It was not a bug. Just a mistake while modifying on my end. Sorry.
I'm closing this issue now. Thanks anyway.
