### ISSUE TITLE
[feature] embed svg icon in the header

### ISSUE THREAD

**Issue by icy-comet** [adityatelange/hugo-PaperMod#974]
This is a continuation of the discussion in the Discord server started on May 15th.

Basically, I had proposed that if the header icon is a SVG it should be embedded into the HTML doc as-it-is instead of using it as the `src` of a image tag for easier styling, e.g. switching SVG color with light/dark color mode.

This was supported by @adityatelange, after which he proposed adding `label.iconSVG` key for the same and that the `label.icon` key would take precedence over it.

This warrants a very small change in the existing template. However, I haven't heard back from @adityatelange and am waiting for confirmation on whether or not the height of the SVG be manipulated in the template to respect the `label.iconHeight` key.

Following is the diff of the changes if `label.iconHeight` is to be respected:
```diff
  <img src="{{- site.Params.label.icon | absURL -}}" alt="logo" aria-label="logo"
      height="{{- site.Params.label.iconHeight | default "30" -}}">
  {{- end -}}
+ {{- else if hasPrefix site.Params.label.iconSVG "<svg" }}
+     {{ site.Params.label.iconSVG | replaceRE `\s*height\s*=\s*"[\w\s]*"|\s*width\s*=\s*"[\w\s]*"` "" | replaceRE "^<svg" (printf `<svg height="%d"` site.Params.label.iconHeight) | safeHTML }}
  {{- end -}}
  {{- $label_text -}}
```

If `label.iconHeight` is not respected, the regex part wouldn't be necessary.

**Comment by adityatelange** [comment]
Is this a complaint?

**Comment by icy-comet** [comment]
I'm sorry if it came across as if I am complaining.

I was just looking for a confirmation on the matter to proceed with the PR.

**Comment by adityatelange** [comment]
> I didn't mean for it to come across as a complaint.
> 
> I was just looking for a confirmation on the matter to proceed with the PR.

I had already said we can go ahead in discord. Anyways about the svg height, we don't need to implement that. 
It is redundant to add iconHeight to replace height in svg. User can add height directly in svg.
