### ISSUE TITLE
Any interest in implementing a raised header with shadow? 

### ISSUE THREAD

**Issue by singhkays** [adityatelange/hugo-PaperMod#98]
I implemented a crude version using the following custom CSS but I need to do a bit more testing to see if this works across all scenarios. 

Any interest in implementing a more standard/pretty version that's better aligned with the goals of the theme? 

```css
    box-shadow: 0 .125rem .25rem rgba(0,0,0,.075);
    position: sticky;
    top: 0;
    z-index: 1020;
    background-color: #fff !important;
```

![image](https://user-images.githubusercontent.com/6164178/100584733-5610d800-32a1-11eb-9314-7afd71fdf8e8.png)

EDIT: Sharing the inspiration for this - https://twitter.com/brian_lovin/status/1333155693008863232.

![image](https://user-images.githubusercontent.com/6164178/100584976-ac7e1680-32a1-11eb-8d8b-1afbc15219b5.png)

**Comment by kdkasad** [comment]
I like the look of it, but it does go against the "paper" style, since
it creates a sort of "raised" section, i.e. not one continuous page like
a piece of paper.

That being said, I'd probably still use it. It would also be easy enough
to implement as a config parameter, so I think it's a good idea.

**Comment by singhkays** [comment]
Aditya - Any interest in this or does this deviate too much from the paper principles? 

You might already know this but I saw another theme that uses this 1.38 KB library to achieve a header that responds to user scroll https://wicky.nillia.ms/headroom.js/

**Comment by adityatelange** [comment]
@singhkays sorry closing without responding, you can add custom-css by using [Bundling Custom css with theme’s assets](https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-faq/#bundling-custom-css-with-themes-assets).
