### ISSUE TITLE
[BUG] Additional , inside ItemListElement

### ISSUE THREAD

**Issue by ganeshdipdumbare** [adityatelange/hugo-PaperMod#980]
**Describe the bug**
As you can see that the additional , is added in the itemListElement at the start when build is done.
```
{
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  "itemListElement": [, 
    {
      "@type": "ListItem",
      "position":  2 ,
      "name": "Posts",
      "item": "https://www.ganeshdip.dev/posts/"
    }
  ]
}
```

 - Device/Os: Linux
 - Type: Desktop
 - Browser and version [e.g. Chrome 86.0]: N/A
 - Hugo Version [ >=0.83.0 expected]: v0.101
 - Theme Version [e.g. v4.0, master, or commit-id ]: master

**Steps to reproduce the behavior:**

**Expected behavior**:
correct index.html should be generated.

**Screenshots**

**Additional context**

**Comment by adityatelange** [comment]
Hi @ganeshdipdumbare can u share the source/ sample of this where it is reproducible?

**Comment by ganeshdipdumbare** [comment]
Hi @adityatelange Please check out this commit branch - https://github.com/ganeshdipdumbare/ganeshdip/tree/5a5b1b755693e1c56fa8d1aa28a5e198311d7e8e for the same.

**Comment by adityatelange** [comment]
![image](https://user-images.githubusercontent.com/21258296/181915329-2443c818-6e2c-45f2-a649-d66e35c68080.png)

Seems fine to me, pls verify bugs before u create an issue

**Comment by matteocontrini** [comment]
I'm seeing this issue, see the source code of [this page](https://blog.contrini.it/aspnet-core-authentication-schemes/).

```html
<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  "itemListElement": [, 
    {
      "@type": "ListItem",
      "position":  2 ,
      "name": "Posts",
      "item": "https://blog.contrini.it/posts/"
    }, 
    {
      "@type": "ListItem",
      "position":  3 ,
      "name": "Working with custom authentication schemes in ASP.NET Core 6.0 Web API",
      "item": "https://blog.contrini.it/aspnet-core-authentication-schemes/"
    }
  ]
}
</script>
```
