### ISSUE TITLE
[BUG]: Breadcrumbs

### ISSUE THREAD

**Issue by Shenlong616** [adityatelange/hugo-PaperMod#986]
**Describe the bug**

 - Device/Os: Windows 11
 - Type: Desktop
 - Browser and version:  Chrome 103.0.5060.114
 - Hugo Version: v0.101.0
 - Theme Version: master

**Screenshots**

![shenlong616 github io_posts_ (1)](https://user-images.githubusercontent.com/15698245/179403587-f70681d5-f546-417d-b435-b956c7e07520.png)

**Additional context**

instead of displaying breadcrumb as `Home > Posts` text, but it shows the `Home` text only?

[Posts page](https://shenlong616.github.io/posts/)

**Comment by yatharthb97** [comment]
This seems like the default behaviour for breadcrumbs on PaperMod.

**Comment by jiangqucheng** [comment]
It seems a consistent display rule, that every page just show the parent link in its breadcrumbs. 
Inside each page of the post content, such as: ```/post/first_post.md```, the breadcrumbs shows ```Home>Posts```, not ```Home>Posts>First_post```. 

But you really made a great bug report hint. 
Inside ```themes\PaperMod\layouts\partials\breadcrumbs.html```, the code now can't handle a 3+ levels directory structure. 
I will create another issue for this.

**Comment by jiangqucheng** [comment]
I got the solution, delete the ```.Parent``` in ```themes\PaperMod\layouts\partials\breadcrumbs.html``` Line 3. And yo'll get ```Home > Posts``` 

![image](https://user-images.githubusercontent.com/12996850/180674531-73074894-5c13-41a8-bc58-0155721c8338.png)

**Comment by xdavidchen** [comment]
Any idea why the breadcrumbs only work when I run with local host `hugo server`?

WORKS:

<img width="797" alt="Screen Shot 2023-07-17 at 7 48 35 PM" src="https://github.com/adityatelange/hugo-PaperMod/assets/98777967/62cdb660-46c5-438e-a83a-af3fe172d722">

When I git push it doesn't work anymore.

DOESN'T WORK:

<img width="797" alt="Screen Shot 2023-07-17 at 7 48 48 PM" src="https://github.com/adityatelange/hugo-PaperMod/assets/98777967/f622f220-da73-40ca-8034-0532cf9bad53">


Below is my ShowBreadCrumbs.html file:

```
{{- if (.Param "ShowBreadCrumbs") -}}
<div class="breadcrumbs">
    {{- $url := replace .Permalink (printf "%s" site.BaseURL) "" }}
    {{- $lang_url := strings.TrimPrefix (printf "%s/" .Lang) $url -}}

    <a href="{{ "" | absLangURL }}">{{ i18n "home" | default "Home" }}</a>
    {{- $scratch := newScratch }}
    {{- range $index, $element := split $lang_url "/" }}

    {{- $scratch.Add "path" (printf "/%s" $element )}}
    {{- $bc_pg := site.GetPage ($scratch.Get "path") -}}

    {{- if (and ($bc_pg) (gt (len . ) 0))}}
    {{- print "&nbsp;»&nbsp;" | safeHTML -}}<a href="{{ $bc_pg.Permalink }}">{{ $bc_pg.Name }}</a>
    {{- end }}

    {{- end -}}
</div>
{{- end -}}
```
