### ISSUE TITLE
Menu items overflow to multiple lines on mobile

### ISSUE THREAD

**Issue by singhkays** [adityatelange/hugo-PaperMod#99]
I've noticed if you have a lot of menu items like in my blog, the menu items can overflow into multiple lines. Example screenshot from desktop below, but on mobile it appears similar. 

![image](https://user-images.githubusercontent.com/6164178/100585649-c2d8a200-32a2-11eb-8be0-664b9b629dff.png)

**Suggestion**: It would be better if the menu items were included in an accordian/hamburger button if the width is below a certain threshold

**Example** of this in action can be seen here - https://themes.gohugo.io//theme/hugo-profile/post/markdown-syntax/
![image](https://user-images.githubusercontent.com/6164178/100585857-16e38680-32a3-11eb-950f-4372d6cfd157.png)

**Comment by adityatelange** [comment]
@singhkays 
What have you done here is zoomed-in on desktop screen.
However, this is not current behavior on mobile device.

There is a nice horizontal scrolling menu which also saves the scroll position on reload (for many menu items) !

Also I won't compare papermod with any theme based on bootstrap, like the theme you have mentioned.

**Comment by singhkays** [comment]
> There is a nice horizontal scrolling menu which also saves the scroll position on reload (for many menu items) !

I don't see it though. Posted an actual screenshot from mobile

![Screenshot_20201130-082330_Chrome](https://user-images.githubusercontent.com/6164178/100645282-4d47f280-32f1-11eb-9ceb-c354808b55bc.jpg)

> Also I won't compare papermod with any theme based on bootstrap, like the theme you have mentioned

I don't understand. Don't know that theme's based on bootstrap but doesn't matter. What I was mentioning was a design paradigm 
https://www.nngroup.com/articles/mobile-subnavigation/

**Comment by adityatelange** [comment]
> > There is a nice horizontal scrolling menu which also saves the scroll position on reload (for many menu items) !
> 
> I don't see it though. Posted an actual screenshot from mobile
> 
Sorry my bad, it was broken from https://git.io/JIfLS Please check if that's fixed now :)

> > Also I won't compare papermod with any theme based on bootstrap, like the theme you have mentioned
> 
> I don't understand. Don't know that theme's based on bootstrap but doesn't matter. What I was mentioning was a design paradigm
> https://www.nngroup.com/articles/mobile-subnavigation/

I said that because bootstrap is 'perfect' ! Papermod is just another side-project theme :p 
Also this will make the theme similar to many others available. 
Currently papermod has a nice userbase (including you) and I guess they like the way menu is rn rather than hamburger style one. This change is diverging from design aspect from og theme paper.

**Comment by singhkays** [comment]
> Sorry my bad, it was broken from https://git.io/JIfLS Please check if that's fixed now :)

Got it, it works now 👍 

> Currently papermod has a nice userbase (including you) and I guess they like the way menu is rn rather than hamburger style one. 

I wouldn't take that to mean they're happy with it :) could also be that others might not have as many menu items. 
I gotta say the horizontal bar does look pretty weird. I don't think I've seen a similar design paradigm anywhere else on mobile. 

> This change is diverging from design aspect from og theme paper.

At some point, I feel like you can diverge as I see the amount of additional work you've done over the base Paper them 😉

**Comment by adityatelange** [comment]
> At some point, I feel like you can diverge as I see the amount of additional work you've done over the base Paper them

Yes I agree. But I personally like the design by paper's author !
